### ISSUE TITLE
[BUG] LG C1 not working

### ISSUE THREAD

**Issue by dipar2009** [mariotaku/moonlight-tv#101]
When trying to launch a game, it says: Failed to start connection: Limelight returned 11

**Comment by mariotaku** [comment]
Please check out [Troubleshooting Guide](https://github.com/mariotaku/moonlight-tv/wiki/Troubleshooting) to narrow down the causes of this issue.

**Comment by dipar2009** [comment]
> Please check out [Troubleshooting Guide](https://github.com/mariotaku/moonlight-tv/wiki/Troubleshooting) to narrow down the causes of this issue.

Thank you for your reply. I tried to restart the Nvidia container but had no luck. I have a clean windows install btw. Is there anything else I could try to solve the problem?

**Comment by mariotaku** [comment]
Does streaming work on other clients?

**Comment by mariotaku** [comment]
Also did this version work for you? https://github.com/mariotaku/moonlight-tv/releases/tag/v0.9.6
Some people are experiencing similar issue after upgrading.

**Comment by mariotaku** [comment]
Might be related to #96.

**Comment by dipar2009** [comment]
> Does streaming work on other clients?

Yes it does

**Comment by dipar2009** [comment]
> Also did this version work for you? https://github.com/mariotaku/moonlight-tv/releases/tag/v0.9.6 Some people are experiencing similar issue after upgrading.

I will try it. Thanks

**Comment by dipar2009** [comment]
> Might be related to #96.

The error codes are different, but I will try to get the logs if I can and post them here.

**Comment by mariotaku** [comment]
@dipar2009 Maybe it's because error message has been slightly changed in recent version. It's likely that error 552 is behind that.

**Comment by dipar2009** [comment]
> Can you try if newest v0.9.96 works for you?

That was the one I tried in the first place

**Comment by mariotaku** [comment]
> > Can you try if newest v0.9.96 works for you?
> 
> That was the one I tried in the first place

v0.9.96 is the version I released tonight, also it looks like v0.9.6.

**Comment by mariotaku** [comment]
Did some test, and got some conclusion. First, if you get error 110, then it means there's connection timeout happened between the TV and the computer. You may need to check firewall settings, or simply try to ping your TV to see if you can reach it.
For 552 is more or less a mystery. I never had a chance to reproduce it.

**Comment by dipar2009** [comment]
> Did some test, and got some conclusion. First, if you get error 110, then it means there's connection timeout happened between the TV and the computer. You may need to check firewall settings, or simply try to ping your TV to see if you can reach it. For 552 is more or less a mystery. I never had a chance to reproduce it.

Ok I managed to ping it with success. Nevertheless, I still have error 11/552 :( Are there some other logs I can provide to help find the problem?

**Comment by mariotaku** [comment]
I'm in Moonlight's discord server: https://moonlight-stream.org/discord

**Comment by mariotaku** [comment]
Nice! I'll close for now. In the future I'm planning to add decoder tests for an out-of-box experience.
