### ISSUE TITLE
Option to disable Magic Controller as input

### ISSUE THREAD

**Issue by pagratios** [mariotaku/moonlight-tv#102]
It seems that Magic Remote Controller is recognized as 1st controller to games which games such as eFootball is a problem

It would be useful to have an option to disable the magic remote as a controller

If that is already possible I couldn't find it
moonlight-tv: 0.9.96
WebOS: 4.9.3
Firmware: 05.10.25
TV LG C9

**Comment by pagratios** [comment]
Next week I will own 2x8bitdo, I will try both of them to eFootball2021 to test if both of them will be recognized as 1st and 2nd.
@mariotaku  when I tried efootball2021 I used xbox elite with USB cable and it is recognized as 2nd controller (1st was magic remote)

**Comment by mariotaku** [comment]
Just a bit curious, how can you make sure the remote was treated as a controller? In my code I never did that...

**Comment by pagratios** [comment]
Sorry for the late response,
After connected the 8bitdo to LG everything works perfectly
