### ISSUE TITLE
Keyboard and mouse support

### ISSUE THREAD

**Issue by TekMystic** [mariotaku/moonlight-tv#107]
**Is your feature request related to a problem? Please describe.**
Hi there, I was just wondering whether the lack of proper KB and mouse support as a valid playing option is due to WebOS limitation or an app limitation...  I can use the mouse, but only through WebOS; meaning the pink arrow won't go away and the mouse doesn't act normal, i.e is extremely fast or something

**Comment by mariotaku** [comment]
In webOS mouse will always be treated as remote pointer. So far there is no way capture relative movement of mouse pointer. I'll take a closer look into event system and give you conclusion later.

**Comment by mariotaku** [comment]
Good news! I did some work to hide mouse cursor in streaming, and provide relative mouse movement. One thing to notice however, is the movement isn't really precise, even with your own mouse. It is how webOS handles mouse events.

**Comment by mariotaku** [comment]
Download v1.1.0 to try it out.

**Comment by jumban** [comment]
Hi, I am also trying to use a mouse and keyboard to play some FPS games, and I have tried all the different combinations of the mouse input settings in moonlight but the LG cursor (pink pointer) doesn't disappear. 

Just wondering if this feature was later removed? Thanks for your help! 

Also, thanks for making this wonderful app! 

Currently on v1.6.2

**Comment by mariotaku** [comment]
@jumban Hi, which webOS version do you have? It sounds like a new issue would be better for your case.
