### ISSUE TITLE
[BUG] RDXD_moonlight__Linux Crash

### ISSUE THREAD

**Issue by AleksandrLiadov** [mariotaku/moonlight-tv#110]
**Describe the bug**

After the start any game, the app crashes.

**To Reproduce**
1. Connect with PC
2. Start any game 

**Expected behavior**
I hoped to begin to play.

**LG webOS TV (please complete the following information):**
 - Model: [um7100plb]
 - webOS version [4.9.0]
 - Firmwareversion: 05.00.15

**Additional context**
Geforce experience: 3.23.0.74 (GTX 950M)
Homevrew: 0.2.1
On TV ssh and telnet are opened.
On PC I use "Device Manager for WebOS"

I tried with two version:
- moonlight-tv 0.9.6:
RDXD_moonlight__Linux Crash: moonlight crashes at location ?var?palm?jail?com.limelight.webos?lib?libc-2.24.so (gsignal+0xc4) [0x96b23ec0]____moonlight.9661.1kMYRu.gz (https://pastebin.com/G3Ph77ww)

- moonlight-tv 1.0.1:
RDXD_moonlight__Linux Crash: moonlight crashes at location ?var?palm?jail?com.li                                                                     melight.webos?usr?lib?libkadaptor.so.1.0.0 (_Z11delete_flowP12_FlowManager+0x99)                                                                      [0x94ed525e]____moonlight.10128.3GFGcI.gz (https://pastebin.com/RNWJE4yB)

**Comment by mariotaku** [comment]
Did you tried other decoders? For example SMP or NetCast Legacy

**Comment by AleksandrLiadov** [comment]
Yes, same thing for all 3 decoders :(
![image](https://user-images.githubusercontent.com/72351793/137596205-fb612b74-d9e7-4980-be51-ad055c9a9228.png)

**Comment by mariotaku** [comment]
How about to change audio backend to something else like ALSA or SDL?

**Comment by AleksandrLiadov** [comment]
> How about to change audio backend to something else like ALSA or SDL?

Do you think that the probleme is audio codec? So why when I run the app from terminal it works?

**Comment by mariotaku** [comment]
@AleksandrLiadov I can't say for sure. But according to the second crash dump, the crash occurred in `startAudioStream`. I assume you're accessing with root permission, so that might be some reason too.

**Comment by Redherring32** [comment]
Using the NetCast Legacy video decider, and ALSA audio backend resolved this issue for me on version 1.3.0 and WebOS 4.9.3.

**Comment by AleksandrLiadov** [comment]
> Using the NetCast Legacy video decider, and ALSA audio backend resolved this issue for me on version 1.3.0 and WebOS 4.9.3.

Thanks, now it works perfect!
