### ISSUE TITLE
[COMPAT] 43UK6300PLB

### ISSUE THREAD

**Issue by MrNikolaich** [mariotaku/moonlight-tv#111]
## Basic information

 - Device model: (43UK6300PLB) 
 - Firmware version: (05.40.09) 
 - webOS version: (4.4.0) 
 - Moonlight version: (1.0.1) 
 - Is audio working: (Yes) 
 - Is video working: (1080p60fps) 
 - Is input working: (Gamepad) 

## Description

Update: now it works! I just needed to run GeForce Experience (>_<). 720p and 1080p works perfectly. 1440p and 4K show black screen or artifacts on TV. PC's monitor image looks right for used resolution (I have gtx760ti and 1080p monitor). With Wi-Fi on TV I have high latency, but I swap it on cable and get very clear and smooth gameplay.

Hello! Maybe it's a very dumb question, but how I can to add my PC in Moonlight on TV? I downloaded DevMode Manager v1.4.0 on my PC Windows 7 Pro x64. Then I turned on DevMode on TV, added my TV in Manager and installed Moonlight in "Available" tab. Lanuching Moonlight from DevManager works fine, Moonlight opening in TV. But when I'm trying to add computer and writing computer's IPv4, i got error message "Failed to add computer".
I got IPv4 by CMD command "ipconfig". I'm tried also writing public IPv4, that I found on specified websites. Also both them I tried to use with turned off Windows Firewall and anti-virus soft. Not working.
What I'm doing wrong?
Internet connection on TV by Wi-Fi router, on PC - cable from router. Both them are in same LAN.
Info tab shows that connection is. Terminal tab shows message "Connection error. Press any key to reconnect. Error: Unable to request a pseudo-terminal"

**Comment by mariotaku** [comment]
> No one of them. I'll try it and answer you!

Keep in mind that Moonlight is a *client* of the software mentioned above. Please refer to https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#quick-setup-instructions to setup your PC.

**Comment by mariotaku** [comment]
Nice! For higher resolution there's a chance that you TV doesn't support it. For now I'll close the issue.
