### ISSUE TITLE
Different refresh rates on source and streaming monitor

### ISSUE THREAD

**Issue by dipar2009** [mariotaku/moonlight-tv#113]
My monitor is 1080p 60Hz and I'm trying to stream to a 120Hz 4K HDR TV. As mentioned [here](https://www.reddit.com/r/nvidia/comments/irc3m9/how_to_enable_120hz_modes_in_gamestreammoonlight/), it should work by creating a custom resolution on the Nvidia Control Panel. I went ahead and tried it, and can indeed apply it. In the UFO Test, the 120Hz test passes, but I can tell the video is only 60Hz (also, the information that appears when holding the back button confirms it). I've also changed the settings in Moonlight to 4K 120 and have enough internet bandwidth to make it work.

**Comment by mariotaku** [comment]
Did you try to use 1080p 120fps first? Right now NVIDIA cards on the market can't encode 4K 120fps yet.

**Comment by dipar2009** [comment]
> So I think it's more like a device limitation. Unlike frame rate, 1080p monitor can use 4K because GPU can scale it. But for frame rate, there's no way for GPU to skip it before sending to monitor. Maybe it's better to get a gaming monitor for your need.

I'm going to guess that isn't the problem because other people managed to do it with other versions of Moonlight (the desktop app I assume). I don't have a high refresh monitor or any other device that supports HDMI 2.0/2.1 (apart from my host PC) to test.

**Comment by mariotaku** [comment]
Closing the issue as it's mostly related to the host (and might work with Sunshine now)
