### ISSUE TITLE
PS3 Controller - L2/R2 Treated as digital inputs

### ISSUE THREAD

**Issue by dipar2009** [mariotaku/moonlight-tv#114]
The L2/R2 buttons do not work as analog inputs

**Comment by mariotaku** [comment]
How do you use the controller, did you connect by USB cable or some adapters? Maybe the gamepad mapping to your controller is not well supported. You may want to checkout https://github.com/moonlight-stream/moonlight-docs/wiki/Gamepad-Mapping .

**Comment by mariotaku** [comment]
A lot has been updated since last year (including renewed gamepad support). I'll close this as it's likely outdated.
