### ISSUE TITLE
HDR NOT WORKING[BUG]

### ISSUE THREAD

**Issue by marvellun** [mariotaku/moonlight-tv#118]
I have enabled the SMP decoder. But the HDR doesn't seem to work. The TV doesn't goes into HDR mode. And unlinke android version where I can right click the application and click on view details to check "HDR-YES/NO", here I can't check that also. Apart from that the app is working flawlessly in 4K@120.
P.S - NDL decoder is also working properly.
 - Moonlight version: [1.1.5]
 - TV Model: [48C1PTZ]
 - webOS version [3.20.45]

**Comment by mariotaku** [comment]
HDR is a bit confusing. Is your monitor capable of HDR?

**Comment by marvellun** [comment]
I tried it with with a non-HDR monitor. But the TV doesn't switch to HDR. I also tried an android box connected to the TV with moonlight running on it. It works that way. So I think my monitor is not the issue here. Have also streamed on my phone using moonlight with the same non-HDR monitor and it shows HDR is working.

**Comment by mariotaku** [comment]
To use HDR you must have HDR monitor connected for the screen you're streaming. I'm testing with HDR capable monitor as well to see how it works.
