### ISSUE TITLE
Can't stream with SMP, only NDL [BUG]

### ISSUE THREAD

**Issue by jpstone** [mariotaku/moonlight-tv#125]
**Describe the bug**

When using webOS SMP encoder, streaming tries to connect then disconnects. NDL works fine.

**To Reproduce**

Force it to use webOS SMP encoder then try to launch game.

**Expected behavior**

Properly connect and stream.

**Basic information**

 - Moonlight version: 1.2.2
 - Model: LG TV webOS TV OLED65BXPUA
 - webOS version: 5.3.0

> To check version, go to Settings > Quick Settings > General > About this TV > webOS TV Version

**Comment by mariotaku** [comment]
NDL is the most optimal decoder while all options are for supporting more system versions. I wouldn't consider this as an issue, but something better to add to the doc instead.

**Comment by jpstone** [comment]
I want HDR, which is why I want SMP.

**Comment by mariotaku** [comment]
It looks like you're running webOS 5. Although I didn't get a chance to test, it seems that NDL also has HDR capability on webOS 5+. Would you like to try some testing version with HDR enabled?

**Comment by jpstone** [comment]
Sure that'd be great.

**Comment by mariotaku** [comment]
Yes, the change was made in v1.2.3. Please try [com.limelight.webos_1.2.3_arm.ipk](https://github.com/mariotaku/moonlight-tv/releases/download/v1.2.3-2/com.limelight.webos_1.2.3_arm.ipk) .

**Comment by jpstone** [comment]
Updated to 1.2.3, was able to select HDR, but Moonlight is reporting that nothing supports it when I click on "Info".

For example, shouldn't mstsc.exe support HDR, since HDR is enabled in Windows and outputting HDR to the monitor for the desktop?

**Comment by jpstone** [comment]
FYI, after updating, my controller's left stick's X axis was swapped...right is left and left is right.

**Comment by mariotaku** [comment]
@jpstone It should support HDR. Could you open monitor HDR settings and tick/untick to see if HDR notice is appearing on your TV screen?

**Comment by mariotaku** [comment]
Also I made a release v1.2.4 for x-axis issue.

**Comment by mariotaku** [comment]
HDR is available for NDL now, and issues mentioned above are solved.
