### ISSUE TITLE
App not launching on TV

### ISSUE THREAD

**Issue by FlyingT** [mariotaku/moonlight-tv#126]
Softwareversion: 05.05.70
Model: 55LB670V-ZA
webOS TV-Version: 1.4.0-2532 (afro-ashley)

I installed version 1.26 of Moonlight-tv using dev-manager-desktop and it worked just fine, but when launching the App on the TV it just shows the logo and nothing more. After a few minutes the app closes itself.

Using the IPK for installation results in the same problem.

**Comment by mariotaku** [comment]
Do you mean, you are able to install the app, but you can't start it?

**Comment by FlyingT** [comment]
> Do you mean, you are able to install the app, but you can't start it?

Exactly

**Comment by mariotaku** [comment]
You're running a really old system version, which - I never got a chance to test it. It is possible that we can make it work on your TV, but it will require you to provide some assistance. Are you familiar with Linux command, or willing to give it a shot?

**Comment by FlyingT** [comment]
I have only Windows systems here, but I can give it a try. WebOS TV CLI is installed.
But I suspect the issue is the old TV I'am trying to run it on. If its too much work on your side to make it run, dont bother with it :) TV is in the same room and I could make it work with some 15m HDMI cables as an alternative

**Comment by FlyingT** [comment]
```
C:\webOS_TV_SDK\CLI\bin>ares-device-info --device tv
modelName : 55LB670V-ZA
sdkVersion : 1.4.0
firmwareVersion : 05.05.70

C:\webOS_TV_SDK\CLI\bin>ares-novacom -r 'MOONLIGHT_OUTPUT_NOREDIR=1 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/media/developer/apps/usr/palm/applications/com.limelight.webos/lib XDG_RUNTIME_DIR=/tmp/xdg APPID=com.limelight.webos /media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight'
ares-novacom ERR! CLI: Connection timed out. Please check the device IP address or the port number

C:\webOS_TV_SDK\CLI\bin>
```
Since I can get the modelName and stuff from the TV via CLI, it has to be connected. I dont get why it times out :/

**Comment by mariotaku** [comment]
@FlyingT I think I have missed a parameter.
```
ares-novacom -d tv -r 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/media/developer/apps/usr/palm/applications/com.limelight.webos/lib XDG_RUNTIME_DIR=/tmp/xdg APPID=com.limelight.webos /media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight'
```

**Comment by FlyingT** [comment]
```
C:\webOS_TV_SDK\CLI\bin>ares-novacom -d lgtv-moonshinetest -r 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/media/developer/apps/usr/palm/applications/com.limelight.webos/lib XDG_RUNTIME_DIR=/tmp/xdg APPID=com.limelight.webos /media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight'
sh: syntax error: unterminated quoted string
ares-novacom ERR! Error: Command ''LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/media/developer/apps/usr/palm/applications/com.limelight.webos/lib' exited with code=2 (signal: undefined)
```

**Comment by mariotaku** [comment]
Good morning. Sorry I was performing the command in powershell. If you replace single quotes to double quotes, it should work.

```
ares-novacom -d tv  -r "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/media/developer/apps/usr/palm/applications/com.limelight.webos/lib XDG_RUNTIME_DIR=/tmp/xdg APPID=com.limelight.webos /media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight"
```

**Comment by FlyingT** [comment]
Result:
```
C:\webOS_TV_SDK\CLI\bin>ares-novacom -d lgtv-moonshinetest  -r "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/media/developer/apps/usr/palm/applications/com.limelight.webos/lib XDG_RUNTIME_DIR=/tmp/xdg APPID=com.limelight.webos /media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight"
/media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight: symbol lookup error: /media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight: undefined symbol: SDL_GetPrefPath
ares-novacom ERR! Error: Command 'LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/media/developer/apps/usr/palm/applications/com.limelight.webos/lib XDG_RUNTIME_DIR=/tmp/xdg APPID=com.limelight.webos /media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight' exited with code=127 (signal: undefined)
```

**Comment by mariotaku** [comment]
@FlyingT Thank you. This is very useful information, I'm reviewing APIs now, hopefully it can work for you in future versions.

**Comment by mariotaku** [comment]
@FlyingT Can you try this snapshot? https://github.com/mariotaku/moonlight-tv/actions/runs/1620042392 It's inside webos-snapshot.zip.

**Comment by FlyingT** [comment]
Uninstalled 1.2.6, installed 1.2.7 using the IPK and tried launching it. Problem still persists, it shows the logo and thats it.
I did everything using the device manager for webOS. 

But now it gets a bit ... interesting. After maybe 1-2 minutes showing the logo, I ran this command again:
`ares-novacom -d lgtv-moonshinetest -r "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/media/developer/apps/usr/palm/applications/com.limelight.webos/lib XDG_RUNTIME_DIR=/tmp/xdg APPID=com.limelight.webos /media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight"`

Which resulted in this output: [https://pastebin.com/6gsh64As](https://pastebin.com/6gsh64As)
Aaaand Moonshine suddenly starting. I instantly got a Pairing Code and popup on my system.
Declined, restarted the TV and tried to reproduce everything. Now its back to not starting and this output again:

```
C:\webOS_TV_SDK\CLI\bin>ares-novacom -d lgtv-moonshinetest -r "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/media/developer/apps/usr/palm/applications/com.limelight.webos/lib XDG_RUNTIME_DIR=/tmp/xdg APPID=com.limelight.webos /media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight"
/media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight: symbol lookup error: /media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight: undefined symbol: jdomparser_new
ares-novacom ERR! Error: Command 'LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/media/developer/apps/usr/palm/applications/com.limelight.webos/lib XDG_RUNTIME_DIR=/tmp/xdg APPID=com.limelight.webos /media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight' exited with code=127 (signal: undefined)
```

**Comment by mariotaku** [comment]
Thanks for your testing. I checked through the program and theoretically the app should work on webOS 1. 

https://github.com/mariotaku/moonlight-tv/releases/tag/v1.2.8

**Comment by FlyingT** [comment]
And it works (or at least starts) practically too! :) 
Uninstalled 1.2.7, installed 1.2.8 using the IPK and it instantly launched!

Added my System and will perform a few more tests before reporting back shortly.

**Comment by mariotaku** [comment]
Fantastic. Would you mind showing me some screenshots of the UI?

**Comment by FlyingT** [comment]
Seems like this TV doesnt support screenshots, so please excuse the shitty pictures: [https://imgur.com/a/Qquo225](https://imgur.com/a/Qquo225)

Game Icons arent loading and names only show up for manually added games, but thats not an issue. 
TV remote works flawless too! I dont know how to get [this menu](https://user-images.githubusercontent.com/830358/141690146-27ee2564-0cc8-43ef-a5b0-54b8487dda1e.png) to show, so wasnt able to make a picture of it.

**Comment by mariotaku** [comment]
Hi, thanks for the testing. So I think the image still doesn't work yet. 

For statistics menu, you can long press back button to have that.

So the stream works right? As well as sound?

**Comment by FlyingT** [comment]
Not having thumbnails is a minor issue, I just added Steam Big Picture and manage everything from there.
Statistics menu wont come up, pressing back on the TV remote is the same as if pressing Escape on the keyboard.

Stream and Sound works now, thank you very much! :)

**Comment by FlyingT** [comment]
Update: 
Played some Pico Park using two controllers and input lag/latency was non-noticable.
I'd say with 1.2.8 moonshine-tv is now fully working on older LG TVs

Again, thank you very much!

**Comment by FlyingT** [comment]
@mariotaku Hey man, thanks for the support on this :) 
Hope my small donation brightens up your day somewhat!
