### ISSUE TITLE
[BUG] Lack of titles and covers of games

### ISSUE THREAD

**Issue by DgDays** [mariotaku/moonlight-tv#128]
**Describe the bug**

Lack of titles and covers of games

**To Reproduce**

1) Open Moonlight on WebOS
2) We observe that there are no titles and covers of games

**Expected behavior**

The ability to somehow distinguish between games

**Basic information**

 - Moonlight version: 1.2.8
 - Model: 55UB850V-ZA
 - webOS version 1.4.0-2337

**Additional context**

Photo with an example of a bug: 
![1640885919919_20211230_223743](https://user-images.githubusercontent.com/55804305/147776026-cb831e22-9650-44c8-ae7f-22373c559682.jpg)

**Comment by mariotaku** [comment]
I don't have TV running webOS 1 so can't test it out, does [this snapshot](https://github.com/mariotaku/moonlight-tv/actions/runs/1638539615) work for you?

**Comment by DgDays** [comment]
This snapshot works for me, but there are no titles and covers yet ... The games are streaming, they are starting, but I do not understand which game I am launching before starting the stream

**Comment by mariotaku** [comment]
Thanks for the info. I will make a patch to disable cover for webOS 1 temporarily, and enable it back on when this issue got solved.

**Comment by mariotaku** [comment]
Please let me know if this works for you: https://github.com/mariotaku/moonlight-tv/actions/runs/1641243157

**Comment by DgDays** [comment]
Yes, it works) Thank you very much

**Comment by mariotaku** [comment]
I will reopen if you don't mind :)
This proves that some image can be loaded properly. So I'll try to make cover image work as well.

**Comment by DgDays** [comment]
Oh good) Let's wait for the news😄

**Comment by azsenca** [comment]
I have the same problem and found solution for my case.

All cover images need to be in RGB color mode. If it is in Indexed mode, it will not display on LG for some reason...

**Comment by exoss** [comment]
> I have the same problem and found solution for my case.
> 
> All cover images need to be in RGB color mode. If it is in Indexed mode, it will not display on LG for some reason...

this is exactly the answer to the question, i converted the Indexed to rgb with photoshop, after restarting sunsinie, the problem was solved thank u

**Comment by mariotaku** [comment]
Closing this issue for now as it might be fixed in recent releases.
