### ISSUE TITLE
Compatibility info

### ISSUE THREAD

**Issue by Nez-debug** [mariotaku/moonlight-tv#13]
MODEL: 43UH668V-ZA
VERSION: 3.3.4-4220

Tested at 1080p and 4K 60 FPS OK!

1440p is not working.
![16109943909157288758077558585672](https://user-images.githubusercontent.com/32144303/104951572-b5928680-59ba-11eb-8686-7227187e680c.jpg)

**Comment by mariotaku** [comment]
SOPS option can be turned off by uncheck settings "Optimize game settings for streaming", then it might work for you. I'll turn SOPS off automatically when non-standard resolution selected (anything other than 720p, 1080p, 4K).

**Comment by Nez-debug** [comment]
Confirmed 1440p 60 FPS also works with SOPS off.

**Comment by Nez-debug** [comment]
Should have mentioned, gamepad (with 8bitdo BT adapter) and magic wand remote all work with this TV :)
