### ISSUE TITLE
[BUG] Loading spinner artifact

### ISSUE THREAD

**Issue by Informatic** [mariotaku/moonlight-tv#130]
**Describe the bug**

Interesting minor artifacts in the bounding box of a loading spinner:

![capture](https://user-images.githubusercontent.com/1131102/147890389-38d68dd3-9659-40c1-be23-7177395f79d2.png)

These are static during runtime, but change on every launch. Probably some uninitialized (graphics?) memory.

**To Reproduce**

1. Launch moonlight-tv with already registered device that is offline
2. See corrupted spinner

**Expected behavior**

I expect spinner to not have artifacts :)

**Basic information**

 - Moonlight version: 1.2.8
 - Model: 43UJ6307-ZA
 - webOS version 3.8.0-61312

> To check version, go to Settings > Quick Settings > General > About this TV > webOS TV Version

**Additional context**

Add any other context about the problem here. For example error message on the screen, and settings in Moonlight

**Comment by Informatic** [comment]
Ah, there are similar artifacts on bitrate slider:
![capture2](https://user-images.githubusercontent.com/1131102/147890489-40a8ef2e-0c5a-47a3-b2f3-65f25b8edef4.png)
...and the same after changing actuve Settings and going back to "Basic":
![capture](https://user-images.githubusercontent.com/1131102/147890499-a51e7cdd-eb79-4def-8a8a-731fb15b4131.png)

**Comment by mariotaku** [comment]
This is very interesting. Those 2 widgets has one thing in common - they use draw mask in lvgl. I have changed its implementation in later version. How's v1.3.0?

**Comment by Informatic** [comment]
These look perfectly fine on 1.3.0. Thanks!
