### ISSUE TITLE
[BUG] NDL audio not working on webOS firmware 3.9

### ISSUE THREAD

**Issue by rebyul** [mariotaku/moonlight-tv#131]
**Describe the bug**

There is no audio played from the TV when the audio decoder is set to auto (NDL) or manually set to NDL.
Sound is available in ALSA and PulseAudio settings, but there is a noticeable delay in audio processing.

**To Reproduce**

1. Open game from Moonlight TV client
2. Notice no audio played through TV in NDL/auto audio decoder settings -or- delayed audio in ALSA/Pulseaudio config

**Expected behavior**

Audio should play. Note that in both TV speaker mode (2.1) or home theatre arc mode (not eARC)(5.1) there is no sound in both NDL and auto settings. In ALSA/Pulseaudio, 2.1 and 5.1 seems to work.

**Basic information**

 - Moonlight version: 1.2.8
 - Model: OLED65E7T
 - webOS version 6.0.00.25
 - webOS firmware version 3.9

> To check version, go to Settings > Quick Settings > General > About this TV > webOS TV Version

**Additional context**

- Game tested: Detroit become human
- Game hosted on Windows PC (6600k, 980ti). Output audio is set to the PC connected headphones (stereo sound) as I dont seem to get the option to set an NVIDIA game stream audio output.
- All picture modes tried (including game)

TBH my use case would be solved if the audio delay could be resolved in some way. I've tried playing around with the audio sync in the TV settings, but it doesn't seem to give me enough sync range.

If you need me to test/develop anything lemme know, would be glad to help!

**Comment by mariotaku** [comment]
NDL is not supported on webOS 3 and below. Does Netcast lagacy work for you?

**Comment by rebyul** [comment]
Afaik, Netcast legacy is one of the video decoder options right? Video works fine with almost no delay on NDL, it's the audio that's not working.

**Comment by mariotaku** [comment]
On some LG TVs with certain SoC, NDL audio does not function or crash. Currently there is no solution for that. But to make things at least work, a different audio backend was selected instead.

Related to #184.
