### ISSUE TITLE
[BUG] Mouse low polling rate and delay

### ISSUE THREAD

**Issue by Bruffandino** [mariotaku/moonlight-tv#132]
Mouse in general feels delayed, with a low refresh rate.

Using a wireless mouse with usb dongle connected to TV I measured 40Hz mouse polling rate, while other moonlight clients to the same host report 60Hz. Interestingly, with a bluetooth mouse paired to the TV I get a noticeble better performance of 50Hz polling rate. 

I addition I feel some input lag, higher than with other moonlight clients.

 - Moonlight version: v1.3.0-1
 - Model: LG OLED55A1
 - webOS version: 6.2.0-31

**Comment by mariotaku** [comment]
Mouse input rate is unavoidable, as webOS only reports pointer event in **shameful** 30ms interval. For gamepad it should be less than 2ms though.

**Comment by Bruffandino** [comment]
I see.. do you think is possible to send the mouse raw data directly to the host?

**Comment by mariotaku** [comment]
Permission model of webOS is still not clear speaking of USB access, but if an app can access such devices then it is possible. However I'm not really motivated to do that as most users are playing with gamepads.

**Comment by Bruffandino** [comment]
Too bad, I'll learn how to play civilization with a gamepad then :D. 
Jokes aside, thank you for the great work. I hope some more people will post here to motivate you.
