### ISSUE TITLE
[BUG] Failed to load apps

### ISSUE THREAD

**Issue by dant3** [mariotaku/moonlight-tv#133]
**Describe the bug**

I added my PC, and then I select it it asks for PIN. After entering PIN,moonlight displays error:

```
Failed to load apps
Press "Retry" button to reload. Try restart the computer if error persists.
```

**To Reproduce**

1. Select a PC in moonlight
2. Enter PIN
3. See error

Whenever I restart the moonlight, or reboot the PC, the steps and the outcome are the same

**Expected behavior**

I can see games list and select one

**Basic information**

 - Moonlight version: 1.3.0
 - Model: 75NANO926PB
 - webOS version 6.2.0-31 (kisscurl-kavir)

**Comment by dant3** [comment]
It works for me in moonlight on other Android-based TV

**Comment by mariotaku** [comment]
Might be related to memory bugs before. I'm closing this now as it's outdated. If you come back using moonlight-tv and got this issue again, fell free to reopen :)
