### ISSUE TITLE
Removing connections

### ISSUE THREAD

**Issue by jorants** [mariotaku/moonlight-tv#134]
**Is your feature request related to a problem? Please describe.**
I can not remove an existing connection in the WebOS interface

**Describe the solution you'd like**
Some way to remove a connection that is not needed anymore.

**Describe alternatives you've considered**
-

**Additional context**
Maybe I just missed this option? 
I had my PC setup but moved to another machine and now the old entry is still present in moonlight while it will never be online.

**Comment by mariotaku** [comment]
Removing reachable connection is not possible because unpair frame in GFE is broken. But I have added feature to remove an unreachable host. It will be available in next release. Simplify long press on a host and dialog will pop up.
