### ISSUE TITLE
Raspberry Pi undefined symbol: SDL_OpenURL (Raspbian buster)

### ISSUE THREAD

**Issue by galloway** [mariotaku/moonlight-tv#136]
Installing the release package for Raspbian buster will not work due to outdated SDL packages:

> $ moonlight-tv 
> moonlight-tv: symbol lookup error: moonlight-tv: undefined symbol: SDL_OpenURL

To confirm your Raspbian release:

> $ lsb_release -ds
> Debian GNU/Linux 10 (buster)

Checking dependencies of the package:

> $ sudo apt depends moonlight-tv
> moonlight-tv
>   Depends: libc6 (>= 2.28)
>   **Depends: libsdl2-2.0-0 (>= 2.0.4)**
>   Depends: libsdl2-image-2.0-0 (>= 2.0.1)
>   Depends: libopus0 (>= 1.1)
>   Depends: libcurl4 (>= 7.16.2)
>   Depends: libuuid1 (>= 2.16)
>   Depends: libexpat1 (>= 2.0.1)
>   Depends: libmbedcrypto3 (>= 2.13)
>   Depends: libmbedx509-0 (>= 2.0)
>   Depends: libconfig9 (>= 1.5)
>   Depends: libraspberrypi0
>   Recommends: libasound2 (>= 1.0.16)
>   Recommends: libpulse0 (>= 0.99.1)
>   Recommends: fonts-dejavu-core
>   Suggests: libavcodec58 (>= 7:4.0)
>     libavcodec-extra58
>   Suggests: libavutil56 (>= 7:4.0)
> 

SDL_OpenURL was made available in version 2.0.14, per the [SDL Wiki](https://wiki.libsdl.org/SDL_OpenURL), and Raspbian Oldstable (buster) has 2.0.9 as the latest version, per [repology.org](https://repology.org/project/sdl2/versions).

It looks like users will have to switch to Raspbian Bullseye in order to have a recent version of SDL. Hopefully filing this issue will save someone else some time in the future!

**Comment by mariotaku** [comment]
I have pushed a patch to solve this. If you find something else not compatible with buster, feel free to tell me. Also you could try build from source by invoking `./script/raspi/easy_build.sh`
