### ISSUE TITLE
Crash on Stream Start

### ISSUE THREAD

**Issue by Overlord43g** [mariotaku/moonlight-tv#138]
please check the performance on lg sm8200pla. after launching the game from the TV, throws out of the moonlight

**Comment by mariotaku** [comment]
Please open Settings - About page to check and provide more information to this issue:

 - Moonlight version
 - webOS version
 - Video decoder
 - Audio decoder

**Comment by Overlord43g** [comment]
> Пожалуйста, откройте Настройки - О странице, чтобы проверить и предоставить дополнительную информацию по этой проблеме:
> 
> * Лунная версия
> * версия вебОС
> * Видео декодер
> * Аудио декодер

Version 1.4.0


> Please open Settings - About page to check and provide more information to this issue:
> 
> * Moonlight version
> * webOS version
> * Video decoder
> * Audio decoder

Version 1.4.0
Webos 4.9.5
Video webos NDL
Audio decoder provided

**Comment by mariotaku** [comment]
Try different video decoder combination:
- SMP + NDL Audio
- SMP + ALSA
- NetCast Legacy
...etc

**Comment by Overlord43g** [comment]
> Try different video decoder combination:
> 
> * SMP + NDL Audio
> * SMP + ALSA
> * NetCast Legacy
>   ...etc

thanks, it helped! now how to connect the controller from the xbox one?

**Comment by mariotaku** [comment]
Which combination works for you?
And for xbox one controller, you can use third party wireless adapter: https://www.8bitdo.com/wireless-usb-adapter-2/

**Comment by Overlord43g** [comment]
Ĺ

> Какая комбинация работает для вас? А для контроллера xbox one вы можете использовать сторонний беспроводной адаптер: https://www.8bitdo.com/wireless-usb-adapter-2/



> Which combination works for you? And for xbox one controller, you can use third party wireless adapter: https://www.8bitdo.com/wireless-usb-adapter-2/



> Which combination works for you? And for xbox one controller, you can use third party wireless adapter: https://www.8bitdo.com/wireless-usb-adapter-2/

8bitdo will be determined by my webos 4.9.5? I got the combination
Video NDL + ALSA
netcast + ALSA works too

**Comment by mariotaku** [comment]
@Overlord43g I think so. My TV is running webOS 4.9.5 too. Thanks for your info.
