### ISSUE TITLE
[COMPAT] (old) Xbox One Controller and Switch Pro Controller are connected to 8bitdo wireless usb adapter in TV, but input doesn't work

### ISSUE THREAD

**Issue by sander1095** [mariotaku/moonlight-tv#139]
## Basic information

 - Device model: (  OLED66C9PLA ) 
 - Firmware version: ( 05.10.25 ) 
 - webOS version: ( 4.9.3 ) 
 - Moonlight version: ( 1.4.0) 
 - Is audio working: (    Yes ) 
 - Is video working: (   128060 ) 
 - Is input working: (   NO  ) 

## Description
I bought an [8BitDo wireless adapter](https://www.amazon.com/dp/B0786JC6VW) so I could use my xbox one controller and switch pro controller directly with my TV. I usually use the xbox one controller directly with bluetooth on my PC, so it is not the controller fault. Same for the Switch Pro Controller. It is also an old version of the controller, so there is no weird BLE stuff going on which I have read about recently.

When I connect the adapter, I do get a notification from the TV about an XPAD (or something) device being added. I can then also sync the controllers to the device, they vibrate, lights go on, etc.. But when I launch a game, none of the inputs do anything.

The funny thing is, I also have an old xbox 360 controller with a wired adapter. When I put this in the TV, it DOES work... sometimes. when it doesn't, it just keeps blinking a circle light on the controller. Retroarch does recognize it though! 

Should I connect my Xbox 360 with its usb adapter or with the 8bitdo one?

What do I need to do to be able to play with my Xbox One Controller/Switch Pro controller? 

[In the wiki](https://github.com/mariotaku/moonlight-tv/wiki/Gamepad-Setup#for-webos-50-and-below) I read some things about XInput mode, but I don't really see how I could do anything with that or what that means for me :)

Thanks for your hard work on this, it is super cool that this project exists!

**Comment by sander1095** [comment]
And another question: Is it possible to connect mouse/keyboard somehow?

**Comment by mariotaku** [comment]
Hi! Xbox 360 controller works out of the box, and 8bitdo adapter v1 is supposed to work OOTB, too. I'll test on my TV to see if I can reproduce the issue.
Mouse and keyboard should work if you plug them, few things to keep in mind is that no matter how good your mouse is, webOS only supports 30ms interval natively. Also for keyboard "Windows" key is occupied so you can't use it.

**Comment by sander1095** [comment]
Please take a look at my adapters I have. 
I believe I need that 8BitDo adapter for my xbox one controller and switch pro controller, and the Xbox 360 adapter for xbox 360 controller!

![IMG_20220129_132236.jpg](https://user-images.githubusercontent.com/7312681/151660933-26f5bf36-5498-4a37-aee9-310af928e988.jpg)

![IMG_20220129_132229.jpg](https://user-images.githubusercontent.com/7312681/151660932-f96d34ff-b3db-4e45-98ee-febe1ae5b0e1.jpg)

To prevent some misunderstandings, could you answer each of these questions?

- With an xbox 360 controller working out of the box, you mean without any other accessories? I believe I do need that wireless Xbox 360 controller adapter, how else would I connect it to my TV?
- I need to have the 8bitdo adapter for the xbox one controller and switch pro controller, I can't just use bluetooth like I can do for my PC?
- Is it OK to have both the 8BitDo adapter and Xbox 360 adapter in the TV?
- the wiki mentions something about xinput being most reliable. How can I know if my controller uses this? Would it be possible to configure this?

**Comment by mariotaku** [comment]
> With an xbox 360 controller working out of the box, you mean without any other accessories?

I mean with official adapter.

> I can't just use bluetooth like I can do for my PC?

It depends on your webOS version. webOS 5+ has ability to pair bluetooth gamepad directly

> Is it OK to have both the 8BitDo adapter and Xbox 360 adapter in the TV?

I think it should work, it will be recognized as 2 controllers.

> do the usb ports matter?

Which one was plugged first matters I think.

> How can I know if my controller uses this? Would it be possible to configure this?

Xbox 360 adapter/controller comes with xinput, 8bitdo has xinput mode. Please check their manual.

> Do I need to turn my controller on before I launch moonlight?

It supports hotplug, so I think it's fine. In game is not defined though.

> Perhaps it'd be good to see a picture of your setup?

I have the same unit of 8bitdo adapter as yours. It works without any issue.

**Comment by sander1095** [comment]
> I have the same unit of 8bitdo adapter as yours. It works without any issue.

Alright, do you have any troubleshooting tips? What usb port do you have it in? How do you connect a controller? 

It clearly doesn't work for me.. I could update my  firmware because an update is available, but I don't trust these updates because I am afraid it will just break more stuff. :) 

I do the following:

- Turn on TV
- Plug in 8bitdo adapter in any port
- see notification about XPAD device being connected
- press the button on the back of the 8bitdo adapter, it starts blinking rapidly
- turn on xbox one controller
- press pair button on controller quickly, it starts blinking rapidly
- after a few seconds, it stops blinking vibrates and stays 1 color; suggesting that it is now connected
- launch moonlight on TV
- launch a game (god of war,rocket league)
- pressing any buttons doesn't do anything.

I do so see some notifications from steam about some gamepad configurations being loaded, not sure if that has anything to do with it.

Could you repeat these steps and get things to work? What game do you test it on? Do you get notifications from steam about a gamepad being connected? And perhaps to be what are your gamepad settings in steam big picture mode?

If I could give you any logs with more details, let me know! Also, let me know how I can give you these logs!

Thanks!

**Comment by sander1095** [comment]
To add to this, my xbox 360 controller works (sometimes, like I said) but the circle LED keeps blinking during gameplay. This is rather annoying! :) I could create a seperate issue for this if you would prefer that!

**Comment by sander1095** [comment]
Hey @mariotaku :) Could you tell me when you could update me on this issue? It's not urgent; I would just like to know an estimate :D.

**Comment by mariotaku** [comment]
@sander1095 Sorry I'm working on other stuff so I don't have much to update yet.

* #140 will be added in next release, and the time is not decided yet.
* Your procedure of using adapter with 8bitdo is identical to mine. I can't tell the reason for this issue, maybe it's nice to add one gamepad test screen.

I think once I get back from https://github.com/mariotaku/steamlink.py I can finish tasks mentioned above. But no estimate.

**Comment by alvaromunoz** [comment]
> ![IMG_20220129_132229.jpg](https://user-images.githubusercontent.com/7312681/151660932-f96d34ff-b3db-4e45-98ee-febe1ae5b0e1.jpg)

That's the V1 adapter, which is no longer compatible with XBox bluetooth controllers since September 2021. To connect your BT Xbox controllers, you would need [the V2 adapter](https://www.8bitdo.com/wireless-usb-adapter-2/).

But you can still use it to connect Switch pro controller. There's a [manual in the 8bitdo website that tells you how to sync and change modes](https://support.8bitdo.com/Manual/USB_Adapter/switchpro_windows.html). Once it's paired and connected to the TV, hold the minus button and up on the dpad, and you should get a popup saying that a device has been disconnected and another connected. If that doesn't work, try other combination from the manual (for example, in V2 the MAC combo works).

Also, I understand that you can only have 1 adapter connected. Either the xbox 360 wireless adapter, or the 8bitdo adapter.

**Comment by sander1095** [comment]
I will check it out. Thanks! 

My xbox one controller is at least 4+ years old, and I never consciously updated it. It has always been attached to my PC. I am not sure if I have this new firmware. Perhaps those mode changing tricks will also work on my xbox one controller.. We shall see.

**Comment by sander1095** [comment]
Messing around with SELECT + UP on the Dpad and SELECT + LEFT on the dpad changed input modes, eventually working correctly. This means that the 8bitdo wireless adapter v1 is indeed supported, no need for v2 when using xbox one controller.

@mariotaku  This might be worth mentioning on the wiki :)
