### ISSUE TITLE
Dynamically enter/leave HDR mode

### ISSUE THREAD

**Issue by cgutman** [mariotaku/moonlight-tv#141]
I've added an HDR mode callback in https://github.com/moonlight-stream/moonlight-common-c/commit/abc7acb5e4c219ebcb51031517b01bd266005e3a that lets you know when the host PC display has been switched to HDR mode.

It looks like it's just a matter of calling `NDL_DirectVideoSetHDRInfo()` in that new HDR mode callback rather than unconditionally when starting the stream. This will make sure colors are correct if the user/app disables HDR while streaming.

**Comment by mariotaku** [comment]
Should be working now.
