### ISSUE TITLE
[COMPAT] 8BitDo Adapter 2 only working in PSC & MD modes.

### ISSUE THREAD

**Issue by ian-moody** [mariotaku/moonlight-tv#148]
- Device model: 55UK6090PUA
 - Firmware version:  05.45.04
 - webOS version: 4.4.1
 - Moonlight version: 1.4.0
 - Is audio working: Yes
 - Is video working: Yes
 - Is input working: No

Out of the 6 manual pairing modes, I'm able to get some response from my controller in PSC mode (VIEW + DOWN) and in MD mode (VIEW + UP + LEFT). Both these which have unacceptable mappings for my xbox one controller, analog sticks not working, triggers acting as digital buttons, etc. In these two modes, I can partially navigate though moonlight tv menus and see it recognized in gamepad-tester.com streamed from my host machine. My tv is displaying correct looking HID and XPAD connection messages for all the modes. Also, the adapter was updated to the latest (1.01) firmware.

**Comment by mariotaku** [comment]
Somehow the adapter is not working properly with Xinput mode on Linux. This issue is the same to #145 .
