### ISSUE TITLE
Add an option to disable the virtual mouse shortcut (LB + RS)

### ISSUE THREAD

**Issue by Martijnpold** [mariotaku/moonlight-tv#149]
**Is your feature request related to a problem? Please describe.**
Some games I've been playing (mostly Dark Souls and Elden Ring) use the RS for certain inputs. In this case, it's used for aim-locking. This has a pretty major side-effect where, whenever I happen to press both buttons at the same time (aim-lock + attack), virtual mouse will enable itself and the game controls very differently and is near unplayable until I press the button combination again.

It's led to some pretty frustrating gameplay since it took me a long time to figure out that this shortcut exists. I haven't found anyone else that references this problem online so far. I've only found out that this was the cause by pure coincidence.

**Describe the solution you'd like**
I would like a toggle setting (maybe still just enabled by default) along the lines of "Enable virtual mouse shortcut (LB + RS)". Since I don't really need to be able to toggle virtual mouse "on the fly" anyway, the menu shortcut works fine in my opinion.

**Describe alternatives you've considered**
I don't really know if there are alternatives. I could rebind RS in those specific games, but most buttons are already in use, so it wouldn't be a great fix.

**Comment by sander1095** [comment]
Copy of #140?

**Comment by Martijnpold** [comment]
Oh yeah true. I just missed it I guess. I'm looking into possibly fixing this myself and making a PR, just been a long time since I've done anything C related so getting the project to run is not easy :)

**Comment by mariotaku** [comment]
The option has been added in v1.4.1!
