### ISSUE TITLE
Gamepad not detected

### ISSUE THREAD

**Issue by uraid** [mariotaku/moonlight-tv#15]
Tested with Xbox One X and Xbox One controllers - using USB cable.
LG 55SM9000 Webos 4.5 shows 'Unknown device connected' and Moonlight SDL doesn't get their input (when trying out a game).
Tried also with TP-Link UB400 Bluetooth dongle.

Am I not connecting the controllers correctly? Thank you!

**Comment by mariotaku** [comment]
Good question! I should add this to the wiki. Xbox One controllers is not a general gamepad device - which means it can't run without a proper driver. Also the wireless adapter by Microsoft is also not supported.

There's an easy way to use almost any kind of game controller, which is using some dongle like [8BitDo Wireless Adapter](https://www.8bitdo.com/wireless-usb-adapter/).

**Comment by uraid** [comment]
Thank you for the quick answer :)
