### ISSUE TITLE
[BUG] Raspberry pi4 (without desktop) Unable to load decoder module: libbcm_host.so.0

### ISSUE THREAD

**Issue by jgabriel98** [mariotaku/moonlight-tv#150]
**Describe the bug**

It seems that the `.deb` package have some missing dependencies (one that includes `libbcm_host.so.0` lib).

I've installed the `.deb` package on a raspberry pi4 (with its desktop ripped off), and after running `moonlight-tv`:
 - the program launches, but don't connect to the server (moonlight-embbeded and -qt works)
 - it outputs the following in terminal:
   ```
   000000.000 [APP][INFO] Start Moonlight. Version 1.4.0
   000001.063 [Module][WARN] Unable to load decoder module: libbcm_host.so.0: não é possível abrir arquivo 
   compartilhado: Arquivo ou diretório inexistente
   000001.495 [Input][INFO] Load game controller mapping from /root/.local/share/com.limelight/moonlight- 
   tv/sdl_gamecontrollerdb.txt
   000001.523 [Input][INFO] Input manager init, 268 game controller mappings loaded
   error: XDG_RUNTIME_DIR not set in the environment.
   000001.669 [APP][INFO] UI locale: pt_BR.UTF-8 (Português do Brasil)
   000001.691 [UI][INFO] Display size changed to 0 x 0
   000001.692 [APP][INFO] Decoder module: Raspberry Pi (auto requested)
   000001.692 [APP][INFO] Audio module: ALSA (auto requested)
   000001.817 [Input][INFO] Controller #0 (Microsoft X-Box One pad) connected, sdl_id: 0, GUID: 060000005e040000120b000009050000
   [Warn]  (1.817, +1817)   indev_pointer_proc: X is 0 which is greater than hor. res      (in lv_indev.cc line #347)
   000001.817 [Discovery][INFO] Start mDNS discovery
   [Warn]  (1.819, +2)      indev_pointer_proc: X is 0 which is greater than hor. res      (in lv_indev.c line #347)
   [Warn]  (1.820, +1)      indev_pointer_proc: X is 0 which is greater than hor. res      (in lv_indev.c line #347)
   [Warn]  (1.822, +2)      indev_pointer_proc: X is 0 which is greater than hor. res      (in lv_indev.c line #347)
   .
   .
   .
   same last logs forever
   ```

the 2º line translated to english would be: `000001.063 [Module][WARN] Unable to load decoder module: libbcm_host.so.0: cannot open shared object file: No such file or directory `

**To Reproduce**

1. install latest raspbian buster 32-bit OS, version **with desktop**
2. remove desktop with `sudo apt purge raspberrypi-ui-mods xserver* lightdm* raspberrypi-ui-mods vlc* lxde* chromium* desktop* gnome* gstreamer* gtk* hicolor-icon-theme* lx* mesa*`
3. install the moonlight-tv `.deb` package (v1.4.0)
4. run `moonlight-tv``on terminal

**Expected behavior**

To application connect to

**Basic information**

 - Moonlight Tv version: 1.4.0
 - Model: RaspberryPi 4 4gb
 - OS: raspbian Buster 32 bit

**Comment by mariotaku** [comment]
If you are running buster, please check:

1. If `libraspberrypi0` is installed
2. If `/opt/vc/lib/libbcm_host.so` exists
3. If `/opt/vc/lib` is in `LD_LIBRARY_PATH`

Also on buster you should better run Moonlight-TV under X.

**Comment by jgabriel98** [comment]
1. It is: 
 ```bash
pi@raspberrypi:~ $ sudo apt-cache policy libraspberrypi0
libraspberrypi0:
  Instalado: 1:2+git20220324~090146+c4fd1b8-1
  Candidato: 1:2+git20220324~090146+c4fd1b8-1
  Tabela de versão:
 *** 1:2+git20220324~090146+c4fd1b8-1 500
        500 http://archive.raspberrypi.org/debian bullseye/main armhf Packages
        100 /var/lib/dpkg/status
```
 2. It does not:
 ```bash
pi@raspberrypi:~ $ ls /opt/vc/lib/libbcm_host.so
ls: não foi possível acessar '/opt/vc/lib/libbcm_host.so': Arquivo ou diretório inexistente
```
 3. it isn't:
 ```bash
pi@raspberrypi:~ $ echo $LD_LIBRARY_PATH

pi@raspberrypi:~ $
  ```

**Comment by jgabriel98** [comment]
note: i've just updated this issue to pass the info.

Personaly i settled with moonlight-qt.
But i'm willing to help if you wish to investigate any futher

**Comment by mariotaku** [comment]
I think the reason has been found. Thanks for providing the info, I completely missed that `libbcm_host.so` is in `libraspberypi-dev` only.

**Comment by mariotaku** [comment]
Fixed in https://github.com/mariotaku/moonlight-tv/commit/b336e80933c76c8644ad10ce7792572e75b6fd46.
