### ISSUE TITLE
Half network framerate with new 1.4.1

### ISSUE THREAD

**Issue by kekkokk** [mariotaku/moonlight-tv#153]
Hi,
I noticed that with version 1.4.1 the network framerate is displayed as half of the host framerate.

Seems a regression since 1.4.0.

However can't really tell if it's only a UI or functional bug

**Comment by mariotaku** [comment]
I think this is a UI issue. The framerate presented was 1/2 of actual framerate.

**Comment by mariotaku** [comment]
It seems that GFE is now sending 2 frames in one packets. So this value is not useful anymore.

**Comment by kekkokk** [comment]
yeah but 1.4.0 is representing it right, even with the newest GFE, is that normal?

**Comment by mariotaku** [comment]
Sorry, this turns out was a mistake by me. It will be fixed in next release.

**Comment by kekkokk** [comment]
this was only graphical bug or also a performance bug? just to know

**Comment by mariotaku** [comment]
It's a graphical bug. Real performance was not affected.
