### ISSUE TITLE
[BUG] Cannot move mouse in remote desktop

### ISSUE THREAD

**Issue by D3v01dZA** [mariotaku/moonlight-tv#154]
**Describe the bug**

When I use remote desktop [wiki](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-moonlight-to-stream-your-entire-desktop) I cannot move the mouse on the host PC. Whenever I move the mouse all that happens is that the mouse in WebOS moves over the screen and the host PC's mouse is not moved. 

**To Reproduce**

1. Setup and enter remote desktop
2. Try to move mouse

**Expected behavior**

The mouse on the remote desktop moves

**Basic information**

 - Moonlight version: 1.4.1
 - Model: OLED65B8PUA
 - webOS version: 4.4.1

**Comment by mariotaku** [comment]
Hello. Did you try to connect with other clients like your phone? This can help to find out whether this is a host issue.

**Comment by D3v01dZA** [comment]
I can confirm it is working from my laptop to my desktop, in fact I typed this from the laptop

**Comment by mariotaku** [comment]
Does DPAD (keyboard arrow keys), or gamepad work?

**Comment by D3v01dZA** [comment]
I can move the mouse using the right stick by pressing the button combo required. It now looks like it usually works, sometimes when I move the mouse I get the big LG red pointer moving, and sometimes it moves the mouse. Honestly I don't really use the remote desktop, I was just playing with it to see how it all works and assess its utility.

**Comment by mariotaku** [comment]
Since v1.5.1, a new feature to use raw mouse input has been added. This issue then can be seen as solved.
