### ISSUE TITLE
[COMPAT] Fails to start on LG C2 42in (webOS 7 aka 22)

### ISSUE THREAD

**Issue by kp73** [mariotaku/moonlight-tv#156]
## Basic information
 - Device model:  LG OLED42C24LA
 - Firmware version: 03.10.75
 - webOS version: 7.1.0-51 (mullet-maria)
 - Moonlight version: unable to check settings but latest from dev-manager-desktop as of 2022-05-03
 - Is audio working:  No
 - Is video working: No
 - Is input working: No

## Description
Moonlight fails to start.  Installed via dev-manager-desktop (other apps install OK eg. homebrew).  Select Moonlinght app, tries to start but screen blanks then returns to webOS homepage or live TV.

**Comment by mariotaku** [comment]
Does it crash on older versions?

**Comment by kp73** [comment]
Yes, same thing.  Tried 1.4.1 and 1.3.1, neither worked :(

**Comment by ILOmega** [comment]
Same Problem on my LG OLED77C26LD.
When Selecting Moonlinght app, tries to start but screen blanks then returns to webOS

**Comment by olidennis** [comment]
Same issue here, on my LG OLED77C26LD. By starting the app, installed with webos-dev-manager, the screen flashes for a moment and then the developer mode opens.

**Comment by mariotaku** [comment]
I see. It looks like moonlight has issue running on webOS 7. I'll extract the firmware and investigate.

**Comment by mariotaku** [comment]
Anyone rooted your TV, or can access its SSH via devmode? I'd like to extract libraries inside Following dirs, and take a look:

* `/lib`
* `/usr/lib`
* Directories listed in `/etc/ld.so.conf`

If you can pull files above, could you share it to me?

**Comment by olidennis** [comment]
I don't have root, but I could get them via sftp.
/etc/ld.so.conf does not exist
I uploaded /lib /usr/lib and /etc to dropbox at this link https://www.dropbox.com/s/zhuq7nbn1ftllce/lgc2.zip?dl=0
Please tell me if you prefer to receive the files in a different way, apparently I cannot send them directly here.

**Comment by mariotaku** [comment]
@olidennis Thank you! Dropbox is a nice way to me. I'll dump all the symbols and try to pinpoint the issue.

**Comment by mariotaku** [comment]
Moonlight v1.4.4 is out, it should work on webOS 7, would you like to give it a shot?

**Comment by ILOmega** [comment]
It works. :)

Thanks for the good work.

I want to try it out better later today.

Is it best via WIFI or Ethernet.? I noticed a little lag in the 5 min I tested it on ethernet and 1080p

**Comment by mariotaku** [comment]
@ILOmega Thanks for testing :)
It should be working on both, however some reports that using gigabit ethernet port will have some lag.

**Comment by olidennis** [comment]
It works well for me, both on ethernet and wifi, and I cannot notice any latency. On wifi sometimes it stops working for few seconds.
Question: is there a reason why the bitrate is limited to 65Mbps? I noticed it works flawlessly while streaming at 4k 120fps via ethernet, but I can see some compression artefacts.

**Comment by kp73** [comment]
1.4.4 works great.  Thanks so much.

**Comment by mariotaku** [comment]
@olidennis 65Mbps is the maximum supported bitrate documented by LG.
