### ISSUE TITLE
"Network error happened, failed to start streaming"

### ISSUE THREAD

**Issue by leonardov** [mariotaku/moonlight-tv#158]
Hi! I am having some issues running a gamestream.
Client: LGWebOS (Ethernet)
Moonlight version 1.4.4
Video: webOS NDL
Audio: Decoder provided

webOS version: 6.3.0

TV model: 50NANO75

Host: GFE (Wifi 5 (802.11ac) 5Ghz

The game runs on host, but the stream is never created for the client. error is "Network error happened, failed to start streaming"

from looking at the log files, I can see two relevant errors
<ServerMiscUtils>   Is GPU in local Game Streaming Whitelist=0
<ServerMiscUtils>  GPU does not support local streaming

I tried reinstalling GFE on Host and Moonlight on client.

I am able to run Moonlight and gamestream on iOS Client with no issues (WiFi), so it really seems to be a network issue.

I verified that both the client and host are on the same subnet mask.

I verified that host computer is able to PING client IP

How can I ensure they are able to make a connection? What should I look into?

I was looking for logfiles on TV since I have root access, but dont know where to look.

here is the nvidia log[
[NvStreamerCurrent.log](https://github.com/mariotaku/moonlight-tv/files/8854288/NvStreamerCurrent.log)

 Many thanks

**Comment by leonardov** [comment]
I can confirm that the Client (webOS Moonlight) was able to connect to the Host via Wifi with no issues. running games and desktop.

It would be optimal to have ethernet anyways , so any feedback is appreciated.

**Comment by mariotaku** [comment]
Hi, have you tried to connect your TV via Wi-Fi?

**Comment by leonardov** [comment]
Yes, the stream was able to start when both TV and PC are on wifi, but results in RTT in client being too high. This confirms being an network issue, so I'll close the issue
