### ISSUE TITLE
OLED65B6V-Z

### ISSUE THREAD

**Issue by TheMasterDingo** [mariotaku/moonlight-tv#16]
# Basic information

 - Device Model: OLED65B6V-Z
 - System Version: 3.3.5-4323 (dreadlocks-dharug)
 - Is Audio Working: Yes
 - Is Video Working: Perfectly 1080@60, too much latency over that
 - Is Input Working: MagicRemote works, DS4v2 works

@1080p60 works with any bitrate , but any resolution over that the latency is very high

**Comment by mariotaku** [comment]
Thanks for this info. This has been added to wiki page. If you have more findings about this model, feel free to comment here.
