### ISSUE TITLE
[BUG] Crashed on LG UM7000PLA

### ISSUE THREAD

**Issue by SSchott** [mariotaku/moonlight-tv#160]
## Basic information

 - Device model: (UM7000PLA)
 - Firmware version: (05.20.35)
 - webOS version: (4.9.5)
 - Moonlight version: (1.4.7) 
 - Is audio working: (No) 
 - Is video working: (No) 
 - Is input working: (No) 

## Description
I have tested the project before without major issues, I wanted to play a game in the TV again, so I reinstalled the latest version using the webOS device manager. The app gets installed just fine, but I noticed that whenever I press to the right before connecting to a PC (when the animation that reduces the menu size happens), the app gets stuck, and has to be closed and reopened.

After managing to connect (I had to reinstall GeForce Experience for whatever reason), if I try to open any app, Moonlight just closes without any further warning. Checked with the WebOS device manager terminal, and didn´t find any log whatsoever.

**Comment by SSchott** [comment]
I took the time to test older version. I can confirm that 1.4.4 works fine.

**Comment by mariotaku** [comment]
Thanks for the info. I'll release a new version of device manager so logs can be viewed.

**Comment by mariotaku** [comment]
Hi, This crash was fixed on v1.4.9 and above. So I'm closing this now.
