### ISSUE TITLE
[BUG] External USB Ethernet Adapter 

### ISSUE THREAD

**Issue by Streid** [mariotaku/moonlight-tv#161]
**Describe the bug**

When connected to the network through an external 1gbps usb adapter, the stream does not start (black screan). Other application (Youtube, Netflix, etc) work correctly. If you connect the TV via a onboard ethernet (or WiFi) adapter, the stream works without problems.

**To Reproduce**

1. Start APP
2. Select game & start stream (the app sees the server but can't start streaming)
3. Have connection error (black screan and error "Network error happened")

**Expected behavior**

Stream has started

**Basic information**

 - Moonlight version: 1.4.7
 - Model: LG OLED55C1RLA
 - webOS version: 6.3.1
 - firmware: 03.33.11
 - NDL decoder
 - 4k
 - 120fps

**Comment by Streid** [comment]
[NvStreamerCurrent.log](https://github.com/mariotaku/moonlight-tv/files/9065868/NvStreamerCurrent.log)

**Comment by Nazgile94** [comment]
+1 for that, same issue for me

LG OLED C1 65 -- with internal Ethernet - all works, with USB Ethernet - blackscreen/error

**Comment by mariotaku** [comment]
Closing this issue and future progress will be tracked in #95 .
