### ISSUE TITLE
[BUG] Black screen with 4K

### ISSUE THREAD

**Issue by maqjav** [mariotaku/moonlight-tv#163]
**Describe the bug**

If I switch the resolution in Moonlight to 4K, then I get black screen with audio

**To Reproduce**

1. Go to Settings -> Set 3840 × 2160
2. Cast something, black screen + audio

**Expected behavior**

It should show the image too.

**Basic information**

 - Moonlight version: 1.4.7
 - Model: UK6200PLA
 - webOS version 4.4.0
 - Firmware version: 05.40.26

**Additional context**

If I switch to 1080p then it works, it fails only with 4K. With 2K it also sends image, however it's messy and with green lines.
I tried with the 4 video codecs, it doesn't work with any of them.
I'm pretty sure last weekend it worked, however today when I turned on the TV Moonlight had disappear from my app menu and I had to install it again, then switching to 4K wasn't working.

**Comment by CloneIX** [comment]
Same problem here with LG C1.

Basic information

    Moonlight version: 1.4.7
    Model: OLED65C17LB
    webOS version 6.3.1
    Firmware version: 03.33.11

I also do not get any picture in 1080p only sound.

**Comment by mariotaku** [comment]
@maqjav @CloneIX Could you try old version e.g. (v1.4.4) to see if it works?

**Comment by maqjav** [comment]
I will give it a shot and let you know.

**Comment by maqjav** [comment]
Hello again.
It works with 1.4.4, I guess I will stick to it.
Thanks.

**Comment by mariotaku** [comment]
Interesting. Could you please test v1.4.5 & v1.4.6 if possible? So I can see which version broke 4K video.

**Comment by oeduand** [comment]
I have an LG 49uk6310pse, in version 1.48
I've already tested all combinations of Codec and resolutions, it only works 1080p
I will test version 1.44/ 1.45/ 1.46 and leave you feedback

**Comment by mariotaku** [comment]
@oeduand Thank you!

**Comment by oeduand** [comment]
I still have the problem, I tried to install version 1.48, then 1.44/ and all subsequent ones and I still have a lack of image in 4K, and 1440p with green...
unfortunately I couldn't help

**Comment by oeduand** [comment]
however I tried 4K on another device, and I think it's a slowness in the image decompressor

**Comment by mariotaku** [comment]
> however I tried 4K on another device, and I think it's a slowness in the image decompressor

Thanks for the info. Maybe I can find the place where maximum resolution is stored.

**Comment by mariotaku** [comment]
Since the "black screen" issue, which is a memory access bug was fixed, I'll close this. Please create new issue if you find something else.
