### ISSUE TITLE
Force a higher refresh rate

### ISSUE THREAD

**Issue by joaopedrosgs** [mariotaku/moonlight-tv#165]
**Is your feature request related to a problem? Please describe.**
Kind of. My monitor goes up to 144hz, but my tv only supports 60hz. The problem I'm having is that sometimes the TV stream stutters, dipping to 58 fps. 

**Describe the solution you'd like**
A way to force a higher refresh rate even if the tv doesn't support it. I'm not asking to make the tv magically work with the refresh rate, I know that's impossible. 
This feature is present in the moonlight android application.

**Describe alternatives you've considered**
I don't think that there are any alternatives for the refresh rate. For the stuttering, I tried almost everything, and to be honest, it's very subtle.

**Comment by mariotaku** [comment]
58~61 FPS can be considered normal. For the stutter issue, it might be something else. How do you connect the TV to the PC?

**Comment by joaopedrosgs** [comment]
PC wired to the router (Archer C80) and TV connected to the same router using 5ghz wireless. Just one wall between the TV and the router

**Comment by mariotaku** [comment]
This might work trying: https://github.com/mariotaku/moonlight-tv/wiki/Troubleshooting#high-frame-rate-drops-on-wlan
By switching to a non-DFS channel, you'll get smoother stream.

**Comment by joaopedrosgs** [comment]
Not sure if using a non-DFS channel did something, but the issue seems less apparent. Thanks, @mariotaku (for both the solution and the amazing software!).
