### ISSUE TITLE
[BUG] LG C1 pixelated image when using 4k with HDR.

### ISSUE THREAD

**Issue by Efabbrini** [mariotaku/moonlight-tv#166]
**Describe the bug**

Stream is pixelated when client is set to 4k with HDR

**To Reproduce**

Set resolution in Moonlight client to 4k with HDR

**Expected behavior**

Expect 4k to be the most clear option on client.

**Basic information**

 - Moonlight version: [e.g. 1.4.8
 - Model: OLED55C1PUB
 - webOS version 6.3.1

**Additional context**

Setting Moonlight resolution to 4k with HDR on makes it significantly more blurry than 1440p with HDR.

Issue seems to be very clear around the edges of shapes. My only guess is that the monitor attached to my PC is 1440P without HDR, which is causing issues. 

Setting Moonlight to 4k without HDR or 1440p with HDR makes the image much more clear.

Desktop:
12700k\RTX2080, 1440p monitor WITHOUT HDR

I've attached a photo of the windows taskbar in 4k\1440, both with HDR on.

4K
![4k](https://user-images.githubusercontent.com/60904187/181121226-e239a7be-3feb-466c-9217-b5c39c513c0d.jpg)

1440p
![1440](https://user-images.githubusercontent.com/60904187/181121236-d78f807b-ce22-4e6c-a3f1-ebbacd1eb0f6.jpg)

**Comment by mariotaku** [comment]
Moonlight on webOS only passes video stream directly into TV. I'm afraid there's nothing I can do on the client side.

**Comment by Efabbrini** [comment]
No worries then, I'm fine with 1440p or 4k without HDR for now. Thanks for the help!

**Comment by cgutman** [comment]
I have seen this in cases where the host desktop or application rendering resolution doesn't match the stream resolution. I'm not sure why it only impacts HDR, but you could try playing with that and see if it goes away.

**Comment by Efabbrini** [comment]
FYI - This issue does not carry over into games so I was able to ignore it.
