### ISSUE TITLE
[BUG] Crash After v1.4.4

### ISSUE THREAD

**Issue by mbahmodin** [mariotaku/moonlight-tv#167]
## Basic information

 - Device model: 55UK6540PTD
 - Firmware version: 05.40.26
 - webOS version: 4.4.0
 - Moonlight version: 1.4.8
 - Is the audio working: Not tested yet
 - Is the video working: 
    - No Video; what have I tested:
        - resolution in Client: 720p30fps, 720p60fps, 1080p30fps, 1080p60fps
        - resolution in host: 720p60hz, 1080p144hz
        - video codec and audio backend: Automatic/Automatic, and every combination of video codec and audio codec, and I restarted the application on every change.
 - Is input working: Not tested yet
 - TV has been rooted using rootmy.tv  and installed using webOS dev manager
 - Crash Log: [Log File](https://gist.github.com/mbahmodin/b3c67b4b3bd0e8c18853cfccadcf5fdb)
 
## Description
- Install the app using any method
- run it
- pair it to the Host PC
- Select `mstsc.exe` or any other applications
- moonlight-tv crash

I already try [this method](https://github.com/mariotaku/moonlight-tv/wiki/Troubleshooting#crashes) but  the last command outputed `-sh: /media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight: not found`

**Comment by mbahmodin** [comment]
Found the fix, downgrade it to [1.4.4](https://github.com/mariotaku/moonlight-tv/releases/tag/v1.4.4)
audio, video, Xinput is working fine with default setting

**Comment by mariotaku** [comment]
Hello, could you manually install v1.4.5 and v1.4.6 to see if they work?

**Comment by mariotaku** [comment]
Hi, sorry to bother you again. Could you try snapshot version in this list (latest one should be fine) when you're available? https://github.com/mariotaku/moonlight-tv/actions

**Comment by mbahmodin** [comment]
- v1.4.8-00C16438 [Crash](https://gist.github.com/mbahmodin/e06e7bcb18001b50ad448f92b1a0b767)

I did it 3 times just to make sure the first one is not a fluke

**Comment by mbahmodin** [comment]
- v1.4.8-00C16438 [Crash](https://gist.github.com/mbahmodin/e06e7bcb18001b50ad448f92b1a0b767)

I did it 3 times just to make sure the first one is not a fluke

**Comment by mariotaku** [comment]
Could you try recent snapshots? https://github.com/mariotaku/moonlight-tv/actions/runs/2822644181
I'm fixing bad memory access.

**Comment by mbahmodin** [comment]
IT WORKS :tada:
It is running perfectly in 720p 60fps and 1080p 60fps mode, and everything works just like how v1.4.4 does.

Although the 8bitdo adapter 2 XInput mode still doesn't work, I think it is the 8bitdo fault, not the moonlight, because I tried it on my Linux machine running pop os, and it's also not working.

In 1080p 60fps mode, everything works fine, but when I look at the performance graph, it is still using 1280*720. I don't know if this is intentional or not.

In 1440p 60fps mode, it produces some glitch, but the audio and controller input is working fine. ![glitch](https://user-images.githubusercontent.com/85983303/184063225-693b51b9-e250-48fd-9a34-0347c7bd5d97.jpg)

In 4K 60fps mode, it only outputs the audio, no video whatsoever, and in the performance graph, it's still in 720p. Controller input is also working.

**Comment by mariotaku** [comment]
Glad to hear it works! May I have the model of your GPU please?

**Comment by mbahmodin** [comment]
sure,
[RTX 3070 TI](https://www.evga.com/products/product.aspx?pn=08G-P5-3785-KL)

**Comment by mariotaku** [comment]
This is interesting. Did you try SMP decoder for 4K stream?

**Comment by mbahmodin** [comment]
I found out that you need to restart the app to change the resolution and the framerate.
SMP didn't output any video. I also get the same output with 30fps in both SMP and NDL.

-720p 60fps SMP
![20220811_184811](https://user-images.githubusercontent.com/85983303/184126916-6c117252-a822-4d9d-8072-48a05024109f.jpg)
-1080p 60fps SMP
![20220811_175416](https://user-images.githubusercontent.com/85983303/184126968-1524189e-2c9e-4b2d-bc38-7a51271f3c40.jpg)
-1440p 60fps SMP
![20220811_175159](https://user-images.githubusercontent.com/85983303/184127101-84ba4a6d-2511-406c-ad66-115f15759a7e.jpg)
-4K 60fps SMP
![20220811_174827](https://user-images.githubusercontent.com/85983303/184127232-33148984-fdf0-4dc9-ac75-67bb6966e972.jpg)


-1440p 60fps NDL
![20220811_180147](https://user-images.githubusercontent.com/85983303/184127524-d28363b4-defc-47cb-8212-742760476976.jpg)
-4k 60fps NDL
![20220811_180518](https://user-images.githubusercontent.com/85983303/184127984-29d58b1b-e240-4c7a-a2fe-57e0a02829f1.jpg)

**Comment by mariotaku** [comment]
I think it may not be able to stream 4K for your TV. It has 4K playback but not for low latency streaming. I'll close this issue as the crashing issue was fixed in v1.4.9+. Feel free to open new issues for other issues.
