### ISSUE TITLE
[FEATURE] Option to clear app cache data

### ISSUE THREAD

**Issue by RemcoTaal** [mariotaku/moonlight-tv#168]
**Is your feature request related to a problem? Please describe.**
The app used to work great, after I changed the resolution + fps in the settings, issue's started to appear. After reinstalling the app it was stable again.

**Describe the solution you'd like**
It would be great to have an option to clear the cache data of the app. My suggestion is to place it in the settings->about OR help section.

**Describe alternatives you've considered**
Tried to find a option to clear app data in the app store or homebrew store. There is no option other than reinstalling the app.

**Comment by mariotaku** [comment]
This app doesn't store anything besides settings and cover photos. It could be related to something else. Could you share more about the issues you got?
