### ISSUE TITLE
[BUG] Game covers get corrupted when navigating the UI

### ISSUE THREAD

**Issue by chocomega** [mariotaku/moonlight-tv#172]
Game covers get corrupted when navigating the UI.

There are 3 different ways to see the glitches

**Method A, easy to reproduce**

1. Go to the game list
2. With the Magic Remote D-Pad, go to the 2nd column and scroll down to the 3rd row 
3. With the Magic Remote D-Pad, scroll up to the 1st row
4. There is a glitch under the selected cover
(Actually there's also a glitch when scrolling on the 1st column but it's less obvious)

https://user-images.githubusercontent.com/5123957/184152620-d3057c7e-ef10-4fe8-9f43-083c0fff6590.mp4

**Method B**
1. Go to the game list
2. With the Magic Remote D-Pad, select a cover on any column
3. With the Magic Remote mouse, click and hold to scroll up or down
4. There is a glitch under the covers

https://user-images.githubusercontent.com/5123957/184152648-05aabc9e-dcec-496f-862c-e51e90aac9e2.mp4

**Method C, hard to reproduce**
1. Go to the game list
2. Select a game and start a stream
3. Close the stream
4. Some covers are corrupted

https://user-images.githubusercontent.com/5123957/184153790-dab1dd60-a7b1-46ae-870c-7d7b28f5bfa8.mp4

**Expected behavior**
No glitch

**Basic information**

 - Moonlight version: 1.4.5 and 1.4.9
 - Model: OLED55C16LA
 - webOS version: 6.3.1
 
 **Additional context**
 The gIitches A and B do not happen on 1.4.4.
 I'm not sure about glitch C as it is random but it has not occurred so far on 1.4.4.

**Comment by chocomega** [comment]
The glitches are gone in 1.5.0, thank you 👍

**Comment by chocomega** [comment]
I spoke too soon, the glitch C is still happening on 1.5.1

**Comment by mariotaku** [comment]
Finally be able to find out and fix this issue after a year!
