### ISSUE TITLE
[BUG] LG CX PIN dissapears with in a faction of a second, cannot authenticate. 

### ISSUE THREAD

**Issue by JamesLodge** [mariotaku/moonlight-tv#174]
**Describe the bug**

LG CX65 when selecting the computer to pair, the PIN flashes up briefly and then is covered or closed by another dialogue box the says "Pairing Enter PIN code on your computer". The PIN originally appears for a split second so its hard to see the 4 digits, but even if you do, the PIN doesn't work in Sunshine

**To Reproduce**

1. Add computer running sunshine's IP address
2. Click on the newly added computer
3. PIN shown for a fraction of a second
4. Click "ok" to the new dialogue box "Enter PIN Code on your computer"

**Expected behavior**

PIN to appear for long enough to take note and enter on sunshine server web UI

**Basic information**

 - Moonlight version: 1.5.1
 - Model: LG OLED65CX5LB
 - webOS version 5.4.1-10

**Comment by JamesLodge** [comment]
would a video of the issue help?

**Comment by mariotaku** [comment]
Hi! Although the exact error is not yet known, I've made an update to show the error reason. It will be available few minutes later.

**Comment by JamesLodge** [comment]
Ill keep an eye out for and will test when i see it.

**Comment by JamesLodge** [comment]
It now work fine. The PIN stay onscreen and allows me to authenticate. Previously, if I managed to catch the PIN authentication still failed.

**Comment by mariotaku** [comment]
I'm not sure what was wrong. But It's great that now it works!

**Comment by mariotaku** [comment]
Closing as finished.
