### ISSUE TITLE
[COMPAT] black screen when streaming @4k

### ISSUE THREAD

**Issue by jiong-han** [mariotaku/moonlight-tv#175]
## Basic information

 - Device model: (UK6300PUE) 
 - Firmware version: (05.45.04) 
 - webOS version: (4.4.0) 
 - Moonlight version: (1.5.2) 
 - Is audio working: (Yes) 
 - Is video working: (720P/1080P Yes 2K/4K No) 
 - Is input working: (Yes) 

## Description

Thanks for bringing this amazing work to webOS! I recently installed this and enjoy using it so far watching video and playing games with 1080P@60FPS. I am currently trying 2k and 4k, but 2k gives me snow screen and with 4k, it's just a black screen. The sound and input work perfectly, it's only the video that is not working as expected.
I reviewed the troubleshooting guide and tried other video decoders, but none of them worked. I know it's maybe hard to reproduce this so please let me know if there's any log or something I can look for and I could share it here. Thank you so much!

**Comment by mariotaku** [comment]
Hi, according to recent reports, some older 4K TVs aren't capable of 4K streaming. Maybe this is the case.

**Comment by mateussouzaweb** [comment]
Same problem here. I will try to debug it later...

**Comment by mariotaku** [comment]
Closed due to inactivity.
