### ISSUE TITLE
[FEATURE] Auto wake

### ISSUE THREAD

**Issue by joaopedrosgs** [mariotaku/moonlight-tv#176]
**Is your feature request related to a problem? Please describe.**
Whenever I open the app, I have to press  "wake" one or two times and then "retry" to connect

**Describe the solution you'd like**
An option to auto wake the computer when you open the application

**Describe alternatives you've considered**
There is no alternative besides clicking the buttons and waiting

**Comment by mariotaku** [comment]
Hi. While I may not add auto wake, I will improve Wake on LAN feature. How long does it take for your PC to completely awake, after you send the request?

**Comment by joaopedrosgs** [comment]
It takes between 3 and 5 seconds

**Comment by mariotaku** [comment]
I see. I'll test on real world cases, and adjust the timeout of retry button.

**Comment by joaopedrosgs** [comment]
Thank you for answering this issue/feature request
And thank you for creating and maintaining this awesome project!

**Comment by mariotaku** [comment]
Status update after WoL looks better now. I'll close this issue and feel free to reopen/open a new one if you still have issues with that.
