### ISSUE TITLE
[BUG] Repeated ESC Key Event

### ISSUE THREAD

**Issue by tobi1449** [mariotaku/moonlight-tv#177]
**Describe the bug**

Sometimes the ESC key is regularly (~ once per second) sent to my PC when playing, which results in opening menus in games, closing fullscreen in some apps or opening exit prompts.

**To Reproduce**

I haven't found a way to reliably reproduce it yet :(

**Basic information**

 - Moonlight version: 1.5.2
 - Model: OLED65B19LA
 - webOS version 6.3.0 (3.30.10)

**Additional context**

 - Xbox Elite 2 Controller connected via Bluetooth directly to TV

**Comment by BrenoAquino** [comment]
I had a similar issue with my TV, but it happened every time. The problem was my OLED TV didn’t map the elite controle buttons right. To solve that, I bought an 8BitDo usb adapter v2 to connect to my elite controller and use this adapter instance of connect straight to the controller.

**Comment by mariotaku** [comment]
This issue may no longer be valid, so I'll be closing it now. Please let me know if it still happens.
