### ISSUE TITLE
[COMPAT] No Audio output

### ISSUE THREAD

**Issue by enterthedar** [mariotaku/moonlight-tv#180]
## Basic information

 - Device model: (    OLED55B7V   ) 
 - Firmware version: (   06.00.30    ) 
 - webOS version: (   3.9.0    ) 
 - Moonlight version: ( 1.5.3      ) 
 - Is audio working: (  No     ) 
 - Is video working: (   Yes    ) 
 - Is input working: (  Yes     ) 

## Description

No audio. First time using Moonlight. Anything I can adjust to get it working? None of the outputs in Windows > Settings are working.

**Comment by mariotaku** [comment]
Please don't select audio output. It might be something related to audio backend of Moonlight. Please open Moonlight Settings -> Audio & Video to select something else like PulseAudio.

**Comment by enterthedar** [comment]
> Please don't select audio output. It might be something related to audio backend of Moonlight. Please open Moonlight Settings -> Audio & Video to select something else like PulseAudio.

That sorted it. Many thanks!
