### ISSUE TITLE
[BUG] Moonlight crashes right after the stream starts

### ISSUE THREAD

**Issue by PieroGiovanni** [mariotaku/moonlight-tv#184]
- Moonlight version: 1.5.3
 - Model: 43UM7100PSA
 - webOS version:  4.9.7
 - Firmware version: 05.30.11

1. Go to Moonlight
2. Click on any application you want to stream from the PC
3. Moonlight crashes after loading

I was able to stream from my computer to the TV, but for some reason I can't do it anymore. It shows the application for a sec, then it crashes and Moonlight closes. I can stream to my phone's Moonlight, so my PC is not the problem.

Crash report from Device Manager for webOs:

[libkadaptor.so.1.0.0 (_Z11delete_flowP12_FlowManager+0x99) [0x945185ee].txt](https://github.com/mariotaku/moonlight-tv/files/9969711/libkadaptor.so.1.0.0._Z11delete_flowP12_FlowManager%2B0x99.0x945185ee.txt)

**Comment by mariotaku** [comment]
Hi, have you tried other decoders? Do you have any memory of what has changed recently?

**Comment by faqgriezz** [comment]
Similar problem here. Successfully connected my PC with moonlight, but when I'm trying to stream a game the moonlight app closes itself almost instantly after loading the stream. I tried choosing different decoders with the same effect. Are there any logs I could send here to try to resolve this problem?

**Comment by eduardoftdo** [comment]
I’m having the same problem using v1.5.3. I can connect to my pc but when I choose steam the connecting load screen appears for a second and then it crashes. Tried every decoder and both NDL and Netcast crash right away while SMP stays on the connecting screen forever

**Comment by PieroGiovanni** [comment]
> Hi, have you tried other decoders? Do you have any memory of what has changed recently?

I did not change anything. I even did a hard reset on my TV, but that didn't solve the problem.
Apparently, I'm not the only one having this problem.

**Comment by mariotaku** [comment]
@choboko Something must have been changed, either it's firmware of the TV, or a newer Moonlight has been installed. Did you try older versions?

**Comment by choboko** [comment]
Well, I went to check for updates just to be sure that it didn't update itself without my permission. But somehow, apparently it did, because when i check for updates it says no updates are available (meaning i now have the latest version). So I guess that's the issue. My TV model is SM8000PSA, the software version is 05.30.20.

**Comment by eduardoftdo** [comment]
Just checked my TV, and it's the same software version as @choboko 05.30.20 with no new update available. My TV model is 50UM7360.

**Comment by smworks** [comment]
New user here. Also have the same issue. While trying multiple times for a moment I could see game being streamed, but after that app seems to crash. Any workarounds for this?

**Comment by mariotaku** [comment]
It might be some memory corruption issue. I'll prepare something to try out later.

**Comment by BNeutral** [comment]
Same issue on after upgrading to 05.30.20 webOS. Used to work before. Tried a few older moonlight versions and that doesn-t seem to be the problem. Hopefully I can make some time during the weekend to give this a look and provide more relevant info.

**Comment by nolemretaWxd** [comment]
Same issue happening on 43UM7450PLA running WebOS 4.9.7 and firmware 05.30.20

**Comment by avra-m3** [comment]
I'm experiencing the same issue.

It seems the video output is a red herring, I changed audio to ALSA and was able to stream, unfortunately that broke the audio output. 
Hopefully this will help with debugging. 
Firmware version 5.30.20 as well.

**Comment by BNeutral** [comment]
Hm, are there any building from source instructions around? I tried to run the debugger on the release ipk, but got nothing relevant out of it. I assume because it's minified.

**Comment by mariotaku** [comment]
> Hm, are there any building from source instructions around? I tried to run the debugger on the release ipk, but got nothing relevant out of it. I assume because it's minified. Am no experte on webos development.

Hi, you can run `scripts/webos/easy_build.sh` after installed toolchain.

**Comment by PieroGiovanni** [comment]
As @avra-m3 said, it works with the audio encoder ALSA, no sound through TV tho.

**Comment by mariotaku** [comment]
Hi everyone in this issue. I was finally able to see the issue after firmware update.

**Comment by ricochet1k** [comment]
> Hi everyone in this issue. I was finally able to see the issue after firmware update.

I'm seeing this problem too. Anything I can do to help? I have more crash dumps if that helps. I'm new to Moonlight/WebOS but I have a TV I'd like to use this with.

**Comment by eduardoftdo** [comment]
Is there any fix available? I haven’t been able to use moonlight since I had this bug

**Comment by mariotaku** [comment]
> Is there any fix available? I haven’t been able to use moonlight since I had this bug

I'm working on the next version to address this issue now.

**Comment by OutPut-translate** [comment]
> > Доступно ли какое-либо исправление? Я не мог использовать лунный свет с тех пор, как у меня была эта ошибка
> 
> Сейчас я работаю над следующей версией, чтобы решить эту проблему.

Привет. Не могу понять что произошло, раньше работал, телевизор заключило, скинутся до заводских, установил все что было раньше и вылетает на соединении, 1с экрана и вылетает из приложения. На компьютере пробовал и откатить драйвера и кодеки установил, не пойму в чем проблема. Может из-за драйверов на реалтек?

Hello.  I can’t understand what happened, I used to work, the TV concluded, they folded to the factory ones, installed everything that was before and crashes on the connection, 1s of the screen and crashes out of the application.  I tried to roll back the drivers and installed codecs on the computer, I don’t understand what the problem is.  Maybe because of the realtek drivers?

**Comment by mariotaku** [comment]
v1.5.4 should avoid using buggy audio backend automatically. Please give that a shot!

**Comment by mariotaku** [comment]
@choboko Hi. I'll take some further look of default audio backend issue. Can you show me the about screen of moonlight? It's in Settings - About.

Also for the video resolution, the resolution displayed is what your computer produced. I guess there's a chance that the TV can't play video correctly because it opened 4K stream but got 1080p.

**Comment by jscanzano** [comment]
Hi! (Thanks so much for pinning this, this thread was a big help)
I encountered the same issue as OP on 1.5.4 and switching to PulseAudio fixed it for me too. 5.30.30 on UM6910PUCg.

**Comment by choboko** [comment]
> @choboko Hi. I'll take some further look of default audio backend issue. Can you show me the about screen of moonlight? It's in Settings - About.
> 
> Also for the video resolution, the resolution displayed is what your computer produced. I guess there's a chance that the TV can't play video correctly because it opened 4K stream but got 1080p.

Here's what the About section: 
![20230528_103247](https://github.com/mariotaku/moonlight-tv/assets/7576451/1c0729ed-ee07-4fbe-885a-889ef194cac8)

As for the video resolution, my PC is producing video at 4k, I use Moonlight in 4k with my laptop and it's working. As I said, this started happening after updating the firmware to version 5.30.20, before that it worked fine. My TV is asking me to update it to 5.30.30. Should I try that? Thanks for the reply!

**Comment by mariotaku** [comment]
@choboko I'm not sure, but I think it doesn't hurt if 4K is broken already :)
BTW I found the cause of NDL audio still being selected on certain models, I'll make a new release to address that.

**Comment by choboko** [comment]
Updating the firmware didn't help. The Auto function on audio is still not working for me. I tried every variation possible with audio and video, the only combinations that works on 1080p are NDL Video with ALSA or Pulse Audio. ALSA gives me a lot of delay, Pulse Audio works fine.

Also, I remember that before updating my TV the only video decoder that worked was SMP, and now the only one that works is NDL. I could stream 4K using SMP. I don't know if that information helps. I'll send the crash log I got from Dev Manager when I set the decoder to SMP, maybe there's something there.
[crash log.txt](https://github.com/mariotaku/moonlight-tv/files/11628291/crash.log.txt)

**Comment by caioavidal** [comment]
I'm facing the same issue @choboko is facing

**Comment by mariotaku** [comment]
Crash related to `libkadapter.so.1.0.0` has been fixed. Please open a new issue for other crashes.

**Comment by simian-kernel** [comment]
I was facing this as well. In my case, I'd switched from `nvidia-driver-535` to `nvidia-driver-590-open` as Linux Mint said it was the "recommended" driver. But in my case, the recommended driver broke Moonlight.

Reverting to `nvidia-driver-535` reliably fixed the issue.
