### ISSUE TITLE
[COMPAT] 8bitdo ultimate bluetooth - xinput detected but not working

### ISSUE THREAD

**Issue by circoloco696** [mariotaku/moonlight-tv#185]
## Basic information

 - Device model: (LG OLED77C8LLA)
 - Firmware version: (05.50.10)
 - webOS version: (4.4.2-10)
 - Moonlight version: (1.5.3)
 - Is audio working: (yes)
 - Is video working: (4k60fps)
 - Is input working: (no, gamepad)

## Description

8bitdo ultimate bluetooth controller 2.4ghz dongle detected as xinput device on tv but doesn't work. 

As i am optimizing moonlight to perfection on my tv, i did everything to reduce latency (full wired setup with usb to ethernet adapter on tv, tv set to game mode, every picture enhancements turned off) everything works close to native 4k60 performance. The last thing is now the gamepad connection via bluetooth that has a higher latency compared to a 2.4 ghz connection.

Today i got the 8bitdo ultimate bluetooth controller. When i connect the 2.4ghz usb dongle to the tv, **it is detected as xinput device if i turn on the gamepad**, but isn't working. 

Is there some way to get this to work ?

Thanks

**Comment by mariotaku** [comment]
Hi, the gamepad may not be mapped yet. IIRC it's a pretty new device right?

**Comment by circoloco696** [comment]
Yes its a few days on the market. So theres a chance this could work in the future?

**Comment by mariotaku** [comment]
@circoloco696 Of course! This supported will be added automatically once the mapping was added to https://github.com/gabomdq/SDL_GameControllerDB .

**Comment by mariotaku** [comment]
I don't have such controller so I have no way to add it, but you can. If you happen to know how to add this, you can make contribution to the link above.

**Comment by circoloco696** [comment]
Okay i will try to create the mapping. After adding it, is a moonlight update necessary? How is moonlight getting the new controller mapping ?

**Comment by mariotaku** [comment]
@circoloco696 No, you don't have to update moonlight. Once the mapping is available moonlight will download it automatically.

**Comment by circoloco696** [comment]
@mariotaku i made the mapping with the sdl2 gamepad tool, but i dont know how to commit it to the github. Maybe you can add it.

Thats the mapping:

03000000c82d00000631000000007801,8BitDo Ultimate Bluetooth 2.4ghz,a:b0,b:b1,y:b3,back:b6,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,platform:Windows,

**Comment by mariotaku** [comment]
Sorry that I didn't provide enough information. For webOS the mapping should be the same to Linux. Thanks for this one! I will commit this Windows mapping to the repo first, and write some tools to help you do the mapping on webOS.

**Comment by circoloco696** [comment]
@mariotaku thanks for this ! 
I will do it on my steam deck later that runs arch linux and post the mapping here in the comments. I hope this will work

**Comment by mariotaku** [comment]
I believe it will work! I really appreciate your contribution.

**Comment by circoloco696** [comment]
Im happy to help, if im able to. 

Sadly the gamepad wont recognize at all if i connect it to linux... or i am not able to do it correctly.

Maybe some other user with the same gamepad will be able to find out the mapping.

**Comment by circoloco696** [comment]
@mariotaku I did some more tests today and found out that its connecting to linux with the new beta firmware.

Here is the Linux mapping, done on Steam deck Arch Linux. Hope this will work.

03000000c82d00000760000011010000,8BitDo Ultimate Bluetooth 2.4ghz,a:b1,b:b0,x:b4,y:b3,back:b10,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,platform:Linux,

**Comment by wiistriker** [comment]
@circoloco696 i have same gamepad GUID in SDL2 gamepad tool app and same mappings.

If i understand correctly your thread, after adding your mappings to gamecontrollerdb.txt we will be able to have correct input using 8bitdo adapter 2 with xbox one controllers?

**Comment by circoloco696** [comment]
@wiistriker yes, thats how i understand it. 

The mapping was done in i think dinput mode (The beta firmware Readme says this mode got added specifically for linux) That was the only mode the controller got connected on linux (Recognized as "8BitDo Ultimate Bluetooth 2.4ghz" in SDL2) 

If i plug in the dongle in this mode, it get recognized as "hid device connected" on my tv

I don't know if the controller has to be in xinput mode after the mapping got added or has to stay on dinput. Wait and try i guess

**Comment by wiistriker** [comment]
I add both mappings to sdl_gamecontrollerdb.txt file inside moonlight-tv app and xbox one controller start working in dinput mode.

but still without vibration.

**Comment by wiistriker** [comment]
@mariotaku is there any way how can i see log messages from app on webos?

**Comment by mariotaku** [comment]
@wiistriker It's not very easy to get stdout/stderr as an app can't be invoked directly (or it will have some strange issues)
The thing you want to do is to try connecting the adapter to webOS right? IIRC 8bitdo adapter v2 can't be recognized by Linux in XInput mode. Using PS3 mode will make it work (without haptic feedback)

**Comment by wiistriker** [comment]
@mariotaku 
yes, not easy. i cant get permissions to read proc fd/1 in terminal. probably i need to get root terminal, will check it later. 

v2 adapter work even in DInput mode, but without vibration. Do you know why this adapter dont work in XInput on Linux? Is this problem related to adapter itself? When i plug it in tv i get notification: xpad device connected (just like xbox 360 controller). Is it mapping issues?

**Comment by Aldune** [comment]
Figured better to reply here vs in a new issue. Noticed with the 8bitdo v2 adapter using a Dualshock 4 xinput goes crazy and doesn't work at all, and with the other modes either some sticks/triggers work, while some don't. Happy to help do the mappings if someone points me at the right tool to grab them.

**Comment by mariotaku** [comment]
Recent 8bitdo adapters and controllers have issues working on Linux. see [this wiki](https://github.com/mariotaku/moonlight-tv/wiki/Gamepad-Setup)
Since they didn't fix this issue in firmware updates for over a year, I'll have to close it as won't fix.
