### ISSUE TITLE
[BUG] moonlight crashes when i click add computer

### ISSUE THREAD

**Issue by z3dee** [mariotaku/moonlight-tv#191]
**Describe the bug**

App crashes

**To Reproduce**

1. Click on add computer

**Expected behavior**

Crashing without explanation.

**Basic information**

 - Moonlight version: [e.g. 1.5.3]
 - Model: 60UN71003LB
 - webOS version: 04.40.19

**Add context**
 crash report:
[libwayland-client.so.0.3.0 (wl_proxy_marshal_constructor+0x1) [0x9498b63c].txt](https://github.com/mariotaku/moonlight-tv/files/10304202/libwayland-client.so.0.3.0.wl_proxy_marshal_constructor%2B0x1.0x9498b63c.txt)

other than this i just installed moonlight on my tv so i do not know what is causing this.

edit:
installed version 0.9.6 and it crashes when i click in the field to type the ip address of the computer in.
I hope this helps.
*** End of info

**Comment by mariotaku** [comment]
Hi, how did you get the crash log? I noticed that many users are sending truncated crash logs, so I'm thinking if the guide has any issue with collecting logs...

**Comment by Gustash** [comment]
I'm having the same issue. I tried following the Troubleshooting Guide to get a crash report, but the `tmp` folder is always empty, so no logs seem to be collected.

I have a 43UK6300PLB running 4.4.0. It is unrooted and all I did was install the app and tried adding my computer.

**Comment by mariotaku** [comment]
Hi, I found the cause of this crash. A new version will come out shortly.

**Comment by farika** [comment]
Hi, same issue on LG CX. Crash when i click on add computer.

**Comment by mariotaku** [comment]
I released v1.5.6 and it should fix this issue.
