### ISSUE TITLE
Wiki links are 404ing

### ISSUE THREAD

**Issue by Natetronn** [mariotaku/moonlight-tv#192]
Just an FYI, the Wiki links on the Wiki Home page are 404ing:

https://github.com/mariotaku/moonlight-tv/wiki

**Comment by Natetronn** [comment]
Looks like the links in the right sidebar are correct, only the home page links are bad.

For example, on the Home page, Installation Guide goes here:
https://github.com/mariotaku/moonlight-tv/Installation-Guide

But should be:
https://github.com/mariotaku/moonlight-tv/wiki/Installation-Guide

**Comment by mariotaku** [comment]
I have updated the links to use MediaWiki style. Could you help me to check again?

**Comment by Natetronn** [comment]
The links on the Home Page are now working. Thank you!
