### ISSUE TITLE
This will require someone who's both capable of making patches for moonlight and have such TV. I don't have access to this TV so it's impossible to see what's going on inside. Let's first close this issue and move discussions to #35 .

### ISSUE THREAD

**Issue by banan4phon3** [mariotaku/moonlight-tv#202]
This will require someone who's both capable of making patches for moonlight and have such TV. I don't have access to this TV so it's impossible to see what's going on inside. Let's first close this issue and move discussions to #35 .

_Originally posted by @mariotaku in https://github.com/mariotaku/moonlight-tv/issues/164#issuecomment-1193241318_

Hey I talked to you before in july about this problem. I just wanted to ask if since then, a new version maybe solved the problem for this TV model?

**Comment by mariotaku** [comment]
Unfortunately I haven't got any information for debugging since then. So I can't help with the issue yet.

**Comment by mariotaku** [comment]
As #35 is still opened, please continue our discussion in that issue.
