### ISSUE TITLE
[COMPAT] PCs disappeared after the last webOS update.

### ISSUE THREAD

**Issue by BORGdr0ne** [mariotaku/moonlight-tv#205]
- Device model: LG OLED55A13LA
 - Firmware version: 03.34.55
 - webOS version: 6.3.2
 - Moonlight version: 1.5.3

## Description
Hello, after the last update to webOS all 3 of my PC disappeared from the TVs Moonlight.

Any attempt to add a PC with an IP address results in infinite loading with no result.

I noticed that one or two PCs appear after the Moonlight App runs for more than 15 minutes without using the TV but while running the app.

I tried to request a pair with one PC and the code appears but the prompt on the computer does not appear at all.

**Comment by mariotaku** [comment]
Closing as the issue can't be reproduced. It might get improved by recent updates so please try update to the latest versions.
