### ISSUE TITLE
Increase max bitrate

### ISSUE THREAD

**Issue by TomasSim** [mariotaku/moonlight-tv#211]
**Is your feature request related to a problem? Please describe.**
Max 65 Mbps bitrate feels to low for high speed LAN and WIFI connections (~700 Mbps)

**Describe the solution you'd like**
Currently max bitrate on webOS is only 65 Mbps. While PC version has 150 Mbps. 

**Describe alternatives you've considered**
Alternative would be nice to leave max recommended bitrate of 65 Mbps, but allow user to have any bitrate.

**Comment by mariotaku** [comment]
Hi, there are 2 reasons that the limit was set to 65mbps.

1. For many models, LG only has a 100mbps Ethernet port.
2. Even with WiFi or USB Ethernet, webOS only supports up to 65mbps. It sometimes crashes beyond that.

**Comment by TomasSim** [comment]
Thanks for answer! But maybe it would be nice to have checkmark with text - Custom bitrate (might introduce crashes  and stability issues). And checking it will allow user to type custom bitrate value into input field?

I have one more question by the way. With current 65mbps limitation, what is recommended streaming quality, feels like 4k 120fps is too high for that? I've been using it with my setup and never noticed any lag or another issues, just not sure if i'm getting the best image quality, although image looks really sharp.

I'm using LG C2 TV connected to my pc with ryzen 5800x3d and amd 7900xt.

**Comment by mariotaku** [comment]
Sorry, but providing bitrate over specifications is out of the question. I have made some attempt to use slightly higher bitrate on a high end TV but all I got was stuttering, blanking and crashing. The maximum value is stated here by LG: https://webostv.developer.lge.com/develop/specifications/video-audio-220

Recommended quality would be HEVC 4K 60fps with the bitrate of 45mbps.

**Comment by tomassimanaitis** [comment]
Thanks for info, anyway! And thanks for making this app!
