### ISSUE TITLE
[BUG] HDR always forced on

### ISSUE THREAD

**Issue by DrDoakes** [mariotaku/moonlight-tv#212]
**Describe the bug**

HDR is always activates when starting a stream, even with the decoder HDR setting disabled. This happens when I start streaming any game or my Desktop or Steam Link/Big Picture to my LG C1 55". This does not happen on my other Moonlight client (installed on my CCwGTV).
Host PC is using Sunshine v0.18.4. 
Moonlight video/audio decoders are both set to Automatic, Prefer H265 codec is enabled, HDR (experimental) is disabled.
Basic settings: 4k120fps, 35000 kbps bitrate.

This behavior persists even if:
-The game doesn't support HDR 
-HDR is disabled in Windows
-HDR is disabled in the decoder settings
-PC is rebooted
-Sunshine is rebooted
-Moonlight-TV app is uninstalled/reinstalled
-Host PC is unpaired/repaired

If I disable "Prefer H265 codec" I get a black screen when starting a stream.

**To Reproduce**

1. Disable 'HDR (experimental)'
2. Launch any app

**Expected behavior**

HDR shouldn't turn on when its disabled.

**Basic information**

 - Moonlight version: 1.5.3
 - Model: OLED55C1AUB
 - webOS version 6.3.2

**Comment by gjano** [comment]
Same here, just to add the issue does not reproduce when connecting to Gamestream with the exact same settings (same PC and everything). Not sure if there is any setting on the Sunshine side that could help here, I couldn't find any.

**Comment by DrDoakes** [comment]
I reinstalled everything today (Sunshine, Moonlight) to the latest versions and everything seems to be working now, HDR is properly toggling on/off.
