### ISSUE TITLE
Any chance to make m'y gamepad be reconized ?

### ISSUE THREAD

**Issue by acca84** [mariotaku/moonlight-tv#213]
Hello and first thanks for your work
I have an usb gamepad adapter that allows to connect ds4 controller to my LG TV USB port
If i connect it to TV, i have a message saying hid device is connected
Do you think if i send you device mapping as described here webosbrew/apps-repo#77 my gamepad will ne reconized ?
The device is : https://a.aliexpress.com/_ExFrsuD
Thanks again

**Comment by mariotaku** [comment]
Hi that's exactly the case. Do you happen to have Linux computer (or something like Raspberry Pi) running? It's OK if you don't have, I'll work on the gamepad tool later.

**Comment by acca84** [comment]
Ok, thanks
I'll  because the dongle doesn't works on my linux VM
Do you know when it will be released please ?
Thanks again

**Comment by mariotaku** [comment]
I can't give an estimation yet, but I should be able to make the tool first as it's needed by ihsplay too.

**Comment by acca84** [comment]
Hi, 
I juste have rooted my TV, and now my gamepad IS recognized (using webos gamepad homebrew)
It's recognized in Moonlight but not in your steamlink client. IS that normal ?
I tried to play Steam with Moonlight, but image is deformed (i only see part of the screen).
How can i correct this or make my gamepad recognized in steamlink homebrew ?

**Comment by mariotaku** [comment]
Yes. That's normal that ihsplay doesn't support some gamepads. It doesn't ship with gamepad mapping so only a few is supported now.

Please provide more information (or better to create separate issues) about other questions.

**Comment by mariotaku** [comment]
Hi, the gamepad mapping has been updated in recent versions. Please update to recent versions. (I saw someone added some DataFrog products).
