### ISSUE TITLE
Unable to pair with PC running sunshine.

### ISSUE THREAD

**Issue by Pllums** [mariotaku/moonlight-tv#216]
Hello, I installed moonlight through the recommended dev-manager-desktop and am having some trouble pairing my tv to my PC. They are are on the same local network (TV is wifi 5Ghz and PC is hardwired ethernet) and see eachother but I am unable to pair. Whenever I click on my PC through the moonlight UI, instead of giving me the PIN to pair them it tells me there is currently a game running on my machine and that I need to shutdown the game in order to pair. 

Im not sure what other than sunshine would be causing it. I don't have any other apps running right now on my machine.

**Comment by mariotaku** [comment]
Hi, did you try streaming with other devices? Like moonlight on your phone?

**Comment by Pllums** [comment]
Thanks for the reply! Using the same boat setup I am able to successfully stream to an iPad, MacBook ,iPhone and OnePlus 7 Pro phone all on the same network.

**Comment by mariotaku** [comment]
Hi! Would you like to try if new versions are working for you?

**Comment by mariotaku** [comment]
Closing the issue now. Feel free to reopen if the pairing problem still exists.
