### ISSUE TITLE
Gamepad 8bitdo Ultimate 2.4G

### ISSUE THREAD

**Issue by OutPut-translate** [mariotaku/moonlight-tv#217]
Здравствуйте. Подскажите пожалуйста почему на web os 4.9 , геймпад  8bitdo Ultimate 2.4G работает только d input, и в некоторых играх левый стик работает с заиканиями. Тесть нажимаешь в верх ничего, ещё раз сработало, потом не отпуская стик персонаж в игре останавливается. Возможно ли Като решить проблему с вашей помощью или это к производителю геймпада? Или телевизор. И да кстати в x input  не работает вовсе данный геймпад, другой же китайский работает. Куда обратится?

---

Translation

Hello. Please tell me why on web os 4.9, the 8bitdo Ultimate 2.4G gamepad only works with d input, and in some games the left stick works with stutters. Father-in-law you press to the top nothing, it worked again, then without releasing the stick the character in the game stops. Is it possible for Kato to solve the problem with your help or is it to the controller manufacturer? Or TV. And by the way, this gamepad does not work at all in x input, while another Chinese one works. Where will he turn?

**Comment by mariotaku** [comment]
Hello, recent 8bitdo products may not have very good support with Xinput. It can't work properly on most Linux based systems without some system configuration, which is not possible on webOS.

**Comment by mariotaku** [comment]
I'll do some experiments about 8bitdo adapters/gamepads later.

**Comment by mariotaku** [comment]
This is the exact issue. See https://github.com/mariotaku/moonlight-tv/wiki/Gamepad-Setup .

**Comment by OutPut-translate** [comment]
> Привет! У меня такая же проблема с контроллером серии Xbox.

У меня работает только в режиме d-input, x-input не поддерживается телевизором web os 4.5, это со стороны lg. Глюки в игре были со стороны игры в режиме d-input.

**Comment by mariotaku** [comment]
I'll close this issue for now. 8bitdo controllers and adapters on the market after 2021 may have some compatibility issues and can't be fixed on our side.
