### ISSUE TITLE
[BUG] Constant 9-10 FPS, despite settings for 1080p@60 (35Mbps)

### ISSUE THREAD

**Issue by Fooughhy** [mariotaku/moonlight-tv#221]
**Describe the bug**

**EDIT: I thought Moonlight-TV reported 9-10 FPS, but that was only when I wasn't moving the mouse. Once I start moving the mouse, it shows 60 FPS.**

The issue is that on my TV (non-rooted) I am seeing constant 1 FPS despite having my settings for 1080p@60. If I open the stream on my phone, I see a clear 1080p@60 (I mean I don't know it's exactly 60, but it's smooth).

**To Reproduce**

1. Install Sunshine on PC
2. Install Moonight-TV 1.5.4 (it was the same on 1.5.3)
3. Use any setting on Moonlight-TV (I have tried changing from SMP-NDL, Bitrate, etc)

**Expected behavior**

It should be 1080p@60 on the TV

**Basic information**

 - Moonlight version: 1.5.4
 - Model: 55UJ635V-ZF
 - webOS version: 3.9.2-62912
 - webosbrew version: 0.6.3

**Additional context**

I thought it was an issue with WIFI, so I changed to a wired connection now. That fixed it for one session but now the issue is back, even on a wired connection.

Moonlight-TV reports normal FPS (though the actual framerate is more like on frame every 3 seconds), 0% frame drops, Network RTT 1ms, decode time 0.8 ms.

**Comment by mariotaku** [comment]
moonlight-tv reports how many frames received per second. When there's no screen update, the host will not send pictures, so the frame rate drops. It's not a problem if you don't feel a low frame rate when things are moving on the screen.

**Comment by Fooughhy** [comment]
I am not sure why you closed this so fast... I gave all the information in the post, but I can clarify.

When I am streaming just my desktop using Sunshine to Moonlight-TV, I am getting around 9-10 FPS in the UI for moonlight-tv. At this point I can't see the "smoothness" on the screen, so I move my mouse once across the screen. The moonlight-tv shows that the FPS increased so something like 11-12 but it takes around 3 seconds for the actual mouse to move on the TV screen. So the **perceived** FPS is something like 0.333... FPS.

If I instead start moving the mouse very erratically, the FPS in moonlight-tv will show around 59 FPS instead, and in this case the **perceived** FPS on the TV screen will be something like 1 FPS.

This is the issue I am having.

**Comment by mariotaku** [comment]
@Fooughhy Sorry, I think I have misunderstood. In normal condition, FPS displayed is low when there's no update on the screen. I thought you were talking about FPS on the performance overlay.
So it means, even you open something like a video or a game on the screen, you'll only get something like a slideshow on the TV?

**Comment by Fooughhy** [comment]
No problem. Yes, exactly. Moonlight-tv reports everything as-if it's functioning completely fine. And it was working fine a couple of months ago... I don't know what has happened in-between. But now, as you say, it looks like a slideshow.

**Comment by mariotaku** [comment]
What was the bitrate by the way?

**Comment by Fooughhy** [comment]
I've tried between 20 Mb/s up to 40 Mb/s.

**Comment by mariotaku** [comment]
There is another decoder called NetCast Legacy/ LGNC. Did you try that too?

**Comment by Fooughhy** [comment]
It seems to have fixed itself now. The only change I have made was to not have "auto" as the video decoder. I am using WebOS NDL right now. 35Mbit/s. No real other changes... So weird... Maybe the issue will return but for now it seems to work.

**Comment by exoss** [comment]
do you have any solution suggestions?

**Comment by mariotaku** [comment]
After some investigations, the TV in this issue is having k3lp SoC, which is similar to its successor k5lp, have broken NDL decoder.
NDL will be disabled for those models.
