### ISSUE TITLE
[BUG] crash => moonlight (SDL_GameControllerAddMappingsFromRW+0xfc3c)

### ISSUE THREAD

**Issue by TheFurnace** [mariotaku/moonlight-tv#223]
**Describe the bug**

App Crashes when clicking "Add computer"

**To Reproduce**

1. Open App
2. Click Add Computer
3. Crash
**Expected behavior**
Don't crash

**Basic information**

 - Moonlight version: 1.5.5
 - Model: OLED65C2PUA
 - webOS version 7.3.0-29

> To check version, go to Settings > Quick Settings > General > About this TV > webOS TV Version

**Additional context**

Crash details attached
[crash2.txt](https://github.com/mariotaku/moonlight-tv/files/11585453/crash2.txt)
[crash1.txt](https://github.com/mariotaku/moonlight-tv/files/11585454/crash1.txt)

**Comment by TheFurnace** [comment]
Update, I've backtracked through the versions and it seems 1.49 works. The issue seems to start in 1.50 (at least for my specific TV and webOS versions)

**Comment by TheFurnace** [comment]
Also, 1.5.1 seems to work as well.

**Comment by mariotaku** [comment]
Hi, I think this issue is the same as #191. I'll fix this issue in v1.5.6.
