### ISSUE TITLE
[COMPAT] Moonlight crashes while connecting

### ISSUE THREAD

**Issue by Voull** [mariotaku/moonlight-tv#225]
## Basic information

 - Device model: (55UM7520PSB) 
 - Firmware version: (05.30.30) 
 - webOS version: (4.9.0) 
 - Moonlight version: (1.5.6) 
 - Is audio working: (No) 
 - Is video working: (No)
 - Is input working: (No)

## Description

Moonlight crashes while it tries to connect to host.

Host initializes application (in this case Steam) normally, after that TV exits Moonlight.

Decoders tried:
SMP + ALSA
NetCast Legacy + ALSA
NetCast Legacy + NetCast Legacy

Crash Report:
[_var_palm_jail_com.limelight.webos_lib_libc-2.24.so (gsignal+0xc4) [0x969e9ec0].txt](https://github.com/mariotaku/moonlight-tv/files/11646085/_var_palm_jail_com.limelight.webos_lib_libc-2.24.so.gsignal%2B0xc4.0x969e9ec0.txt)

**Comment by mariotaku** [comment]
Hi! Did you try other decoders, like NDL?

**Comment by Voull** [comment]
I've just tried NDL + ALSA and NDL + NetCast Legacy.

This time Moonlight didn't crash.
Both yield the same error:

Failed to Start Streaming
Connection failed at stage 9 (video stream establishment), errorCode = -1 (Unknown error -1)

**Comment by Voull** [comment]
For some magical reason, now it is working.

There is a few seconds of sound lag, but the main issue of connection is solved (NDL + ALSA).

Thanks!
