### ISSUE TITLE
[COMPAT]OLED65C9PUA

### ISSUE THREAD

**Issue by submatrix** [mariotaku/moonlight-tv#23]
# Basic information

 - Device Model: OLED65C9PUA
 - System Version: 05.00.03
 - Is Audio Working: Yes
 - Is Video Working: 4K60fps, 50000 bitrate
 - Is Input Working: Remote (also tested DS4 with 8bitdo in a previous version, which worked) 

Video is slightly desaturated compared to direct HDMI input on the same TV. I tested this by switching back and forth between my PC's HDMI input to TV and the Moonlight webOS app.

**Comment by submatrix** [comment]
After discussing with mariotaku, turns out I am on webOS 4.9.0.

**Comment by mariotaku** [comment]
Thank you for your info, I'm closing this issue as it's now done. Feel free to comment if you have new findings regarding compatibility about your device.
