### ISSUE TITLE
[BUG] Cannot Connect To Client PC on LG Cinebeam

### ISSUE THREAD

**Issue by hyundoo-zigzag** [mariotaku/moonlight-tv#233]
**Describe the bug**

I cannot connect to PC on LG Cinebeam

**To Reproduce**

1. Go to webOS Dev Manager
2. Install Moonlight
4. Run Moonlight
5. Enter IP Address
6. Click "OK"
7. See error

**Expected behavior**

Connecting with PC

**Basic information**

 - Moonlight version: 1.5.8
 - Model: PJTR HU70LA
 - webOS version 4.7.0

[error_log.txt](https://github.com/mariotaku/moonlight-tv/files/11772111/error_log.txt)

**Comment by hyundoo-zigzag** [comment]
I did nothing but Accidently Work!

**Comment by mariotaku** [comment]
Hi! I'm working on this issue now. It should be the same as #231. 
You can try v1.5.9 to see what error message it will give.

**Comment by mariotaku** [comment]
Closing because this is a duplicate. Don't worry, I'm working on this so it will be fixed soon.

By the way your device is very interesting. Feel free to create issues if you have other issues using moonlight.
