### ISSUE TITLE
[BUG] Fatal error - Failed to create GS_CLIENT

### ISSUE THREAD

**Issue by theMichaelG6** [mariotaku/moonlight-tv#238]
**Describe the bug**

When opening the app I get a Fatal Error Message

**To Reproduce**

Installed Moonlight via webOS Dev Manager.
Error appears after opening moonlight. See attached image below for exact error message

**Expected behavior**

Launch moonlight without errors

**Basic information**

Moonlight version: 2.5.9
Device Model:50UQ8000PSC
webOS TV Version: 7.3.0-2407

**Additional context**
![IMG_3069](https://github.com/mariotaku/moonlight-tv/assets/48197373/59c36aff-b719-4352-ba71-c83557339729)

**Comment by mariotaku** [comment]
This is the same issue as #231 and will be fixed soon.
