### ISSUE TITLE
Oled65E6

### ISSUE THREAD

**Issue by Ascorbat** [mariotaku/moonlight-tv#24]
# Basic information

 - Device Model: OLED65E6
 - System Version: 05.30.95
 - Is Audio Working: Yes
 - Is Video Working: 4K 60Fps
 - Is Input Working: F710 Working 

Using gamepad disables magic remote cursor.

**Comment by mariotaku** [comment]
Thanks for your info! https://github.com/mariotaku/moonlight-tv/releases/tag/v0.3.0 Might work for you. To enable the cursor again, simply scroll or shake the remote like in other apps, it will appear again.
