### ISSUE TITLE
[BUG] The XBox Button or View button not working

### ISSUE THREAD

**Issue by sachinpatl** [mariotaku/moonlight-tv#249]
**Describe the bug**
The XBox Button or View button   not working. (Button number 5 and 3 respectively as mentioned on this page - https://support.xbox.com/en-AU/help/hardware-network/controller/xbox-one-wireless-controller) 
The buttons work when we are directly connected to PC but not when we are connected to LG TV through Webos Gamepad app [webos-gamepad](https://github.com/Superd22/webos-gamepad)

**To Reproduce**

1. Connect the XBox Controller to LG TV through [webos-gamepad](https://github.com/Superd22/webos-gamepad) app.
2. Launch the game through Moonlight
3. Try tapping the XBox Button or View button  Button.

**Expected behavior**
The Buttons should work as they work when connected to PC directly.

**Comment by sachinpatl** [comment]
@mariotaku  - 
Also noted that this is not the issue with Android Moonlight client.

**Comment by sachinpatl** [comment]
Accidentally closed the INC now reopened it.

**Comment by mariotaku** [comment]
@sachinpatl I'll try with my controller. The mapping seems to be completely handled by the OS so we can't change its mapping.

**Comment by sachinpatl** [comment]
BTW does the XBox button and View button works for you or you are yet to check???

**Comment by mariotaku** [comment]
> BTW does the XBox button and View button works for you or you are yet to check???

I didn't check that yet. Because I mainly use USB wireless adapters.

**Comment by sachinpatl** [comment]
Yes please, thanks!

**Comment by sachinpatl** [comment]
Update -

Tried a lot of things, different mappings with the gamepad and the final thing that worked without much of a change is -
Addition of the following code - 

`sachinp@ubuntu-virtual-machine:~/webos/moonlight-tv-test$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   app/platform/sdl/navkey_sdl.c
	modified:   scripts/webos/easy_build.sh
	modified:   third_party/ss4s (modified content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	scripts/webos/gamecontrollerdb.txt

no changes added to commit (use "git add" and/or "git commit -a")
sachinp@ubuntu-virtual-machine:~/webos/moonlight-tv-test$ git diff app/platform/sdl/navkey_sdl.c
diff --git a/app/platform/sdl/navkey_sdl.c b/app/platform/sdl/navkey_sdl.c
index d352aef2..de003efa 100644
--- a/app/platform/sdl/navkey_sdl.c
+++ b/app/platform/sdl/navkey_sdl.c
@@ -11,6 +11,7 @@ NAVKEY navkey_from_sdl_webos(const SDL_Event *ev);
 static NAVKEY navkey_gamepad_map(SDL_JoystickID which, Uint8 button);
 
 NAVKEY navkey_from_sdl(const SDL_Event *ev, bool *pressed) {
+    static int tmp;
     switch (ev->type) {
         case SDL_KEYDOWN:
         case SDL_KEYUP: {
@@ -46,6 +47,7 @@ NAVKEY navkey_from_sdl(const SDL_Event *ev, bool *pressed) {
         }
         case SDL_CONTROLLERBUTTONDOWN:
         case SDL_CONTROLLERBUTTONUP: {
+            tmp = ev->jbutton.button;            
             *pressed = ev->cbutton.state == SDL_PRESSED;
             return navkey_gamepad_map(ev->cbutton.which, ev->cbutton.button);
         }
sachinp@ubuntu-virtual-machine:~/webos/moonlight-tv-test$ 

`

I am not sure why and don't have rooted TV to enable logging daemon. 

This code change does not make a any of sense to me, I had added a overlay label and was showing events on it. I saw that when I press the view button there is an event detected but it was detected as Joystick event. To get the mapping I decided to show the Joystick button and when I access the event->jbutton.button it started working.

I then removed all the other code and kept this one and it still is working. Don't know the internal implementaion of the SDL2 but this somehow is working. Can someone explain and can we get this in the main branch.

**Comment by sachinpatl** [comment]
Update  -

Thanks to @mariotaku  for helping me setup the project. I was lost and this was the first time I tried my hands on a webos native project.

Tried a lot of things, different mappings with the gamepad and the final thing that worked without much of a change is -
Addition of the following code -
```

sachinp@ubuntu-virtual-machine:~/webos/moonlight-tv-test$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
(use "git add ..." to update what will be committed)
(use "git restore ..." to discard changes in working directory)
(commit or discard the untracked or modified content in submodules)
modified: app/platform/sdl/navkey_sdl.c
modified: scripts/webos/easy_build.sh
modified: third_party/ss4s (modified content)

Untracked files:
(use "git add ..." to include in what will be committed)
scripts/webos/gamecontrollerdb.txt

no changes added to commit (use "git add" and/or "git commit -a")
sachinp@ubuntu-virtual-machine:~/webos/moonlight-tv-test$ git diff app/platform/sdl/navkey_sdl.c
diff --git a/app/platform/sdl/navkey_sdl.c b/app/platform/sdl/navkey_sdl.c
index d352aef2..de003efa 100644
--- a/app/platform/sdl/navkey_sdl.c
+++ b/app/platform/sdl/navkey_sdl.c
@@ -11,6 +11,7 @@ NAVKEY navkey_from_sdl_webos(const SDL_Event *ev);
static NAVKEY navkey_gamepad_map(SDL_JoystickID which, Uint8 button);

NAVKEY navkey_from_sdl(const SDL_Event *ev, bool *pressed) {

static int tmp;
switch (ev->type) {
case SDL_KEYDOWN:
case SDL_KEYUP: {
@@ -46,6 +47,7 @@ NAVKEY navkey_from_sdl(const SDL_Event *ev, bool *pressed) {
}
case SDL_CONTROLLERBUTTONDOWN:
case SDL_CONTROLLERBUTTONUP: {
       tmp = ev->jbutton.button;            
       *pressed = ev->cbutton.state == SDL_PRESSED;
       return navkey_gamepad_map(ev->cbutton.which, ev->cbutton.button);
   }
sachinp@ubuntu-virtual-machine:~/webos/moonlight-tv-test$

```

I am not sure why and don't have rooted TV to enable logging daemon.

This code change does not make a any of sense to me, I had added a overlay label and was showing events on it. I saw that when I press the view button there is an event detected but it was detected as Joystick event. To get the mapping I decided to show the Joystick button and when I access the event->jbutton.button it started working.

I then removed all the other code and kept this one and it still is working. Don't know the internal implementaion of the SDL2 but this somehow is working. Can someone explain and can we get this in the main branch.

**Comment by mariotaku** [comment]
@sachinpatl Hi, accessing `jbutton` in `SDL_CONTROLLERBUTTON*` event would be a mistake. It will access unintended memory location in that case.

**Comment by sachinpatl** [comment]
No it's not in SDL_CONTROLLERBUTTON, it's inside SDL_Event -> jbutton -> button

**Comment by mariotaku** [comment]
@sachinpatl That access was in `SDL_CONTROLLERBUTTONUP`, while `SDL_Event` is an union, accessing `jbutton` in that case is not valid.

**Comment by mariotaku** [comment]
I can't reproduce with my controller connecting with Bluetooth. So it's better to [use an adapter](https://github.com/mariotaku/moonlight-tv/wiki/Gamepad-Setup#connect-using-adapter-recommended) for your case:
