### ISSUE TITLE
[BUG] Audio not working, seemingly non-deterministically.

### ISSUE THREAD

**Issue by ASAPHAANING** [mariotaku/moonlight-tv#250]
**Describe the bug**

It seems like 90% of the time, the audio will not work on my TV. I've tried messing around with the volume mixer to switch between different devices but no matter what I do, once the audio fails on launch, I cannot make it work.

I do see the NVIDIA HDMI Out device there, and what I've noticed is it starts at 0 volume when the error occurs. The few times it works I haven't verified whether that's the case too, I will try to keep this thread updated with any patterns I find along the way.

Audio backend is set to auto and it selects WebOS NDL.

When selecting the ALSA backend I can hear the sound playing from my host machine. (Not the desired outcome)

**To Reproduce**

1. Go to the Moonlight app and launch it
2. Click on any option. I usually go with Steam Big Picture
3. Video streams perfectly yet there's no sound.

**Expected behavior**

I expect the sound to work 100% of the time.

**Basic information**

 - Moonlight version: 1.5.10
 - Model: OLED55B8PLA
 - webOS version 05.50.15

**Additional context**

Will update thread when I find more patterns.

**Comment by mariotaku** [comment]
Hi, did you try streaming with other official clients, such as Android or iOS version?

**Comment by ASAPHAANING** [comment]
I tried with

- Xiaomi Mi Pad 5
- iPhone XS

Both worked great. Btw before I continue allow me to thank you for putting this client out there. When it works it's simply the best in terms of bitrate & latency.

**Comment by mariotaku** [comment]
Audio issue should be fixed in recent releases. Feel free to reopen if you still notice issues.
