### ISSUE TITLE
App gets removed after a few days on LG C1 TV

### ISSUE THREAD

**Issue by adeelaak0** [mariotaku/moonlight-tv#251]
## Basic information

 - Device model: LG C1
 - Firmware version: (       ) 
 - webOS version: (       ) 
 - Moonlight version: (       ) 
 - Is audio working:YES
 - Is video working:YES
 - Is input working:YES

## Description
I can install the app and get it working fine however after a few days the app disappears from the WebOS on LG TV and I have to go into developer mode to reinstall it again.

**Comment by mariotaku** [comment]
It's in the installation guide. https://github.com/mariotaku/moonlight-tv/wiki/Installation-Guide#important-notice

To renew dev mode session, you can try https://github.com/webosbrew/dev-manager-desktop/ if you don't want to or can't root the TV.

**Comment by mariotaku** [comment]
Closing as the question has been answered.
