### ISSUE TITLE
[FATAL ERROR] Failed to create config directory (Permission denied)

### ISSUE THREAD

**Issue by leo025** [mariotaku/moonlight-tv#253]
Hi @mariotaku please I would appreciate your assistance. I have encountered a similar issue, but I have not yet discovered a solution. 

My WebOS is 3.9.2 and I installed the latest version of the app 1.5.10

Error message:

Fatal error
Failed to generate client info: Failed to create config directory /media/developer/apps/usr/palm/applications/com.limelight.webos/conf/key: Permission denied

This is my ls output:

```
# ls -la /media/developer/apps/usr/palm/applications/com.limelight.webos/
/media/developer/apps/usr/palm/applications/com.limelight.webos/:
total 80
drwxrwxr-x    7 root     root          4096 Jul 1 21:21 .
drwxrwxr-x    6 root     root          4096 Jul 1 16:27 ..
-rw-r--r--    1 root     root           388 Jul 1 21:21 appinfo.json
drwxrwxr-x    2 root     root          4096 Jul 1 21:21 assets
drwxrwxr-x    2 root     root          4096 Jul 1 21:21 bin
drwxrwxr-x    2 root     root          4096 Jul 1 21:21 conf
-rw-r--r--    1 root     root          3257 Jun 18  2022 icon.png
-rw-r--r--    1 root     root          5762 Jun 18  2022 icon_large.png
drwxrwxr-x    2 root     root          4096 Jul 1 21:21 lib
drwxrwxr-x   13 root     root          4096 Jul 1 21:21 resources
-rw-r--r--    1 root     root          36192 Jun 18  2022 splash.png
```
I would appreciate some help with this issue. Thank you in advance.

_Originally posted by @leo025 in https://github.com/mariotaku/moonlight-tv/issues/231#issuecomment-1616672552_

**Comment by mariotaku** [comment]
This is a duplicate to #231. Please continue in the original issue.
