### ISSUE TITLE
[COMPAT] Input regression in 1.5.11?

### ISSUE THREAD

**Issue by cbynep** [mariotaku/moonlight-tv#256]
## Basic information

 - Device model: (60UN71006LB) 
 - Firmware version: (03.21.75) 
 - webOS version: (5.2.1-2521) 
 - Moonlight version: (1.5.11) 
 - Is audio working: (Yes) 
 - Is video working: (Yes) 
 - Is input working: (No gamepad) 

## Description

I was using Dualshock 4 through 8bitdo adapter, which worked as expected on 1.5.3, haven't updated since, but decided to check for new version today and was greeted with no gamepad input on 1.5.11. Had to manually install 1.5.10 to test and my setup is working again, didn't test versions inbetween 1.5.3-1.5.10.

**Comment by mariotaku** [comment]
Hi, the mapping was deleted to fix #231 , I'll add it back (with a new way) in future releases.

**Comment by mariotaku** [comment]
Added back in recent releases.
