### ISSUE TITLE
[BUG] WebOS SMP on WebOS 3.9.0 won't wakelock screen panel

### ISSUE THREAD

**Issue by Marocco2** [mariotaku/moonlight-tv#259]
**Describe the bug**

If you use webOS SMP as decoder, in a couple of minutes TV will go to screen saver mode even if there is action on screen.

**To Reproduce**

1. Set video decoder as SMP
2. Play a game

**Expected behavior**

TV won't go screen saver mode as long as stream is active.

**Basic information**

 - Moonlight version: 1.5.11
 - Model: LG C1
 - webOS version: 3.9.0

> To check version, go to Settings > Quick Settings > General > About this TV > webOS TV Version

**Additional context**

I don't use gamepad paired with the TV as I've paired directly to the PC host

**Comment by Marocco2** [comment]
Works perfectly, thanks 👍

**Comment by mariotaku** [comment]
> Works perfectly, thanks 👍

Hi, did you download snapshots? The new version is not released yet.

**Comment by Marocco2** [comment]
> > Works perfectly, thanks 👍
> 
> Hi, did you download snapshots? The new version is not released yet. 

Yes, I downloaded and installed the snapshot

**Comment by mariotaku** [comment]
Glad it works for you! Because it's a build during refactor. Let me know if you see any crash.
