### ISSUE TITLE
Only draw a border around the currently focused game in the game library

### ISSUE THREAD

**Issue by submatrix** [mariotaku/moonlight-tv#26]
**Is your feature request related to a problem? Please describe.**
It is currently pretty difficult to see which game is currently in focus. I suggest only drawing the border around the game currently in focus, and possibly even making the border a brighter color so it is more visible against the dark gray background.

This is what Moonlight-qt does.

**Describe the solution you'd like**
Only see a border around the currently focused game.

**Describe alternatives you've considered**
The focused game icon becomes larger when focused, even potentially partially obscuring other game elements in the view. This is how it looks (by default for "collection views") on tvOS. 

**Additional context**

**Comment by mariotaku** [comment]
Done in v0.3.1 .
