### ISSUE TITLE
[BUG] Moonlight crashes upon connecting

### ISSUE THREAD

**Issue by vguzmanp** [mariotaku/moonlight-tv#276]
**Describe the bug**

When starting the app, it tries to connect to my PC, and requests the PIN.
Once entered, it suddenly crashes.

**To Reproduce**

1. Open the app
2. Connect to a computer
3. Enter the pin
4. The app is gone

**Expected behavior**

I expected it to not crash

**Basic information**
 - Moonlight version: 1.5.13
 - Model: LG 49NANO867NA
 - webOS version 5.4.3-36

**Additional context**
Downgrading back to 1.5.11 makes it work fine again.

I installed the app using webOS device manager, the crash report there shows:
[Gist with the crash report](https://gist.github.com/vguzmanp/fecb8d782782414629374675ad044712): https://gist.github.com/vguzmanp/fecb8d782782414629374675ad044712 .

[Second crash report](https://gist.github.com/vguzmanp/b3b186f5f5cff4e282c6180c908a9b95): https://gist.github.com/vguzmanp/b3b186f5f5cff4e282c6180c908a9b95

**Comment by mariotaku** [comment]
Hi, it looks like the crash is the same as #262. Do you have game without a cover?

**Comment by vguzmanp** [comment]
Thank you for the fast update! 
I do have a game without a cover. I'll test it out today and report back.
