### ISSUE TITLE
[COMPAT] OLED65BX3LB

### ISSUE THREAD

**Issue by inatlewski** [mariotaku/moonlight-tv#29]
# Basic information

 - Device Model: OLED65BX3LB
 - System Version: 5.2.0-250801 (update 03.21.10)
 - Is Audio Working: No
 - Is Video Working: No
 - Is Input Working: No

Additional information:
Moonlight - Release v0.3.3
TV uses Gigabit Ethernet connection.
The application starts, pairs with my computer, and lists available games.
UI and navigation work correctly.
After starting any game, the application shows "Connecting..." and PC speakers stop playing music.
5 seconds later, a black screen is shown and the Moonlight crashes.
Relaunching the application and resuming the session crashes Moonlight again.
After stopping the session, PC speakers start playing music again. 
I tested different video and audio settings, the behavior is always the same.
Streaming games from PC to iPhone and Moonlight Embedded on Raspberry Pi works correctly.

Update:
Sometimes, in low-resolution modes and with checked "Use SDL to play audio" I'm able to hear music for 2 seconds, then the TV freezes and restarts.

**Comment by mariotaku** [comment]
@inatlewski 0.6.x is out, it should work on webOS 5 TVs.

**Comment by mariotaku** [comment]
Closed as this should be working now. Feel free to open an issue if something isn't working for you.
