### ISSUE TITLE
[BUG] Moonlight doesn't switch from HDR back to SDR mid-stream if toggled on the host

### ISSUE THREAD

**Issue by Mothamoz** [mariotaku/moonlight-tv#291]
## Bug Description

I use Playnite as my only app within Moonlight, to get a 'console' like fullscreen experience. 
Playnite supports HDR toggling for PC titles that support HDR. When I launch for example Spiderman Remastered, Playnite toggles HDR on on the host and when the game exits and goes back to playnite, HDR is toggled off. 

Moonlight WebOS works fine when HDR gets toggled on, it switches from SDR to HDR midstream and I see the popup in the top-right of my TV. However, when the game exits and the host goes back to SDR, the client remains stuck in HDR mode until I quit the stream and start it as new. 

## Reproduce Steps

1. Start a stream in SDR
2. Toggle HDR on on the host while streaming, HDR mode will be started on the client
3. Then go ahead and turn HDR off on the host, the host goes back to SDR but the client will remain stuck in HDR, verifiable in my case by checking which image preset is active on the client, which is 'HDR Game'

## Expected Behavior

I expect Moonlight to switch the image preset back to SDR when the host gets switched back to SDR mode. Currently the client remains stuck in HDR, making content look weird (because its using the HDR preset while the host is in SDR mode) and it only gets fixed when restarting the stream.

---

## Basic Information
- Moonlight 1.5.17
- WebOS NDL video/audio
- 1440p 120fps stream, 65mb bitrate
- Connected to ethernet
- Sunshine on the host

**Comment by Mothamoz** [comment]
@mariotaku i see you've made a commit, should i try a recent snapshot to see if it works?

**Comment by mariotaku** [comment]
@Mothamoz There's no successful build yet. You could try the snapshots if the checks turns green.

**Comment by Mothamoz** [comment]
I'm not sure where to look for the checks but I'll keep my eyes open, thanks mariotaku

**Comment by Mothamoz** [comment]
@mariotaku just tried the latest snapshot, works perfectly!

**Comment by mariotaku** [comment]
It will be added in the next release.
