### ISSUE TITLE
Incorrect work dualshock 3

### ISSUE THREAD

**Issue by WADPH** [mariotaku/moonlight-tv#293]
## Bug Description
I use Moonlight on my tv using a playstation 3 controller. The first time I connected the controller, it started working in the game. But strangely it didn't work in the moonlight menu 
The second time the gamepad was not detected both in the game and in the moonlight menu I thought for a long time how to fix this, downloaded old versions of moonlight but nothing helped me. The gamepad still didn't work. Then he started working again, very strange, but it happens by itself, then the gamepad works, then it doesn’t work  If someone's gamepad is completely working, it works fine on my PC without problems 

It used to work sometimes, but now I can’t connect my gamepad for 2 days, it won’t connect 

![16909938374412210046439853447864](https://github.com/mariotaku/moonlight-tv/assets/75982625/c5e87802-23d4-4282-889c-2d4cb7b94b61)

**Comment by mariotaku** [comment]
This issue might get fixed in future versions after #270 implemented.
