### ISSUE TITLE
Add the ability to set custom ports to access the host

### ISSUE THREAD

**Issue by OmikroN-TNS** [mariotaku/moonlight-tv#294]
Hello there, I'm trying to connect to a host that has default ports closed and the only way to access it is by forwarding to different ports. The Moonlight macOS client allows to input the computer address followed by the port you want to use to connect (that I've already set on Sunshine host app) but I can't find a way to do it on my LG TV client.

So I'm here because I would like to be able to set custom ports when adding a new host to the moonlight client. Could it be possible? Or is it already possible and I'm missing how to do it?

Thanks

**Comment by mariotaku** [comment]
moonlight-tv uses fixed port at this moment. I'll add ability to use other ports in future versions.

**Comment by Emanuads** [comment]
Thanks, that would be great!

**Comment by mariotaku** [comment]
This feature is in progress now! It should be available in a few days.
