### ISSUE TITLE
[COMPAT] 55NANO916NA

### ISSUE THREAD

**Issue by xatornet** [mariotaku/moonlight-tv#30]
# Basic information

 - Device Model: 55NANO916NA
 - System Version: 5.2.1
 - Is Audio Working: Yes
 - Is Video Working: Yes (with HW acceleration since v0.6.0)
 - Is Input Working: Partially* (see below)

UPDATE 2: new version 0.6.0 has working HW Acceleration!!
![photo_2021-04-08_13-48-37](https://user-images.githubusercontent.com/43992639/114021728-4a49a980-9871-11eb-828e-ccd0188a9c8d.jpg)

It works great with the stock bitrate, if I go anything more than 50Mbps, Moonlight crashes.
 
UPDATE: new version 0.5.2 works!!!
![photo_2021-03-21_20-05-30](https://user-images.githubusercontent.com/43992639/111917557-df326180-8a80-11eb-91b0-8c9bc21059f6.jpg)

It also works and pairs succesfully, although I'm warned that there's no HW decoding available:
![photo_2021-03-21_20-04-45 (2)](https://user-images.githubusercontent.com/43992639/111917571-f3765e80-8a80-11eb-8480-5b83c99411d3.jpg)

And, as warned, anything above 720p gets absolutely slow and stutters a lot. I'm using LAN, not wireless, but I guess this is the best the TV can handle without HW decoding:
![photo_2021-03-21_20-04-45](https://user-images.githubusercontent.com/43992639/111917603-2587c080-8a81-11eb-8f49-436788ba5a0b.jpg)

Anyway, this is a big improvement!! I'm so happy to see this working!! Keep up the good work! :-)

**INPUT TEST:
Mouse works as intended both in-app and in-stream. Could not test Xbox One controller, i'll give it a go as soon as possible.

**Comment by xatornet** [comment]
It's sadly still not working on version 0.43 :-(

**Comment by mariotaku** [comment]
I think that's related to webOS 5. I'm still working on decoding video in webOS 5, please stay tuned!

**Comment by xatornet** [comment]
Great to know. Also, awesome work. I'll keep trying each new release :-)

**Comment by xatornet** [comment]
Updated results with new version v0.5.2

**Comment by mariotaku** [comment]
Hardware accelerated streaming is here, feel free to try out.

**Comment by xatornet** [comment]
> Hardware accelerated streaming is here, feel free to try out.

Tried it and updated the post. Works great now. There are still some caveats, but it is working great. 

There's no codec selection, and pairing works although I get a "error pairing" at the end of it. But works fine. Also, I cannot get to any bitrate higher than 50Mbps or the app crashes and closes itself.

Other than those small issues, it works great at 60fps. Great work!!! Thanks for your time and effort :-)

**Comment by mariotaku** [comment]
Thanks for reporting! I'll be closing good compatibility reports, feel free to open if you encounter problems.
