### ISSUE TITLE
[COMPAT] MAGIC-S PRO 2 + DualShock 4 no longer works

### ISSUE THREAD

**Issue by francoisvdv** [mariotaku/moonlight-tv#309]
## Basic information
 - Device model: LG OLED55C8PLA
 - Firmware version: 05.50.15
 - webOS version: 4.4.0
 - Moonlight version: 1.5.20
 - Is audio working: Yes
 - Is video working: Yes
 - Is input working: Remote yes, Gamepad (MAGIC-S PRO 2 + DualShock 4) no

## Description
Hi,

I recently updated from Moonlight version 1.5.3 to 1.5.20 and since then my Gamepad does not work anymore. I put the MAGIC-S PRO 2 in XPAD mode, as suggested in the wiki. The DualShock 4 connects, but no inputs are registered through Steam Big Picture mode.

Downgrading to 1.5.17 also did not help. Unsure where the issue actually started.

Should you need any (debug?) information please let me know.

**Comment by mariotaku** [comment]
@francoisvdv Hi, Moonlight uses new input driver since v1.5.17. I'm currently solving the issue on webOS 4 and below and you'll get an update to fix this soon.

**Comment by francoisvdv** [comment]
Hi, Thanks for your reply, looking forward to the fix! 😄

**Comment by domizi** [comment]
@mariotaku Hi, could this be the same for xbox 360 wired controller, because it doesn't get input registered on the moonlight even though it works on WebOS?

**Comment by mariotaku** [comment]
@domizi I haven't get a chance to test 360 controllers, but Xbox One controller works.

**Comment by francoisvdv** [comment]
Hi @mariotaku Awesome, indeed fixed for me in v1.6.1. Thanks for your great work!
