### ISSUE TITLE
[COMPAT] Crashing on webOS 1~3

### ISSUE THREAD

**Issue by KeepeR22rus** [mariotaku/moonlight-tv#310]
Hello, moonlight on my LG TV webOS 1.4.0-2341  05.06.10 not loading. I see only logo moonlight. Is this OS supported?

**Comment by mariotaku** [comment]
Hi, do you see it crash? You'll see the screen go blank and quit to TV/HDMI.

**Comment by KeepeR22rus** [comment]
> Hi, do you see it crash? You'll see the screen go blank and quit to TV/HDMI.

After startup, the moonlight logo appears, I see it for 2 minutes, after which the screen returns to TV

**Comment by mariotaku** [comment]
Thanks. In this case I think it needs some debugging. Would you mind giving me remote access? We can discuss with discord.

**Comment by RoelZ** [comment]
I experiencing the same issue. App logo pops in and after a few seconds the TV redirects itself to HDMI 1.

I'm running Web OS 5.70.30 on a UH650T

Sadly I don't think I can share a remote session. But feel free if you think otherwise @mariotaku

**Comment by mariotaku** [comment]
After some investigations (thanks to @KeepeR22rus 's info), there are some incompatibilities with v1.5.20 for webOS 1.x to 3.x now. I'm solving this issue now.

**Comment by mariotaku** [comment]
Thanks to your info and assistance, a new release [v1.5.21](https://github.com/mariotaku/moonlight-tv/releases/tag/v1.5.21) is available for testing. Please give it a try.

**Comment by KeepeR22rus** [comment]
> Thanks to your info and assistance, a new release [v1.5.21](https://github.com/mariotaku/moonlight-tv/releases/tag/v1.5.21) is available for testing. Please give it a try.

Hi, I installed v1.5.21, but I still only see the logo.

**Comment by SilverTongue248** [comment]
I had the same issue of hanging on the logo screen, but when I tried installing v1.5.21 it said "Luna call returned negative response: Unable to exec luna-send-pub: Error: Failed to call getIDs"

**Comment by mariotaku** [comment]
Hi @KeepeR22rus @SilverTongue248 , I have made another update, and can confirm it worked on the emulator. Please try if they work for your real TVs.

**Comment by SilverTongue248** [comment]
It is the com.limelight.webos_1.5.20_arm.ipk file im supposed to install right? Because I still get the Failed to call getIDs

**Comment by mariotaku** [comment]
@SilverTongue248 It's a pre-release so you can't install from updates list. As for the errors with `getIDs`, it is an issue of webOS Homebrew channel app (and devs are working on it: https://github.com/webosbrew/webos-homebrew-channel/pull/152) . You can use [dev-manager-desktop](https://github.com/webosbrew/dev-manager-desktop/) instead to install manually at this moment.

**Comment by SilverTongue248** [comment]
Ok, yeah it seems it's an issue with installing anything however I have been using the dev manager and getting the error.

**Comment by SilverTongue248** [comment]
Ahh ok, I uninstalled the Homebrew Channel and it let me install now. Must've been interfering with dev manager. Will test update now.

**Comment by KeepeR22rus** [comment]
Hello, I installed ipk from v1.5.22 pre-release, and application is working!!!

**Comment by mariotaku** [comment]
@KeepeR22rus Great! After some more testing I'll close this issue.

**Comment by SilverTongue248** [comment]
Seems to open fine, didn't hang or crash however It can't create the directory because it doesn't have permissions, I tried creating a file through the dev manager terminal but same missing permissions.

**Comment by mariotaku** [comment]
Closing as the crashing issue is now solved. Please see #317 for "permission denied" issue.
