### ISSUE TITLE
[COMPAT]

### ISSUE THREAD

**Issue by arturfariasv** [mariotaku/moonlight-tv#311]
## Basic information

 - Device model: (    43UF7700   ) 
 - Firmware version: (     04.06.25  ) 
 - webOS version: (   2.2.0    ) 
 - Moonlight version: (     1.5.20  ) 
 - Is audio working: (       ) 
 - Is video working: (       ) 
 - Is input working: (       ) 

## Description
I can’t open moonlight.

I installed the moonlight using the webOS Dev Manager and as soon as I opened the moonlight it appears for 2 sec and crashes and goes back to HDMI/TV

**Comment by mariotaku** [comment]
Hi, this is an known issue #310 . I'm working on a fix now.

**Comment by mariotaku** [comment]
Hi! A new pre-release is out to fix this issue. Please give it a try.
