### ISSUE TITLE
Unable to have audio from computer and shield at the same time

### ISSUE THREAD

**Issue by 89jd** [mariotaku/moonlight-tv#319]
## Bug Description
Cannot change audio from Nvidia hdmi out will automatically revert back

## Expected Behavior

Audio source changes to selected, ideally will come from both

## Basic Information

GFE. Latest moonlight on lg G2

**Comment by mariotaku** [comment]
To get audio from both computer and TV, turn off "Mute computer while streaming" in host settings.
