### ISSUE TITLE
AV1 Decoder Video Not Smooth

### ISSUE THREAD

**Issue by trottdeaje** [mariotaku/moonlight-tv#329]
## Bug Description
 When using the AV1 Decoder the visuals do not appear to be smooth.  
  
[Link to AV1 Video](https://streamable.com/lsmqso) 
[Link to H265 Video](https://streamable.com/5tnpj4) 

When turning the camera, objects in the AV1 video appear to be trailing behind slightly, whereas the h265 video, objects are consistent

## Reproduce Steps

1. Under Video settings in moonlight tick checkbox for **Use AV1 if possible**
2. Start Stream

## Expected Behavior

I expect for the AV1 Decoder stream to be smooth as with the H265 decoder.

---

## Basic Information

 - Moonlight Info in Settings - About:
Version: 1.5.26
Video decoder: ndl-webos5
Audio backend: ndl-webos5
System: webOS 7.3.1 (HE_DTV_W22O_AFABATAA)
Screen resolution: 3840* 2160
Refresh rate: 120FPS

 - Are you using GFE or Sunshine? If so, what's the version?

 I compiled the latest Sunshine version: 0.20.0.7166d2f.dirty

## Additional Context
System Specs:
RTX 4080 16GB
Windows 11

**Comment by mariotaku** [comment]
Moonlight doesn't decode video by itself, instead it feeds the video directly into the TV's hardware.
AV1 is very new to webOS TVs too. And their hardware might not be strong enough to decode like they handle H265/H264.


I would suggest lowering bitrate/framerate/resolution to see if it helps. If you really want the best performance and the highest present available, use H265/H264 instead.

**Comment by kentyman23** [comment]
More discussion in #336.
