### ISSUE TITLE
[COMPAT] OLED55CXPUA

### ISSUE THREAD

**Issue by mykol64** [mariotaku/moonlight-tv#33]
# Basic information

 - Device Model: OLED55CXPUA
 - System Version: 5.2.0-290904
 - Is Audio Working: N/A
 - Is Video Working: N/A
 - Is Input Working: N/A

The app initially works great and connects to my host PC without issue. 
The app immediately crashes upon selecting a game, although it does launch the selected game on the host PC.
The app also sometimes crashes while scrolling.

**Comment by exalented** [comment]
This might be because we're running webos 5.x . Mario has stated that work still needs to be done REing the new versions https://github.com/mariotaku/moonlight-tv/issues/32#issuecomment-777961472

**Comment by mariotaku** [comment]
New version is out, might worth trying.

**Comment by mariotaku** [comment]
Closing now. Feel free to open a new one if there're something not working.
