### ISSUE TITLE
[COMPAT] - Xbox Series X controller does not work

### ISSUE THREAD

**Issue by domizi** [mariotaku/moonlight-tv#333]
- Device model: LG OLED55CX6LA
 - Firmware version: 04.41.45
 - webOS version: webOS 5.4.3
 - Moonlight version: 1.6.0
 - Is input working: **No.** Xbox Series X controller with MAGIC-S PRO 2 (Set to the green input - Xinput)

For some reason the controller does not work once I launch anything through Moonlight-TV app on WebOS.
It works in WebOS. It works in Moonlight app. However no input is registered once I launch Steam or any game through Moonlight-TV.
I tried ALL Magic-S PRO 2 input modes. I tried with cable and wireless, same result.
What could be wrong?

In the Wiki it shows that this controller and dongle combo should be working.
![image](https://github.com/mariotaku/moonlight-tv/assets/6929535/e40be35e-8b20-42e6-b57c-a29f8031d314)

**Comment by mariotaku** [comment]
Looks like moonlight didn't report number of gamepads properly. I'll look into this.

**Comment by domizi** [comment]
Unfortunately I am still not able to use my Xbox Series X controller with Magic-S PRO 2 adapter... :(

**Comment by mariotaku** [comment]
Do you have the latest firmware of the adapter and the gamepad? Both can be updated with official manuals.

**Comment by mariotaku** [comment]
Also, please try streaming with other devices like your phone to see if gamepad input works.
If you can't get input with other clients either, then the issue happens on the computer.

**Comment by domizi** [comment]
After doing a clean install of Windows 11, both Xbox Series X (with Magic-S PRO 2) and Xbox 360 controller (with cable) now work! Thanks!
