### ISSUE TITLE
AV1 has video ghosting/stuttering/choppiness

### ISSUE THREAD

**Issue by kentyman23** [mariotaku/moonlight-tv#336]
## Bug Description
When I try to use AV1, I get very choppy video that stutters and has a ghosting effect. I don't have this problem with HEVC/H.265. Bitrate setting doesn't seem to affect it. Decode time is between 0.07-0.25 ms but usually around 0.15 ms. I have attached a screenshot, but please see this slow-motion video to witness it in action: https://photos.app.goo.gl/feZ3hw5AVJgt1Hd57

## Reproduce Steps
1. Enable AV1 on Moonlight.
2. Play Starfield.

## Expected Behavior
Smooth video like I get with HEVC/H.265.

---

## Basic Information

TV: LG C2 65
Moonlight: 1.6.1
Sunshine: 0.21.0
Resolution: 1440p
Bitrate: Any (5K, 35K, 65K)
GPU: RTX 4070
CPU 5600X

## Additional Context

None.

![PXL_20231021_150801900_exported_27424](https://github.com/mariotaku/moonlight-tv/assets/33491334/4c77ad5d-fe58-4104-8b17-811caf04db8f)

**Comment by mariotaku** [comment]
Hi, thanks for the report. AV1 is highly experimental, and probably not having the best performance compared to HEVC/H264. I'll add some notes about performance when someone selects AV1.

**Comment by kentyman23** [comment]
Thanks for the quick reply. I knew it was experimental so didn't expect it to be perfect, but I thought I'd still file this in case the stuttering and ghosting was indeed a bug that needs fixing, specifically on webOS. Any idea if Moonlight Android, for example, has this problem?

**Comment by mariotaku** [comment]
I'm not sure about other platforms, but on webOS rendering the video was solely done by the TV, instead of client app. So if there are video related issues, it considered a compatibility issue instead of a bug. I'll keep track of this issue though, to see if there are any common pattern in the future.

**Comment by kentyman23** [comment]
I tried out an AV1 MKV in Kodi 20.90.801, installed through webOS Dev Manager, and it played perfectly on my TV. Is this maybe because Kodi uses FFmpeg behind the scenes?

**Comment by mariotaku** [comment]
Live game streaming and media file playback can have different behavior. I can't tell the specific reason (because there's no information provided), but it's likely that AV1 isn't for streaming for current generation models.
