### ISSUE TITLE
[COMPAT] Extended input not working with 8BitDo v1 adapter and DS4

### ISSUE THREAD

**Issue by stek29** [mariotaku/moonlight-tv#337]
## Basic information
 - Device model: 
 - Firmware version: 05.20.08
 - webOS version: webOS 4.9.0
 - Moonlight version: 1.6.1
 - Is audio working: Yes
 - Is video working: Yes, 1080p60 (haven’t tried other options)
 - Is input working: not completely
 - Sunshine version: nightly 0.21.0.5b052d7c2c059aa26fdf79cc87885af2f461f544
 - Controller: DS4

## Description
Extended input (Gyroscope/Accelerometer/LEDs) works fine when DS4 is plugged into TV via USB
But it doesn’t work via 8BitDo v1 adapter

I’ve used [Game Controller Tester](https://powgames.itch.io/game-controller-tester) for testing it.

**Comment by mariotaku** [comment]
Did you try connecting the adapter to the PC directly and see if it supports gyro? I saw some posts complaining about 8bitdo adapter doesn't properly handle gyro at all.

**Comment by stek29** [comment]
looks like it only supports motion controls in "switch mode" according to their compatibility chart

https://download.8bitdo.com/Manual/Receiver/usb_adapter/8Bitdo_USB_RR_FOR_PS_Manual.pdf
https://support.8bitdo.com/Manual/USB_Adapter/ps4_switch.html

and judging by this line in the dmesg, it was set to PC mode:
```
input: Microsoft X-Box 360 pad as /devices/platform/usb/18050000.xhci_top/usb1/1-2/1-2:1.0/input/input7
```
and it does indeed work with Nintendo switch.

I've tried switching it to Switch mode, and now I see this in dmesg:
```
[Fri Nov  3 02:38:04 2023] (3)-2557	usb 1-2: new full-speed USB device number 7 using xhci-hcd
[Fri Nov  3 02:38:04 2023] (3)-2557	input: Nintendo Co., Ltd. Pro Controller as /devices/platform/usb/18050000.xhci_top/usb1/1-2/1-2:1.0/0003:057E:2009.0003/input/input11
[Fri Nov  3 02:38:04 2023] (3)-2557	hid-generic 0003:057E:2009.0003: input,hidraw0: USB HID v1.11 Joystick [Nintendo Co., Ltd. Pro Controller] on usb-18050000.xhci_top-2/input0
[Fri Nov  3 02:38:09 2023] (3)-2557	usb 1-2: USB disconnect, device number 7
[Fri Nov  3 02:38:09 2023] (3)-2557	usb 1-2: new full-speed USB device number 8 using xhci-hcd
[Fri Nov  3 02:38:09 2023] (3)-2557	input: Microsoft X-Box 360 pad as /devices/platform/usb/18050000.xhci_top/usb1/1-2/1-2:1.0/input/input12
```

so it seems like it switches back to "PC mode" automatically from the "Switch mode" after 5 seconds for some reason -- I guess it has some auto detection to guess that it's actually plugged into Nintendo Switch.

I'll try to look further into it, but I guess there's not much moonlight-tv can do here :(

**Comment by stek29** [comment]
Ok, so first thing I needed to do to get it working in Switch mode and stop switching to other modes it to get it updated to latest firmware.

I had a PS Classic adapter (since it was in stock when I was buying it, unlike the "normal" one) -- so I had to flash it manually and "convert" it into a normal one.
I've used [this guide](https://ladis.cloud/blog/posts/firmware-update-8bitdo.html), and just got the latest firmware for the classic adapter: 6a446a08-d6d2-40ca-b57b-14ade2f25d23.dat.

Now when I switch it to the Switch mode by holding Share+L1 it stays in Switch mode, and SDL based GameConTest on windows detects it as a Switch Pro controller with all the inputs (including motion controls) working.

Obviously webOS kernel is too old to have hid_nintendo in-tree, I wonder if it'd be possible to build it for it out-of-tree.

**Comment by stek29** [comment]
I was able to get extended input working, including the gyroscope, in the Switch Pro mode.
There are some caveats, though:
- L2/R2 turn into digital buttons instead of analog buttons (since that's what Switch Pro controller has)
- the rumble works in "mono" -- L and R rumbles work the same
- the kernel module crashes the OS when the adapter is unplugged -- there's 

Hardware:
- 8BitDo PS Classic, flashed into 8BitDo USB Wireless Adapter v1 manually, firmware 6a446a08-d6d2-40ca-b57b-14ade2f25d23.dat (Firmware v2.05)
- Sony DualShock 4 controller
- LG webOS 4.9.0 TV (50UM7300, k5lp)

Software:
- Moonlight TV 1.6.1
- some nightly dev build of Sunshine, too lazy to look it up & doesn't matter

Here's what I had to do:
1) build hid-nx.so module from sources, load it on the TV
2) add udev rules to remap the controller & start udevd since webOS doesn't seem to have it started by default
3) switch 8bitdo adapter into Switch Pro mode by holding Share+L1

Patch for [hid-nx](https://github.com/emilyst/hid-nx-dkms.git) (applied on top of e0d36613969b51564e1e5a48c82d40314abf97c7)
```
diff --git a/Makefile b/Makefile
index 293ff75..da2ea1e 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 obj-m += hid-nx.o
 
-KERNEL_RELEASE := $(shell uname -r)
-KDIR           := /lib/modules/$(KERNEL_RELEASE)/build
+KERNEL_RELEASE := 4.4.84-p.568.gympie.k5lp.1
+KDIR           := ../linux_pop
 
 OBJ_FILE       := $(obj-m)
 SRC_FILE       := $(OBJ_FILE:.o=.c)
diff --git a/hid-nx.c b/hid-nx.c
index 122e331..1a83dfd 100644
--- a/hid-nx.c
+++ b/hid-nx.c
@@ -40,6 +40,11 @@
 #include <linux/power_supply.h>
 #include <linux/spinlock.h>
 
+// not yet moved into hid.h on older kernels
+#define to_hid_device(pdev) container_of(pdev, struct hid_device, dev)
+// not available on this kernel
+#define LED_HW_PLUGGABLE 0
+
 /*
  * Reference the url below for the following HID report defines:
  * https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering
@@ -331,28 +336,30 @@ struct nx_con_imu_cal {
 	s16 scale[3];
 };
 
-static const u32 NX_CON_BTN_Y		= BIT(0);
-static const u32 NX_CON_BTN_X		= BIT(1);
-static const u32 NX_CON_BTN_B		= BIT(2);
-static const u32 NX_CON_BTN_A		= BIT(3);
-static const u32 NX_CON_BTN_SR_R	= BIT(4);
-static const u32 NX_CON_BTN_SL_R	= BIT(5);
-static const u32 NX_CON_BTN_R		= BIT(6);
-static const u32 NX_CON_BTN_ZR		= BIT(7);
-static const u32 NX_CON_BTN_MINUS	= BIT(8);
-static const u32 NX_CON_BTN_PLUS	= BIT(9);
-static const u32 NX_CON_BTN_RSTICK	= BIT(10);
-static const u32 NX_CON_BTN_LSTICK	= BIT(11);
-static const u32 NX_CON_BTN_HOME	= BIT(12);
-static const u32 NX_CON_BTN_CAP		= BIT(13);
-static const u32 NX_CON_BTN_DOWN	= BIT(16);
-static const u32 NX_CON_BTN_UP		= BIT(17);
-static const u32 NX_CON_BTN_RIGHT	= BIT(18);
-static const u32 NX_CON_BTN_LEFT	= BIT(19);
-static const u32 NX_CON_BTN_SR_L	= BIT(20);
-static const u32 NX_CON_BTN_SL_L	= BIT(21);
-static const u32 NX_CON_BTN_L		= BIT(22);
-static const u32 NX_CON_BTN_ZL		= BIT(23);
+// gcc in toolchain is too old for static const tricks,
+// use plain old define's instead
+#define NX_CON_BTN_Y		BIT(0)
+#define NX_CON_BTN_X		BIT(1)
+#define NX_CON_BTN_B		BIT(2)
+#define NX_CON_BTN_A		BIT(3)
+#define NX_CON_BTN_SR_R	BIT(4)
+#define NX_CON_BTN_SL_R	BIT(5)
+#define NX_CON_BTN_R		BIT(6)
+#define NX_CON_BTN_ZR		BIT(7)
+#define NX_CON_BTN_MINUS	BIT(8)
+#define NX_CON_BTN_PLUS	BIT(9)
+#define NX_CON_BTN_RSTICK	BIT(10)
+#define NX_CON_BTN_LSTICK	BIT(11)
+#define NX_CON_BTN_HOME	BIT(12)
+#define NX_CON_BTN_CAP		BIT(13)
+#define NX_CON_BTN_DOWN	BIT(16)
+#define NX_CON_BTN_UP		BIT(17)
+#define NX_CON_BTN_RIGHT	BIT(18)
+#define NX_CON_BTN_LEFT	BIT(19)
+#define NX_CON_BTN_SR_L	BIT(20)
+#define NX_CON_BTN_SL_L	BIT(21)
+#define NX_CON_BTN_L		BIT(22)
+#define NX_CON_BTN_ZL		BIT(23)
 
 struct nx_con_button_mapping {
 	u32 code;
@@ -2195,7 +2202,7 @@ static int nx_con_leds_create(struct nx_con *con)
 		led->name = name;
 		led->brightness = ((i + 1) <= input_num) ? 1 : 0;
 		led->max_brightness = 1;
-		led->brightness_set_blocking = nx_con_player_led_brightness_set;
+		led->brightness_set_sync = nx_con_player_led_brightness_set;
 		led->flags = LED_CORE_SUSPENDRESUME | LED_HW_PLUGGABLE;
 
 		if ((ret = devm_led_classdev_register(&hdev->dev, led))) {
@@ -2224,9 +2231,14 @@ static int nx_con_leds_create(struct nx_con *con)
 		led->name = name;
 		led->brightness = 0;
 		led->max_brightness = 0xF;
-		led->brightness_set_blocking = nx_con_home_led_brightness_set;
+		led->brightness_set_sync = nx_con_home_led_brightness_set;
 		led->flags = LED_CORE_SUSPENDRESUME | LED_HW_PLUGGABLE;
 
+		// it fails to register home led with 8BitDo Adapter,
+		// and later it tried unregistering the home led, which
+		// leads to null dereference oops
+		return 0;
+
 		if ((ret = devm_led_classdev_register(&hdev->dev, led))) {
 			hid_err(hdev, "Failed registering home led\n");
 			return ret;
```

and here's the udev rule -- I've only included Pro Controller DEVICE_ID, but it can have all the ids the hid-nx supports:
```
ACTION=="add", KERNEL=="0003:057E:2009.*", SUBSYSTEM=="hid", \
RUN+="/bin/bash -c 'echo $kernel > /sys/bus/hid/drivers/hid-generic/unbind'", \
RUN+="/bin/bash -c 'echo $kernel > /sys/bus/hid/drivers/nx/bind'"
```

here's the list of HID VENDOR_ID/DEVICE_IDs that hid-nx supports:
https://github.com/emilyst/hid-nx-dkms/blob/e0d36613969b51564e1e5a48c82d40314abf97c7/hid-nx.c#L2671-L2685

I'm using following file to load custom kernel modules at boot:
```
#!/bin/sh
# /var/lib/webosbrew/init.d/20-insmod-kernel-drivers

driver_dir="/media/kernel-drivers"
if [ ! -d "${driver_dir}" ]; then
  echo "${driver_dir} does not exist"
  exit 0
fi

cd "${driver_dir}"

for mod in *.ko; do
  echo "loading ${mod}"
  insmod "${driver_dir}/${mod}"
  exit_code="$?"
  if [ "${exit_code}" != 0 -a "${exit_code}" != "17" ]; then
    echo "failed to load ${mod}: exit code ${exit_code}"
    exit "${exit_code}"
  fi
done
```

I have custom built hid-nx.ko at /media/kernel-drivers
(and I'm also using it to load `ftdi_sio.ko` from https://github.com/throwaway96/webos-kernel-drivers for Hyperion over Serial, that's why I have a separate init.d file for the kernel modules)

And here's a script I use for udevd rules
```
#!/bin/sh
# /var/lib/webosbrew/init.d/30-start-udevd
set -e

rules_d="/media/udev-rules.d/"

if [ ! -d "${rules_d}" ]; then
  echo "${rules_d} does not exist, not starting udevd"
  exit 0
fi

killall udevd || :
mount --bind "${rules_d}" /etc/udev/rules.d/
udevd --daemon
```

I've prepared the /media/udevd-rules.d like this:
```
cp -R /etc/udev/rules.d /media/
cat >/media/udev-rules.d/99-udev-nx.rules <<EOF
ACTION=="add", KERNEL=="0003:057E:2009.*", SUBSYSTEM=="hid", \\
RUN+="/bin/bash -c 'echo $kernel > /sys/bus/hid/drivers/hid-generic/unbind'", \\
RUN+="/bin/bash -c 'echo $kernel > /sys/bus/hid/drivers/nx/bind'"
EOF
```

I'll also try to build hid_nintendo if I have some free time to see if it also crashes kernel on unplugging.
Also, sometimes hid-nx does fail to detect and probe the 8bitdo, but that seems like the 8bitdo's issue, I'm still looking into it.

**Comment by mariotaku** [comment]
Very awesome discovery! I did notice that many gamepads can't be used on webOS 4.

**Comment by stek29** [comment]
btw, I've also tried connecting DS4 directly over bluetooth -- webOS 4 won't allow to do it via UI, but you can do it via luna-send, there's a guide in Russian here: https://webos-forums.ru/post146837.html
However I've found that it has a very high lag and low refresh rate -- so it's not worth it.

**Comment by stek29** [comment]
I guess the issue can be closed -- I've got it working on my TV, and there was nothing wrong with moonlight-tv -- it was about the adapter and the webOS.
