### ISSUE TITLE
Variable Refresh Rate (VRR)

### ISSUE THREAD

**Issue by woiza** [mariotaku/moonlight-tv#339]
Is VRR supported on LG C1 or later using AV1 or H265?

**Comment by mariotaku** [comment]
Generally the TV only cares about maximum frame rate, and renders the video right after it receives one. I'm not sure about the exact definition of VRR, does this behavior match what you're describing?

**Comment by woiza** [comment]
Let’s say I am playing a demanding game and the framerate varies between 80 and 120fps. Using a freesync/gsync monitor, the framerate and refresh rate / hz will always match. What happens in this case when using sunshine/gamestream and moonlight on webos? Will sunshine encode variable fps and will moonlight decode variable fps? Will moonlight adjust the TV‘s / panels refreshrate to accommodate the varying fps?

**Comment by mariotaku** [comment]
Everything I'm describing is based on observation: Sunshine will send video frame upon screen update. So I suppose it supports VRR. You probably need to ask its developers for more info.
And what moonlight-tv does is just feeding video frames to the TV so it doesn't control panel framerate. I'd suggest you to run this test to see if it works: https://www.testufo.com/vrr .

**Comment by woiza** [comment]
Understood, will do. Thank you for your help!
