### ISSUE TITLE
Gamepad not working 

### ISSUE THREAD

**Issue by Cocv0077** [mariotaku/moonlight-tv#340]
## Bug Description

When I connect my Bluetooth controller to LG C3 Tv it gets connected perfectly, it even works normally on moonlight app, but when I run any game the controller stops working, while win 10 pc shows 3 xbox controller devices connected, on further investigation I found that out of those 3 instance one controller is providing inputs when testing via "Advanced Game controller" setting in windows 10

This is only happening after latest update which contained gamepad detection fix, I used to play normally with same controller and same tv & PC

I think old non working instances of controller are getting in the way

## Reproduce Steps

1. Connect controller to tv and start playing game 
2. You will find no inputs getting registered on windows server pc

## Expected Behavior

Gamepad should give proper inputs and also only one virtual device should get connected to windows server PC 
---

## Basic Information

 v1.6.1

 - Moonlight Info in Settings - About:
 - Are you using GFE or Sunshine? If so, what's the version?

## Additional Context

Please reply back if you need any other info
This is my first time reporting a bug on GitHub, so please bear with me if I have reported incorrectly or missed something

**Comment by mariotaku** [comment]
Hello! Could you test the gamepad on this website? https://hardwaretester.com/gamepad

And are you using GFE or Sunshine?

**Comment by mariotaku** [comment]
Yeah. It looks like there are some issues with GFE while sunshine is doing fine. Does it show 3 controllers on the tester website too?

**Comment by Cocv0077** [comment]
No it doesn't show 3 controllers on website

Btw it's WORKING now

I deleted the device from tv and re paired it.
Also restarted the host pc and forgeted every virtual device

And bam it started working again and now it doesn't show 3 virtual device when connecting via moonlight

Seems like some kind of data clash or corruption

**Comment by mariotaku** [comment]
Update: I'm able to reproduce 3 controllers issue too and it's only present on webOS (not on raspberry pi)

**Comment by Cocv0077** [comment]
Alright
But today it got resolved don't know how

Were you able to conclude the reason behind this issue?

**Comment by mariotaku** [comment]
On webOS TVs, 2 virtual devices got registered as gamepad too. I'll filter out those devices so only real gamepads will be recognized.
