### ISSUE TITLE
App crashes when using pro controller

### ISSUE THREAD

**Issue by julio-vaz** [mariotaku/moonlight-tv#343]
## Bug Description
If I try to open the app while having a pro controller, such as the 8bitdo ultimate Bluetooth connected, it does not start, getting stuck in the moonlight logo.

The app also crashes if I connect the controller after I have opened it.

This doesn't used to happen before the update, unfortunately I do not know how to rollback the app.

## Reproduce Steps
1. Connect pro controller
2. Try to open the app

## Expected Behavior
The app should work correctly with pro controllers.

---

## Basic Information

 - Moonlight Info in Settings - about:

App version 1.6.2
WebOS version: 5.5.0
Ndl-webos5
4k
120fps

 - Are you using GFE or Sunshine? If so, what's the version?

Sunshine 0.21

**Comment by mariotaku** [comment]
Hi, could you collect the crash logs by using dev-manager-desktop?

**Comment by julio-vaz** [comment]
Hello, @mariotaku! Thank you for the prompt response.

As the app appears to be stuck on the Moonlight logo, it doesn't seem to be a crash, as the dev-manager-desktop doesn't display any crash reports. It seems more like a "loop" or some condition that makes the app stuck. Here's a print of the crash report folder:

![image](https://github.com/mariotaku/moonlight-tv/assets/8976358/7b335a6a-fb2f-4f85-b079-2bd6c28640ea)

The "Debug" tab in the app is also blank.

Does moonlight-tv generate logs? If so, in what folder? /var/log is empty for my tv. Here's a print:
![image](https://github.com/mariotaku/moonlight-tv/assets/8976358/3099c67f-52c8-499f-89ce-641e0050ee32)

**Comment by julio-vaz** [comment]
Only if it's a bluetooth gamepad that is recognized by LG WebOS as a "pro controller" (Nintendo Switch based controller). If I use a XBOX series or XBOX one controller, connected via bluetooth, the app runs completely fine.

**Comment by mariotaku** [comment]
Thanks for the info. I happen to have a pro controller and a webOS 5 TV. I'll try to reproduce.

**Comment by mariotaku** [comment]
It looks like when the Pro Controller is connected, moonlight tries to send commands to the controller but on webOS sending to the controller won't work. In the next release I'll disable the switch controller specific driver when it is connected with Bluetooth.

**Comment by mariotaku** [comment]
Pro controller via Bluetooth has been specified to use basic drivers in recent updates, so it should have no crash now.
