### ISSUE TITLE
Gamepad sticks get stuck. (Provide Deadzone Options)

### ISSUE THREAD

**Issue by quelotic** [mariotaku/moonlight-tv#347]
## Bug Description
Both playstation 5 controller and gulikit king Kong 2 pro seem to bug very often. Sticks get stuck spinning the camera forever. Player keeps moving never stopping until I move the sticks to another direction, which sometimes just change the way the camera spins or the character moves.

## Reproduce Steps
Launch game and play.

## Expected Behavior
Sticks should center when I'm not touching them.

---

## Basic Information

 - Moonlight Info in Settings - About:
 Version 1.6.2
Audio video decoder: ndl-webos5
System: webOS 5.5.0 (HE_DTV_W20O_AFABABAA)
Screen resolution: 3840*2160
Refresh rate: 120fps

 - Are you using GFE or Sunshine? If so, what's the version?
 Using sunshine v0.22.0 on windows 11

## Additional Context

Network connection is smooth. No dropped frames. No stuttering whatsoever.

**Comment by mariotaku** [comment]
Hi, are you able to see sticky button presses too? If not, I suspect that the deadzone of your controllers caused that (doesn't mean the controller is bad).
In that case I'll suggest adjusting deadzone settings.

**Comment by quelotic** [comment]
> Hi, are you able to see sticky button presses too? If not, I suspect that the deadzone of your controllers caused that (doesn't mean the controller is bad). In that case I'll suggest adjusting deadzone settings.

Hello, how do you suggest doing that on the PS5 controller? I am aware that my king kong has some settings but I have no idea how to adjust it. It's not doing it all the time... I've spent a lot of time playing during the weekend and it happends really randomly. Losing control of the character and the camera I mean. When it does it happens for both sticks. I've been trying to figure if it happens on sticky input but it's really hard to tell but i'd say 75% it's happening on buttons. Buttons like R2 and L2 (big ones).

**Comment by mariotaku** [comment]
@quelotic You're mentioning L2/R2, which makes it even likely to be a deadzone issue, since those buttons are also analog.

Other moonlight clients support deadzone settings, I'll probably add it to this port too. 


---

Please note that I'm kinda busy in the coming few months and can't update this project very often, so anyone seeing this issue, please consider contributing by submitting a pull request :)

**Comment by mariotaku** [comment]
@quelotic Hi, please try snapshot build here: https://github.com/mariotaku/moonlight-tv/actions/runs/7158337057

It contains a configurable deadzone and the default value is 7%.

**Comment by quelotic** [comment]
Hello! I downloaded and installed right away but it doesn't seem to apply any deadzone! Set it to 20% but the sticks activate the moment I touch them!

**Comment by mariotaku** [comment]
@quelotic Could you please connect the controller on the PC and test directly?

**Comment by quelotic** [comment]
I had some time today to test it a bit more.
The option is there but it doesn't seem to apply any deadzone to the controllers. Both controllers are working properly on my PC. Even with 20 deadzone I barely touch my thumbsticks and I instantly get input.

**Comment by mariotaku** [comment]
Could you try this website and see how the sticks perform? https://hardwaretester.com/gamepad

**Comment by quelotic** [comment]
Ok after some testing, sticks perform ok on the tester:
Gulikit King Kong 2 pro gamepad has 0 deadzone and performs perfectly with no drift at all (no potenciometer - magnetic). I can apply firmware deadzone.
My 2 Playstation 5 controllers perform the same (as they should) on the tester with no drift.
- God of War (seems like the game does not provide software deadzone)
King Kong 0 deadzone lags A LOT, increased firmware deadzone performs better.
Playstation controller lags less But still lags.
- Last of Us part I (seems like the game does provide some sort of software deadzone)
King Kong 0 deadzone seems to be working ok, some lags still occur. Moving the sticks restores the functionality.
Playstation controller seems to perform the same. Very rare lags. Moving the sticks restores the functionality.
- Final Fantasy VII Remake (seems like the game does not provide software deadzone)
King Kong 0 deadzone lags A LOT, incresed firmware deadzone performs better.
Playstation controller lags less but still many lags
- Final Fantasy Stranger of Paradise (no software deadzone)
King Kong 0 deadzone lags A LOT, increased firmware deadzone performs better.
Playstation controller lags less but still a lot!

I think it is indeed the deadzone setting.
I am using the version your shared before with the deadzone settings enabled, but it seems that it's not applying any deadzone settings.

I am now available after a long period of holidays. If I knew C I would help. Trust me I tried to read what you're doing on the source but I can't understand anything!

I just noticed that you have released a couple versions while I've been missing. I will be testing those in the afternoon and will be back for further info!

**Comment by Argon2000** [comment]
Just adding my experience; I have the same issue while using a Xbox One controller connected by BT to LG TV. Have tried latest 1.6 .5 and setting deadzone to max (20%). Character keeps walking and I have to pull in other direction to stop. This controller have been working ok in the past. (Works fine connected to PC without Moonlight)

Using a Nintendo Switch Pro Controller it is working, but the input lag is unbearable.

My current best option is a Xbox 360 controller with a USB-dongle plugged into TV. No input lag and no drifting.

Thanks alot for this Moonlight version btw, I use it every day! ♥️

**Comment by mariotaku** [comment]
@Argon2000 Thanks for your experience! Did you try the gamepad tester website above? How's the drift?

**Comment by Argon2000** [comment]
@mariotaku Sorry for late response. Did not try gamepad tester. But I just updated to 1.6.9 (from 1.6.5) and the issue seems to be resolved for me 🎉
