### ISSUE TITLE
Micro-stutter when streaming

### ISSUE THREAD

**Issue by NanKillBro** [mariotaku/moonlight-tv#353]
### Moonlight Version

1.6.2

### Device Type

webOS TV

### Device Model

43NANO76SQA

### Device OS

webOS 7.3.1

### Host OS

Windows

### Host Software

GeForce Experience

### Host Setup

Intel Core i5 12500H, RTX 3050, Windows 11 Pro
TV is connect via 5ghz wifi and PC is connect via LAN (1.0 Gbps full duplex)

### Bug Description

Experiencing micro-stuttering when streaming game
Here's a quick video that I record my problem: https://youtu.be/KdvZ09lODBQ
*sorry if i made any grammar mistake, i'm not good at English :D

### Reproduction Steps

1. Open Moonlight
2. Streaming any game

### Expected Behavior

Streaming without any micro-stutter

**Comment by mariotaku** [comment]
Hi, you may have noticed there's a huge packet loss (~20%), did you try lower bitrate, or connecting through WiFi?

**Comment by NanKillBro** [comment]
I have tried to lower bitrate like 5000kbps with 720p@30 and both also connected 5ghz wifi but the problem still there, i also have tried using h264 or change decoder to webos smp and it still didn't work

**Comment by mariotaku** [comment]
This might be related to https://github.com/moonlight-stream/moonlight-android/issues/79 too. Did you try the workaround mentioned?

**Comment by NanKillBro** [comment]
I just tried using the method you mentioned (changing 1.0 Gbps full duplex to 100Mbps full duplex) but it still doesn't work
I also tried streaming to my phone and it works perfectly fine

**Comment by mariotaku** [comment]
Thanks for your info. Could you try pinging your TV from the computer?

**Comment by NanKillBro** [comment]
Ping while TV is idle:
![Screenshot 2024-01-07 081300](https://github.com/mariotaku/moonlight-tv/assets/72297072/92fe45a0-3621-4b22-9f1b-26861fbb4cb0)
Ping while pc is streaming to the TV:
![Screenshot 2024-01-07 081856](https://github.com/mariotaku/moonlight-tv/assets/72297072/2295f18b-dbe1-419f-8d54-1c1ae36cf67a)

**Comment by mariotaku** [comment]
This shows a very bad packet drop. If everything works as intended, the pings should be always at around 2ms when idle. Assuming you're now connecting via 5ghz wifi, what's your channel? In Vietnam, channels 32-48, 149-165 might be better as they're not affected by DFS.

https://en.m.wikipedia.org/wiki/List_of_WLAN_channels

**Comment by NanKillBro** [comment]
After I changed my channel from Auto (100) to 36, it now worked perfectly without any stutter. Thanks you very much!
