### ISSUE TITLE
Doubled Gamepad Input After Recent Firmware Update (webOS 23 Models)

### ISSUE THREAD

**Issue by FluffyCake** [mariotaku/moonlight-tv#356]
### Moonlight Version

1.6.2

### Device Type

webOS TV

### Device Model

LG C3 65 Inch

### Device OS

03.30.60

### Host OS

Windows

### Host Software

Sunshine

### Bug Description

Prefacing that I was connecting a newly purchased Xbox Controller and PS5 DualSense via direct tv bluetooth connection.

I am getting a lot of double inputs while in steam. It also seems like the Xbox/PS button now forcibly returns to the webOS home instead of opening the Steam home. 

I'm thinking the recent LG webOS update adjusted how gamepad support works via bluetooth. 

Previous bluetooth functionality with Xbox Gamepad and PS5 DualSense no longer works. 

I cannot be sure which webOS version I was on previously. 

I am also not sure if it can be changed on the software end by Moonlight. 

Ordering the MayFlash adapter to see if it will be a more consistent workaround.

Asking around if anyone else is seeing these issues.

### Expected Behavior

Functionality previously was perfect just using the native bluetooth gamepad connection.

**Comment by aakister** [comment]
I'm experiencing what seems to be the same issue, also on an lg c3. Was working perfectly before, then a new update came through tonight.

Now my Xbox controller works to control all applications (netflix, jellyfin, etc) where it would previously only control moonlight. Input in moonlight seems to be doubled.

**Comment by mariotaku** [comment]
@aakister This is rather interesting. A relatively good change on the webOS side but I'll need to take a look to prevent doubled input.

**Comment by mariotaku** [comment]
TBH webOS has pretty terrible support for gamepads connected via Bluetooth. An adapter or USB connection is always preferred, as it provides better support for gyro/trackpad etc.

**Comment by mrrouge** [comment]
The same issue here too. Thanks for looking into it.

**Comment by FlavioCJMarco** [comment]
Same here. It was working fine, then webOS update dropped and the controller started controlling the volume, both inside and outside Moonlight, making it pretty hard to manage. Thanks for the quick response :)

**Comment by Fasolina** [comment]
Same here. 
Been playing on a LG C3 65 Inch TV for a few months and everything worked perfectly with my Xbox Series X gamepad directly connected to the TV via bluetooth. 

Than after the TV updated today the controller can now controll the TV( rigth stick raise/lowers the volume, start button opens the menu etc.) 
Gameing is not possible with this.
Would be appriciated if something could be done about that.

**Comment by mariotaku** [comment]
Oh no. This indeed renders gamepads usable. I'll see the way to properly use gamepads exclusively!

**Comment by mariotaku** [comment]
Could you please share your firmware version BTW? My TV might not have this feature so I'll have to reproduce it first.

**Comment by aakister** [comment]
My C3 is running:

Software version: 03.30.60
webOS TV Version: 8.3.0-13 (number1-nameri)

**Comment by mrrouge** [comment]
It seems that a new update is rolling out: 03.30.70

**Comment by FluffyCake** [comment]
The MayFlash adapter came in. 

I'm using the Magic S Pro 2.

Unfortunately I am seeing that the issue seems to be affecting the way the control scheme works regardless of method used.

> TBH webOS has pretty terrible support for gamepads connected via Bluetooth. An adapter or USB connection is always preferred, as it provides better support for gyro/trackpad etc.

Even with the adapter the same double input behavior happens. 

I am also concerned that the Xbox/PS buttons still forcibly sends me to the WebOS Home.

This occurs whether it's wired or wireless, regardless of if I use the adapter or not.

Has anyone else able to reproduce the same issues while using an adapter?

**Comment by Fasolina** [comment]
Yeah organized a MayFlash Magic S Pro 2 Adapter too.

Same behaviour as when connecting the controller directly to the tv when pressing a button it now controlls the functions of the tv e.g rigth stick now controlls the audio volume.

Happens with the green mode(Xinput) other modes dont work at all

**Comment by wesraph** [comment]
Same problem here with a PS5 controller, broke after the webos update

**Comment by mariotaku** [comment]
> Same problem here with a PS5 controller, broke after the webos update

Do you happen to know the firmware version before and after?

**Comment by wesraph** [comment]
I don't know about the version before but the current versions are:
Firmware: 03.30.60
WebOS version: 8.3.0

**Comment by rvller** [comment]
+1 for bug, even it seems that bug is related to LG tv fw itself…
I dont know the previous version, but current is:
Firmware: 03.30.60
WebOS version: 8.3.0

**Comment by mariotaku** [comment]
Hi! You may want to try this snapshot: https://github.com/mariotaku/moonlight-tv/actions/runs/7520079078
I have discovered something might be linked to this behavior and made some changes

**Comment by Fasolina** [comment]
After a quick test of the new version seems to be working again.
Controller works as intended when running Moonlight.
Will updated when I had the time to test it for longer.

But for now it seems that the fix you implemented does work

Thank you

**Comment by aakister** [comment]
Similar experience, I could only interrupt Paw Patrol long enough for a short test, but everything seemed to function as expected with #357. I'll do some more extensive testing tonight.

Thank you for taking a look at this issue so quickly!

**Comment by FallingSnow** [comment]
> Same here. It was working fine, then webOS update dropped and the controller started controlling the volume, both inside and outside Moonlight, making it pretty hard to manage. Thanks for the quick response :)

Oh thank God. I thought this was just me. Whenever I press right trigger on my PS5 controller the volume goes up. I also get button presses not registering.

**Comment by FallingSnow** [comment]
Latest snapshot seems to have resolved my issues.

**Comment by aakister** [comment]
I was able to play a co-op game session for about an hour with no unexpected behavior; as far as I can tell that change is a winner.

**Comment by FluffyCake** [comment]
Thank you so much for the quick and timely fix. I really appreciate it! @mariotaku

**Comment by mrrouge** [comment]
Working... thanks!!!
