### ISSUE TITLE
Gyro controls not working anymore on 1.6.4

### ISSUE THREAD

**Issue by Mothamoz** [mariotaku/moonlight-tv#358]
### Moonlight Version

1.6.4

### Device Type

webOS TV

### Device Model

LG CX

### Device OS

webOS 5.5.0

### Host OS

Windows

### Host Software

Sunshine

### Host Setup

i7-13700k, NVIDIA RTX 4070Ti, 32GB DDR4-4400

### Bug Description

After the latest moonlight update my DS4 controllers do not pass through gyro anymore. I tested this by opening Yuzu through my client's moonlight and configuring controls, the gyro isn't picked up at all.
The controller however is recognized correctly as a DualShock 4.

I've also closed down the stream and restarted it multiple times to no avail.

### Reproduction Steps

Start a stream using a DS4 or (probably) any other gyro supported controller and you'll see the gyro does not work.

### Expected Behavior

Gyro controls to be passed through and working correctly.

**Comment by mariotaku** [comment]
I have tested v1.6.4 with Aimlabs and other apps, and gyro works. How did you connect the gamepad?

**Comment by Mothamoz** [comment]
They are connected through bluetooth, directly to the TV. I will do some more troubleshooting and testing later today and report back

**Comment by mariotaku** [comment]
Actually, I didn't expect the PS4 controller to have a working gyro via Bluetooth at all. What about USB connection?

**Comment by Mothamoz** [comment]
> Actually, I didn't expect the PS4 controller to have a working gyro via Bluetooth at all. What about USB connection?

It worked perfectly ever since you implemented gyro support :) Besides it being apparently broken for me now

I'll try a USB connection but I'd rather not have that be a permanent solution due to distance from the TV & couch, and bluetooth working fine before

**Comment by mariotaku** [comment]
I know USB connection is less than ideal, but because bluetooth support on webOS is so inconsistent, I'd suggest using a dongle instead. On my TV, it's not possible to test such feature at all, so I'm not able to fix if webOS breaks it.

**Comment by Mothamoz** [comment]
I tried a magicflash ultimate but the controller limit to 2 plus the usage was annoying, i'll do some troubleshooting this evening and report back. Hopefully we can find out what changed between 1.6.4 and 1.6.2 that makes it not work

**Comment by Mothamoz** [comment]
Nice! Let me know when or if I should test a build or something else!

**Comment by mariotaku** [comment]
https://github.com/mariotaku/moonlight-tv/actions/runs/7551192089
Does this work for you? Switch Pro Controller can't work via Bluetooth without that patch, so I made it only for Nintendo devices.
Do you have a Switch controller to test out?

**Comment by Mothamoz** [comment]
> https://github.com/mariotaku/moonlight-tv/actions/runs/7551192089
> Does this work for you? Switch Pro Controller can't work via Bluetooth without that patch, so I made it only for Nintendo devices.
> Do you have a Switch controller to test out?

Unfortunately I don't, only have ds4's laying around

**Comment by mariotaku** [comment]
@Mothamoz I bought a DualShock 4 controller and tested. Looks like the fix works well. I'll make another release with some other fixes.
