### ISSUE TITLE
Generate SHA256 client certificate

### ISSUE THREAD

**Issue by cgutman** [mariotaku/moonlight-tv#36]
I noticed that https://github.com/mariotaku/moonlight-tv/commit/4f674cfa716893a3c1812ee54af7af17c859f116 switched from creating a SHA256 client certificate with OpenSSL to a SHA1 client certificate with mbedTLS. SHA1 certificates are deprecated almost everywhere, so it would be a good idea to generate a SHA256 client certificate, especially because these certificates will be long-lived and require re-pairing with all host PCs to rotate.

Official Moonlight clients have been generating SHA256 certificates since mid-2019 when Debian Buster's specially configured OpenSSL package started blocking SHA1 certificates. I believe OpenSSL 3.0 will default to blocking SHA1 across the board, so SHA1 client certificates in the field are likely to break when Nvidia updates to OpenSSL 3.0 (once it's released, of course).

**Comment by mariotaku** [comment]
Thank you. I must be copied bad example code from somewhere. I'll change this ASAP.
