### ISSUE TITLE
Description of how to enable virtual mouse using game pad

### ISSUE THREAD

**Issue by KlosiakMK** [mariotaku/moonlight-tv#365]
### Description

Hi,

I just wanted to provide my feedback regarding description which can be found in the menu when it comes to how to enable Virtual Mouse using gamepad controller.

It says now: "Press LB + RT to move mouse cursor with sticks" and this was not true for my Xbox Series controller connected to TV via BT. I was pressing LB + RT and nothing happen but found that when I pressed LB + RS then it worked. I don't know whether it is specific only for this controller but LB + RT suggests to use LB + Right Trigger button on the pad and in my case I had to press LB and Rights Stick to enable Virtual Mouse feature.

I think that "LB + RT" should be updated to "LB + RS" to not confuse users...if this is the case for all Xbox type controllers.

Cheers! 

### Motivation

To not confuse users who connect their Xbox type controllers to be used with the client.

**Comment by mariotaku** [comment]
Thanks for the feedback! This is a typo and I'll update all the strings to avoid confusing users.

**Comment by KlosiakMK** [comment]
Thanks!
