### ISSUE TITLE
Numpad 5 and Pause/Break does not work

### ISSUE THREAD

**Issue by FallingSnow** [mariotaku/moonlight-tv#366]
### Moonlight Version

1.6.5

### Device Type

webOS TV

### Device Model

LG C3

### Device OS

webOS 8.3.0-13

### Host OS

Windows

### Host Software

Sunshine

### Host Setup

Intel 13600K, Nvidia P40

### Bug Description

Numpad key 5 does not register. The number row 5 does work though.

### Reproduction Steps

Try to press numpad 5 while typing.

**Comment by mariotaku** [comment]
Hi, my keyboard doesn't have numpads so I didn't notice. Would you mind checking if other keys are working?

**Comment by FallingSnow** [comment]
![image](https://github.com/mariotaku/moonlight-tv/assets/2512197/325f329c-e280-4f95-9939-ce3a21e580a0)

Keys in white do not register except for the enter on the numpad, which registers as enter on the center of the keyboard (as apposed to the expect numpad enter).

**Comment by mariotaku** [comment]
@FallingSnow thanks! I can also observe missing pause key and win key (because webOS maps it as home button), but can't reproduce #368 #367

**Comment by mariotaku** [comment]
OK after trying on Android client, I noticed that pause key is not working either. Do you have such device to give it a try too? It's possible that Sunshine isn't handling those keys properly.

**Comment by FallingSnow** [comment]
![image](https://github.com/mariotaku/moonlight-tv/assets/2512197/e44519b7-ee40-4867-ac86-f00f3b1985fd)

It seems to register as CTRL RIGHT. In the picture above, I pressed scroll lock to test, then pause/break 2 times, then right ctrl 2 times, then pause/break once... followed by me taking a screenshot.

**Comment by FallingSnow** [comment]
Oh and I forgot to mention, that we me using a raspberry pi with moonlight-qt so I guess this is a moonlight-common/sunshine issue?

**Comment by mariotaku** [comment]
Yes. I think this is a sunshine issue.
