### ISSUE TITLE
[COMPAT] 49UM7000PLA 

### ISSUE THREAD

**Issue by SSchott** [mariotaku/moonlight-tv#37]
# Basic information

 - Device Model: 49UM7000PLA 
 - System Version: 5.00.15
 - Is Audio Working: yes
 - Is Video Working: yes [720p]
 - Is Input Working: TV Remote yes/Gamepad not tested

Using ethernet connection, and runs very smoothly. Thanks for the effort. Hope there is a way to keep it installed soon.

**Comment by mariotaku** [comment]
Thanks for reporting! I'll be closing good compatibility reports, feel free to open if you encounter problems.
