### ISSUE TITLE
Increase of decode time

### ISSUE THREAD

**Issue by caioavidal** [mariotaku/moonlight-tv#370]
### Moonlight Version

1.6.5

### Device Type

webOS TV

### Device Model

LG 55UM761C0SB

### Device OS

webOS 4.10.0

### Host OS

Windows

### Host Software

GeForce Experience

### Host Setup

12th Gen Intel(R) Core(TM) i5-12600KF - 32,0 GB DDR4
RTX 2060 Super

### Bug Description

Decode time increased from version 1.6.2. The decoder time used to be less than 1ms and now it is around 30 to 40ms.
Tried all versions after 1.6.2 (including 1.6.2) and all look the same. Version 1.6.1 looks good though.

**Comment by mariotaku** [comment]
Starting from recent versions, I have discovered a way to get relatively accurate decode time. 1ms was time to send video frames to the TV, while 30~40ms is time to really display the frame.
