### ISSUE TITLE
WebOS - Touchscreen support

### ISSUE THREAD

**Issue by lmsilva** [mariotaku/moonlight-tv#374]
### Description

I have a LG StandbyMe 27", which has touchscreen controls, but the Moonlight client does not support them.
It seems to only work with the tv's remote and bluetooth gamepads - which is great, don't get me wrong, but I was really hoping to be able to use the touchscreen on the WebOS device as a mouse controller.

I have some popcap casual touchscreen games I want to stream from my PC and, unfortunately, I can't.

p.s. GREAT JOB on the moonlight client - works excellent!

### Motivation

It would be useful for those of us with LG WebOS touchscreen capable devices.

### Additional Context

I am using LG StandbyMe 27":

**Comment by lmsilva** [comment]
I have root on my tv so I can alpha / beta test anything you need me to. Thank you!

**Comment by mariotaku** [comment]
@lmsilva Does this build work for you? https://github.com/mariotaku/moonlight-tv/actions/runs/8061656908

**Comment by lmsilva** [comment]
Thank you, @mariotaku . How do I deploy a build outside of homebrew? I have ssh / telnet access but I've only deployed builds through homebrew so far.

**Comment by mariotaku** [comment]
There are multiple ways and the easiest one would be using https://github.com/webosbrew/dev-manager-desktop/ .

The package can be found in "Artifacts" section, where the file name starts with `webos-snapshot-`.

**Comment by lmsilva** [comment]
@mariotaku , "it works!" :) 
check this video I recorded for you:
https://www.youtube.com/watch?v=twIxL9agdXs

When I leave it with the default of "absolute mouse mode", it seems to work perfectly!
If I toggle it off, it makes the mouse work as a touchpad and I do have some trouble moving / touching / lifting the screen (watch video for more details) but, for the most part, you nailed it!!!

I am having another issue with the mouse movement when I launch my 800x600 game and go into fullscreen mode BUT I think that is an unrelated issue (as I had the same problem with connecting to Sunshine using Moonlight on my iPhone) - so I think it is a sunshine "streaming issue" related to "dynamic resolution changes".

Having said that, you did it - it is working pretty sweet! Let me know if you want me to do some more testing on the "touchpad" (absolute mouse mode deactivated) mode!

p.s. I'm going to put in a request with IHSPlay to add touchscreen support too, as I think you'll be able to easily do the same for it and that should resolve my "streaming 800x600 touchscreen games" ;)
