### ISSUE TITLE
Failed to Create GS_Client Error Message

### ISSUE THREAD

**Issue by ggkk15** [mariotaku/moonlight-tv#377]
### Moonlight Version

1.6.5

### Device Type

webOS TV

### Device Model

UN85 LG

### Device OS

4.50.53

### Host OS

None

### Host Software

None

### Bug Description

When installing Moonlight TV through the webOS Dev Manager I get the following error message and restarts the app.

FATAL ERROR
Failed to create GS_Client: Failed to parse certificate: X509 - The date tag or value is invalid

### Reproduction Steps

1. Launch Moonlight
2. Reach Error Message

**Comment by mariotaku** [comment]
Hi, did you try reinstall the app?

**Comment by dantewyj** [comment]
same error here, reinstall via webOS Dev Manager and still not work

**Comment by mariotaku** [comment]
Can you navigate to `/media/developer/apps/usr/palm/applications/com.limelight.webos/conf/key/`, and share `client.pem` here? It should not contain any sensitive information, so don't have to be worried.

**Comment by mariotaku** [comment]
BTW do you have the same TV model or firmware? @dantewyj

**Comment by dantewyj** [comment]
-----BEGIN CERTIFICATE-----
MIICvzCCAaegAwIBAQIBATANBgkqhkiG9w0BAQsFADAjMSEwHwYDVQQDDBhOVklE
SUEgR2FtZVN0cmVhbSBDbGllbnQwHhcNMjQwMjI5MDIxMzE5WhcNMzQwMjI5MDIx
MzE5WjAjMSEwHwYDVQQDDBhOVklESUEgR2FtZVN0cmVhbSBDbGllbnQwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDgEsz9SJEPh/HTa1JFczPwHdxRrlit
PnYlzxzDNWzpyVRqzL7ADKt1lecdb0RfjhL4OAwSiod6YhUkAaaQce4BzAZnA+9k
JDSmZ//Ro6JNSNXS0kU9a1j26Tvy0fdJOBPMxLHQe2gd6z1/nQ3rBFWQjopEe+b0
tdbFP8H8VgWE0cnEin+tIlJBXCnSrOUAzPEcd/89vib/OJ0QtG1mqQfUW4klbcYF
iE1VuZqn9e/gggTZXTZ8NBVtW2So7R/4ASbkYfI2n0JhFSZTlyBbuaHxNUf8S9+J
KWsrm5OyhVI76VAEqT687mBVQUD+wpuv+HI+2FV9aKtWX8mSXjSVdpo/AgMBAAEw
DQYJKoZIhvcNAQELBQADggEBALDVEoZ5mBe73f+NxaBDAWJFXYetZ75ZNaTwFIev
P3rMwxaG3w7iV5SGvwCMqhMYLvuC3v2BP8glI2Q8OuMSDXsnXxXabjJbDX/NG1IM
KhsPXOIpJle6q6Ns2NNPKAhdn4rEFIu1KyE5lBrjv14F+gQWSgSmh16RpgRusEql
eq2k2ZH+pDnp8g2EMKoeam+q4QvPG/LQ8kHLbbt6T27CIlu/vvxU4ei8Ty/Mgz6C
WXdPxMwYf8TZn9jxI1N5qs0JCb1GkjnnFcJEZ6Cd2ik59aucykC/zC3IKrUX8Oll
sCR3ve8a5LOWuv8OYGz104XNlNmtvqETNooew0ymVIqtWOo=
-----END CERTIFICATE-----

and my TV model is LG OLED 55 C2

**Comment by mariotaku** [comment]
@dantewyj Thanks. The cert actually looks fine. What about the TV's clock settings?

**Comment by dantewyj** [comment]
@mariotaku thanks for your kind help, TV's clock setting is set to auto, and as i checked, it's correct

pretty strange that i can open Moonlight this morning (before/around Feb 29, 10am, GMT+8), but somehow now it show this error

**Comment by mariotaku** [comment]
@dantewyj This is rather strange, after you reinstall the app, did you notice that `client.pem` has been updated?

**Comment by dantewyj** [comment]
@mariotaku yes will be updated each time i reinstall, and i run the decoder, the valid date range will start from my new reinstall timestamp

**Comment by dantewyj** [comment]
@mariotaku i just uninstall the sunshine host in my pc, not TV moonlight no error...(not even pair them lol)

**Comment by mariotaku** [comment]
I can reproduce on my TV now, looks like it's something with cert/key generation.
