### ISSUE TITLE
[COMPAT] OLED55C9PLA

### ISSUE THREAD

**Issue by admird** [mariotaku/moonlight-tv#38]
# Basic information

 - Device Model: OLED55C9PLA
 - System Version: 4.9.0
 - Is Audio Working: Yes
 - Is Video Working: Yes, 1080p 60fps, 4K60fps
 - Is Input Working: Magic remote working, XBOX 360 Wireless dongle + Wireless gamepad working

Ethernet connection used. Works great.

**Comment by mariotaku** [comment]
Thanks for reporting! I'll be closing good compatibility reports, feel free to open if you encounter problems.
