### ISSUE TITLE
Horrible latency with SMP (500ms). NetCast and NDL work fine (25ms) on B7 OLED.

### ISSUE THREAD

**Issue by Artasdmc** [mariotaku/moonlight-tv#387]
### Moonlight Version

1.6.9

### Device Type

webOS TV

### Device Model

LG B7 UK

### Device OS

WebOs 3.6.10

### Host OS

Windows

### Host Software

GeForce Experience

### Host Setup

5800X Lc, 2070 Super Lc, 3600mhz ddr4, nvme ssd.

### Bug Description

I can't stream any HDR content through Moonlight. Latency is impossible to play with, the other 2 video formats (h264) are working flawlessly, but when it comes to H265 it is at 500ms. This is with 4K/60Hz at 100mbits. And no matter what I do, it doesn't really budge. I changed resolution to 720p/30 at 5mbits and it is still at over 300ms.

TV supports VP9, H265, and I don't think it's software based?

Because this is a 120HZ 4K panel, I thought I can get away without losing colour detail by using moonlight. As this TV is only HDMI 2.0b, so I can't really do 4K at 10bits of colour, but SMP streaming has unplayable latency. Is this something that can be resolved? Or something like VP9 could be added as an option at some point?

**Comment by mariotaku** [comment]
SMP can only be considered as an alternative when NDL and NetCast doesn't work.

**Comment by Artasdmc** [comment]
So there's no way I'm getting HDR stream on this TV?

**Comment by mariotaku** [comment]
SMP is a hit or miss. I'm afraid there's no other ways to stream HDR on old TVs, if SMP doesn't work well.
