### ISSUE TITLE
Webos 6 support

### ISSUE THREAD

**Issue by robinvalk** [mariotaku/moonlight-tv#39]
**Is your feature request related to a problem? Please describe.**
I saw in the comments of #32 that you're working on supporting version 5. Do you think version 6 will be much different? I've read somewhere that the biggest difference is the UI for that release. But we don't know if the internals had a major overhaul ofcourse.

**Describe the solution you'd like**
I would love to see support for the 2021 models. Personally I've bought a 55C1 model and would love to play games on there using moonlight 😁 

**Describe alternatives you've considered**
N/A

**Additional context**
The TV has been sitting in a box here for a couple of weeks (still moving) but when I have it set up I can help out testing if you want. Maybe provide some logs / filedumps etc.

**Comment by robinvalk** [comment]
Hi again, so I've installed the app on the TV now. It starts up and it does discover my PC in the list. When I connect to it I do get a pair dialog on my PC where I fill in the code. All good so far 🤞!

Sometimes I get a pairing failure, sometimes I don't. Even after the pairing failure, if I close the app and reopen it again, I see my games listed. After clicking on a game I see the windows screen showing up for a short amout of time. When it actually boots the game it disconnects from my PC. If I try to choose a game again I get the following error: Stage 3, Error code 552

After this failure it does not recover again. Even so, if I restart the app, I have to repair with my PC all over again.

**Comment by mariotaku** [comment]
Hi, and thanks for trying out! Did you tried [streaming desktop only](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-moonlight-to-stream-your-entire-desktop)? Are you using HDR for streaming?

**Comment by robinvalk** [comment]
I'll try streaming the desktop only in the next couple of days.

I do know I did not have HDR enabled in the settings. Although I did see some HDR labels on the game posters. But I don't know if that's normal, even with the setting disabled.

**Comment by mariotaku** [comment]
Issue might relevant: https://github.com/moonlight-stream/moonlight-android/issues/590
Another thing worth notice is [this message](https://discord.com/channels/352065098472488960/746259367791427636/828975800191025182)

> Moonlight is not yet compatible with the GeForce Experience 3.22.0.88 Beta update that was released today. Streaming will fail with a 500 error at the RTSP handshake stage of the connection.
>
> You should avoid enabling the "experimental features" checkbox in GFE (which will opt you into the beta) until Moonlight is updated. 
> 
> If you've already updated to GeForce Experience 3.22.0.88, uninstall GeForce Experience and install the latest official release from https://www.nvidia.com/en-us/geforce/geforce-experience/
> 
> There are some fairly extensive changes, but we're working on updating Moonlight.

**Comment by robinvalk** [comment]
Actually my bad... As I moved my network setting in windows was set to the "public network" setting. And the firewall blocked all incoming traffic. Changed it to private network now 😂 

The pairing actually succeed and it now lists the games. The UI came in a state were I couldn't click on anything using the remote, but a restart of the TV fixed that. The desktop stream and games are working now! But the performance is terrible. 

Using the back button on the remote I saw in the stats that I have a network frame drop of ± 95%. Does this have to do anything with hardware acceleration, my network or what could it be? I don't think my network should be the problem here though. Is there any logging feature that could help analysing this?

**Comment by mariotaku** [comment]
You can find your system version, decoder used and your system capability in Settings -> About. Also keep in mind that if bitrate is too high, unexpected things may happen.

**Comment by robinvalk** [comment]
Allright here are the stats:

Version: 0.6.0
Decoder: webOS SMP
webOS version: 6.0.1
Panel resolution: 3840*2160
Refresh rate: 120

Next to 4k I also tried 1440p, with the same result.
Frame drop on 4k was more like 98% and on 1440 around 94%.

**Comment by mariotaku** [comment]
Thanks. And other than frame drop, how's video submit time? Are they over 10ms?

**Comment by robinvalk** [comment]
I've installed version 6.6 and now the app crashes like others have already reported. I've tried to run the commands to get the crash reports but they don't work: 

```console
Robins-MBP-4:~ robinvalk$ ares-novacom -r "ls -l /var/log/reports/librdx" --device TV
ls: /var/log/reports/librdx: No such file or directory
ares-novacom ERR! ares-novacom: Error: Command 'ls -l /var/log/reports/librdx' exited with code=1 (signal: undefined) 
Robins-MBP-4:~ robinvalk$ ares-novacom -r "zcat /var/log/reports/librdx/*.gz" --device TV
gzip: /var/log/reports/librdx/*.gz: No such file or directory
ares-novacom ERR! ares-novacom: Error: Command 'zcat /var/log/reports/librdx/*.gz' exited with code=1 (signal: undefined) 
```

**Comment by robinvalk** [comment]
Hi again!

Version 0.6.8 works! On 1440p @ 60 it's lag free. The video submit time is around 7ms. I've tried to use 4k but I get the message that SOPS (if I remember it correctly) is not supported for this resolution.  Also the audio doesn't seem to work.

**Comment by mariotaku** [comment]
Glad to hear it works! SOPS could be turned off in Settings -> Host -> Optimize blahblah. For Audio I'll make some further modification to make it work.

**Comment by mariotaku** [comment]
Hello, after few updates, there should be option to select other audio backends - which should work for you.

**Comment by CremboC** [comment]
I've been using the latest version 0.7.10 on my LG C1 with webOS 6.0 and it works perfectly for me. No changes needed of any kind. 4k 60fps with HDR on. Latency is less than 2ms.

**Comment by mariotaku** [comment]
I think this issue can be closed. If you encounter any issue, feel free to create a new one.
