### ISSUE TITLE
NDL crashes the app

### ISSUE THREAD

**Issue by infriker** [mariotaku/moonlight-tv#392]
### Moonlight Version

1.6.9

### Device Type

webOS TV

### Device Model

49um7090pla

### Device OS

webOS 4.10.0

### Host OS

Linux

### Host Software

Sunshine

### Host Setup

OS: Linux Mint 21.3 x86_64 
CPU: AMD Ryzen 5 7600 (12) @ 6.799GH 
 GPU: AMD ATI Radeon RX 7700S/7600/76
 Memory:  31742MiB

### Bug Description

The application crashes with the selected NDL decoder. The image is shown for a second and immediately crashes. Сrash log 
[crashlog.txt](https://github.com/mariotaku/moonlight-tv/files/14657278/crashlog.txt)

### Reproduction Steps

1) Launch Moonlight
2) Open the settings
3) In video settings choose decoder NDL
4) Connect to desktop

### Expected Behavior

Seeing video output

**Comment by infriker** [comment]
Network Legacy work fine, SMP doesn't work, but it looks like SMP is a common problem

**Comment by mariotaku** [comment]
Hi, there's a pre-release v1.6.10, that tries to address the issue. Does that work for you?

**Comment by infriker** [comment]
No, the result is the same. NDL shows the image for a second and then crashes, SMP with the codec turned on is infinitely connected, crashes without the codec. I use the ALIAS sound decoder if it affects of course. attach crash logs
[crash_log_ndl.txt](https://github.com/mariotaku/moonlight-tv/files/14662399/crash_log_ndl.txt)
[crash_log_smp.txt](https://github.com/mariotaku/moonlight-tv/files/14662400/crash_log_smp.txt)

**Comment by mariotaku** [comment]
@infriker Thank you so much for testing that out. Are you able to chat via Discord? We can have a thread to test it out real-time.

**Comment by infriker** [comment]
@mariotaku Yes, I have a discord. Nickname: fenixstar_

**Comment by mariotaku** [comment]
@infriker Please join our moonlight server and find me in webos-help channel :)

https://moonlight-stream.org/discord
