### ISSUE TITLE
LG Moonlight trouble

### ISSUE THREAD

**Issue by satyrfablous** [mariotaku/moonlight-tv#395]
### Moonlight Version

1.6.9

### Device Type

webOS TV

### Device Model

LG 55UJ6309-ZA

### Device OS

webOS 3.9.2

### Host OS

Windows

### Host Software

Sunshine

### Host Setup

Ryzen 5 5600, Rtx 3070, Windows 11 Pro

### Bug Description

When i started from Moonlight a Application, then it will switch to the HDMI 2 Port and sometimes the screen go Green.

**Comment by mariotaku** [comment]
Hello, could you try https://github.com/mariotaku/moonlight-tv/releases/tag/v1.6.13 and see if it works?

**Comment by mariotaku** [comment]
Closing the issue now. If you're still seeing the issue, please reopen.
