### ISSUE TITLE
[COMPAT] OLED55BX6LB

### ISSUE THREAD

**Issue by Darwinkel** [mariotaku/moonlight-tv#40]
# Basic information

 - Device Model: OLED55BX6LB
 - System Version: 5.2.1
 - Is Audio Working: Yes
 - Is Video Working: Yes (very slow)
 - Is Input Working: Remote works, gamepad untested.

Appears to work overall, but there is no hardware acceleration. Therefore, performance is mostly bad.

**Comment by mariotaku** [comment]
Hi! Time for an update, new version introduced hardware acceleration for webOS 5 :)

**Comment by Woedenaz** [comment]
I just tried this, launching it on my LG OLED55BX and it doesn't seem to launch at all. It blinks a black screen before switching back to my initial input. I'm pretty confident I haven't done anything wrong either.

**Comment by mariotaku** [comment]
@Woedenaz Sounds like many people experiencing this. Could you try grab the crash log by this guide? https://github.com/mariotaku/moonlight-tv/wiki/Troubleshooting

**Comment by Woedenaz** [comment]
Tried the exact command you have there, `ares-novacom -r "zcat /tmp/faultmanager/crash/*.gz"`, and I get the error:
> ares-novacom ERR! ares-novacom: Error: Connection time out. please check the device IP address or port.

I tried it again with the device specified, `ares-novacom -r "zcat /tmp/faultmanager/crash/*.gz -d tv`, and I get the error:

> gzip: /tmp/faultmanager/crash/*.gz: No such file or directory
> ares-novacom ERR! ares-novacom: Error: Command 'zcat /tmp/faultmanager/crash/*.gz' exited with code=1 (signal: undefined)

Not entirely sure what I'm doing wrong and I'm not 100% sure how to connect to the tv via SFTP. I tried finding a guide but I can't seem to find anything.

**Comment by Woedenaz** [comment]
Sorry for the double post but I managed to connect via SFTP and there does not seem to be a crash file. The /tmp/ directory appears to be entirely empty.

**Comment by mariotaku** [comment]
@Woedenaz Thank you. Could you run below command to execute moonlight directly?
```
ares-novacom -r 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/media/developer/apps/usr/palm/applications/com.limelight.webos/lib;/media/developer/apps/usr/palm/applications/com.limelight.webos/moonlight'
```

**Comment by mariotaku** [comment]
Issues above should have fixed, closing it now. Feel free to open a new one.

**Comment by Woedenaz** [comment]
Apologies, I meant to reply that this does seem to be fixed now. Thank you and sorry I wasn't too much help!
