### ISSUE TITLE
Adding a computer using a ddns address.

### ISSUE THREAD

**Issue by Danger-irk** [mariotaku/moonlight-tv#401]
### Description

I would like to be able to add a computer to the client using the DDNS address. Currently this can only be done via a static IP. I know that this has been implemented in the Desktop client.

### Motivation

Static IP service from my provider is expensive. :)

**Comment by Danger-irk** [comment]
@mariotaku , hi )

Tell me, will this feature be implemented? I would like to clarify this issue. :)

**Comment by mariotaku** [comment]
Yes. I'm planning to implement this as well as #429 in the next release.

**Comment by Danger-irk** [comment]
@mariotaku , Hi, I wanted to ask when we can expect the implementation of this feature. Please don’t think I’m rushing you, it’s just that quite a lot of time has passed, and I’m starting to worry if everything is alright on your end. After all, releases used to come out more frequently.

**Comment by mariotaku** [comment]
@Danger-irk Hi, sorry for the delay of this one. Recently I become a bit slow updating moonlight-tv (too much backlogs in all aspects!)
But this one is a very simple change and I probably could finish it sooner as it's requested by a few users.

**Comment by Danger-irk** [comment]
@mariotaku 

Thank you so much for the commit.

Looking forward to the release :)
