### ISSUE TITLE
Mouse forward and back button are not registered

### ISSUE THREAD

**Issue by FallingSnow** [mariotaku/moonlight-tv#402]
### Moonlight Version

1.6.9

### Device Type

webOS TV

### Device Model

LG C3

### Device OS

webOS 8.3.0

### Host OS

Windows

### Host Software

Sunshine

### Bug Description

Mouse forward and back buttons do not make my browser go forward and back in my history. I tested this on moonlight-qt and it works as expected.

### Reproduction Steps

1. Connect a mouse with forward and back buttons.
2. Attempt to go forward and back in your browser history.
3. Notice nothing happens.

### Expected Behavior

1. Connect a mouse with forward and back buttons.
2. Attempt to go forward and back in your browser history.
3. The browser moves forward and back through the browser history.

**Comment by mariotaku** [comment]
I'm afraid this is impossible. 

Taking the Logitech mouse I have as an instance, when you connect it to the PC, the driver recognizes the side buttons, and send key combinations or special instructions to navigate forward/back. This won't happen when you connect it to a Linux device without having proper driver. To Moonlight on the TV (more specifically, events from `/dev/input/event*` or wayland),
it only sees mouse movements and ordinary buttons.

I did verification by using `evtest` tool and see nothing but movements, wheels and left/right/middle clicks.

**Comment by mariotaku** [comment]
Oh, wait. I did the test with another mouse and somehow I got extra events.

**Comment by mariotaku** [comment]
You'll see better mouse buttons support in the next release :)

**Comment by FallingSnow** [comment]
Awesome. I'm using an MX Master 3S Logitech mouse so I'll be happy to see if it works in the next release.

Thank you!

**Comment by FallingSnow** [comment]
So I updated to 1.6.16 from 1.6.13 and the hardware mouse option doesn't seem to work anymore. My mouse behavior is the same irrespective of hardware mouse being enable/disabled (very jumpy, quick, and unnatural).

From the release notes, it seems this change only just went into 1.6.16.

**Comment by FallingSnow** [comment]
I will note though, backward and forward mouse buttons do work. So I can close this issue and open a new one for the hardware mouse issue if you like?

**Comment by mariotaku** [comment]
@FallingSnow It's a new issue, so please open a new one and let's track it there (although I have found the reason and fixed it) :)

**Comment by FallingSnow** [comment]
Tested the new snapshot. It is fixed now. Thank you!
