### ISSUE TITLE
DisplayPrimaries is Having Wrong Pixel Order

### ISSUE THREAD

**Issue by mariotaku** [mariotaku/moonlight-tv#405]
### Moonlight Version

latest

### Device Type

webOS TV

### Device Model

32LX6900

### Device OS

5.2.0

### Host OS

None

### Host Software

None

### Bug Description

DisplayPrimaries is having wrong pixel order RGB while webOS accepts BGR

**Comment by Topuz** [comment]
Still broken with the latest artifact build. Let me know if I can somehow help with testing.
