### ISSUE TITLE
Tips not disappering

### ISSUE THREAD

**Issue by robsonbn** [mariotaku/moonlight-tv#410]
### Moonlight Version

1.6.13

### Device Type

webOS TV

### Device Model

LG C1

### Device OS

6.4.0

### Host OS

Windows

### Host Software

Sunshine

### Host Setup

AMD RYZEN 5800X, NVIDIA 3080TI, 32GB RAM with Windows 11 Pro

### Bug Description

The "tips" that appear when I access my computer, don't go away. They stay in the screen. That started to happen after I updated Moonlight.

![IMG_20240415_204629](https://github.com/mariotaku/moonlight-tv/assets/11152036/49b12290-4a50-4370-9ae5-1b0944eab1e6)

**Comment by bellliam** [comment]
I am also experiencing this 
![Uploading IMG20240422211310.jpg…]()

**Comment by robsonbn** [comment]
One thing I did that seems to solve is to change the language of moonlight back and forth, don't know why but eventually it solves. I'm playing normally since then.

Note: I installed moonlight in two of my TV's (CX and C1), and this issue happened in both of them.

**Comment by bellliam** [comment]
Thanks I'll give that a try

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bellliam** [comment]
I tried using a firestick 4k max instead but then I get audio lag... Problems problems everywhere lol ..

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mariotaku** [comment]
Hi, this is a bug and has been solved in the last release (it will be available shortly)

**Comment by bellliam** [comment]
That's great, thanks. Do I need to update it somehow thought WebOS Dev or do I need to re-download it?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
