### ISSUE TITLE
[BUG] Release 0.6.0 & webOS 3.8 crash on startup

### ISSUE THREAD

**Issue by Informatic** [mariotaku/moonlight-tv#42]
**Describe the bug**
moonlight-tv crashes on startup since version 0.6.0. Release 0.5.2 seems to launch fine.

**To Reproduce**
1. Install application
2. Launch from home screen
3. TV returns to last active input (app crashes)

**Expected behavior**
I would expect an app to launch properly.

**LG webOS TV (please complete the following information):**
 - Model: 43UJ6307-ZA
 - webOS version 3.8.0-61312
> To check version, go to Settings > Quick Settings > General > About this TV > webOS TV Version

**Additional context**
Log of manual start:
https://gist.github.com/Informatic/801f219ad8a348db3ec00d5c56035483

**Comment by Informatic** [comment]
Worth noting - on release 0.5.2 in Settings → System Info following values are reported:
* Panel resolution: 0 * 0
* Refresh rate: 0
* Decoder: NetCast Legacy

**Comment by mariotaku** [comment]
Just found that there are some system functions not available on webOS 3. Will do a patch about that.
