### ISSUE TITLE
Capture Meta (Windows) Key

### ISSUE THREAD

**Issue by FallingSnow** [mariotaku/moonlight-tv#423]
### Description

Is it possible to mimic the way Windows 365 under the home office app captures the Meta key?

### Motivation

Would be nice to not get sent to the LG home screen every time I hit the Meta key.

**Comment by mariotaku** [comment]
I think I figured out a way of handling that. I'll provide an option to capture the home button in future releases.

**Comment by FallingSnow** [comment]
@mariotaku You are the man! Thank you!

**Comment by FallingSnow** [comment]
I gave `v1.6.17` a try and enabled capture system keys in the settings. Unfortunately it does not seem to work on my device. Pressing the windows/meta key leaves the app and takes me back to the LG home screen.

**Comment by FallingSnow** [comment]
Okay, I ran into a very strange issue. I'm trying to figure out a unstable network issue that just appeared yesterday when all of a sudden the windows key starts working. I think "Oh wow, that's pretty cool, wonder if it started working because I repaired with the client... anyways back to figuring out this unstable network issue." But then I notice neither `Ctrl+Alt+S` nor `Ctrl+Alt+Q` are working. Then the keyboard stops working all together. Mouse still works though. -- So I decide to power off and on the TV via the remote. Once the TV is back on the keyboard still doesn't seem to be working (but there is usually a delay when starting the TV and being able to hit the start button to go to home so it may have just been that.) So I hit `Ctrl+Alt+Del` to try to hard reset the TV, which it does. Now I go back into the Moonlight app and it is exactly as it always was, windows key isn't captured and stat/quit combo work. Bummer.

I have 2 theories as to what is going on here.
1. Some kind of race condition. Maybe since my unstable network issues are causing the first frame to load slowly, or connect slowly (I see a black frame for a little before I get to 1-2 fps.) Maybe things are being initialized at different times/speeds and this results in this unexpected behavior.
2. Either the Moonlight App or WebOS messes up and starts sending all keys the client.

As a side note, I've `Ctrl+Alt+S` and `Ctrl+Alt+Q` stop working before several times, usually after long connection sessions (maybe +24 hours). I never though to check if the Windows key starts working when though break. I'll keep it in mind for next time.

**Comment by Nepoxx** [comment]
This is still happening with the latest release (1.6.36). I tried with and without capture system keys, no change, seems like WebOS considers the win key to be "home"

**Comment by dolence** [comment]
Any solution to this? I was trying to setup moonlight as some kind of RDP/VNC client to my desktop, but without the Super key it is not feasible.
Super key isn't being forwarded, it brings me to the LG Home Screen and alt grey isn't working too.

**Comment by jljean1** [comment]
I ran into this on a webOS 23 (23.23.30) TV and traced it down. On webOS 8 and later the keyboard super key is behind its own access policy (`KEYS_META`), separate from the Home key one that "Capture system keys" requests, so the TV keeps the key and opens the home screen.

#630 requests that policy as well. With it installed and "Capture system keys" on, the super key reaches the host as the Windows key on my TV.

It only applies to webOS 8 / webOS 23 and later, since that's where the policy exists. If you're still seeing this on an older webOS version, please mention which one.
