### ISSUE TITLE
Moonlight crashes as soon as I start any application.

### ISSUE THREAD

**Issue by Fuziius** [mariotaku/moonlight-tv#424]
### Moonlight Version

1.6.13

### Device Type

webOS TV

### Device Model

LG 65UK6100PLB

### Device OS

3.9.0

### Host OS

Windows

### Host Software

Sunshine

### Host Setup

Intel i7 2600k, GTX 1080Ti, 16GB DDR3 RAM, Windows 10 Pro

### Bug Description

Moonlight crashing as soon as I start any application. The game starts on the PC and I can also close the game by stopping the stream in Moonlight. The Video-Decoder Auto and the two webOS Decoder crashing instantly. NetCast Legacy Decoder sometimes works for some time. But when it works the input of my controller (connected to the TV) instantly shows on my Host PC but displays it 2 seconds later on the TV.
I had Valorant installed on my Host PC. In the FAQ it says I might need to reinstall Windows. Could that be the problem?
It would be a lot of work to set up everythign from scratch so I would like to try other solutions first if there are any.

### Reproduction Steps

1. Open Moonlight
2. Select the Host PC
3. Start any application
4. Moonlight crashes

### Expected Behavior

The stream shouldn't crash.

**Comment by mariotaku** [comment]
Hi, what is your streaming resolution?
I'm not sure if the GTX1080 could perform well, so I also would like you to share a short video about how the stream performs?

**Comment by Fuziius** [comment]
Hi, I did set the resolution in Moonlight to 2560*1440. I play all my games on an UWQHD (3440x1440) monitor and I have no issues with this GPU.
In the attached [video](https://drive.google.com/drive/folders/1EopL2-yNGBFR6IO6kn2cnhMyAYUT02JC?usp=drive_link) the stream crashes instantly. Sometimes you can see the picture of the host PC for just a blink of an eye before the stream chrashes. But that's the most.

**Comment by mariotaku** [comment]
Thanks for the info. Could you try starting with 1080p first with default bitrate?

Also, when it crashed you'll get some logs and can be viewed by the dev-manager-desktop tool. Can you collect that for me?

**Comment by mariotaku** [comment]
OK, according to my assumption, the hardware your TV has is like its successor series (k5lp), is having compatibility issues running with the NDL module.

Your GPU should be fine and it's a TV issue. Could you switch to NetCast Legacy and share the results?

**Comment by mariotaku** [comment]
Hi, could you try [this snapshot](https://github.com/mariotaku/moonlight-tv/actions/runs/8904432626) to see if it selects LGNC automatically for you?

**Comment by Fuziius** [comment]
Hi, what am I supposed to do with this?
I guess I have to download the webos-snapshot artifact? But what to do with this file?
Sorry, I have absolutely no idea what this snapshot is haha.

**Comment by mariotaku** [comment]
Yes, you can download the zip and extract the ipk inside. Then you can install it with dev-manager-desktop.

**Comment by mariotaku** [comment]
Does this mean the video works without modifying any settings? If so, we can move on to solve the input issue. If you stream with another device, does input work?

**Comment by Fuziius** [comment]
Hi, the controller works now. It was my fault sorry.
I had to remove the controller from my host PC and reconfigure it in Windows and Steam. Now it works just fine.

Thank you so much for your time and help. It's so nice that I can now enjoy my games on TV without buying something new or moving my PC.

**Comment by mariotaku** [comment]
Awesome! I will close this as all the problems in this issue have been resolved. Feel free to open a new one for other issues you see.
