### ISSUE TITLE
WebOS NDL Screen freezing bug

### ISSUE THREAD

**Issue by githubber321321** [mariotaku/moonlight-tv#426]
### Moonlight Version

1.6.16

### Device Type

webOS TV

### Device Model

LG OLED 65A1PSA

### Device OS

WebOS 6.4

### Host OS

Windows

### Host Software

Sunshine

### Host Setup

Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz   2.81 GHz
RAM 16,0 GB
Geforce 2060

### Bug Description

Choosing NDL or automatic audio backend makes the image freeze for long periods (initially I thought the mouse wasn't working).
Works normally with other audios backend.
Works normally with moonlight 1.16.3

Thanks once again for the great app!

### Reproduction Steps

1. Choose NDL or auto audio backend.
2. Stream
3. Screen is frozen for long periodic times.

### Expected Behavior

Normal screen rendering without delays.

**Comment by mariotaku** [comment]
Hi, did you try playing a YouTube video with sound while you start streaming?

**Comment by githubber321321** [comment]
> Hi, did you try playing a YouTube video with sound while you start streaming?

Hi, I did try now. It starts with screen frozen, then it speeds up and works fine after that. Thanks for workaround.

**Comment by mariotaku** [comment]
Hi, I have made a new release that doesn't need this workaround. Could you please try and tell me if they work for you?

**Comment by githubber321321** [comment]
Hi!

Thank you for your quick response!
Unfortunatelly It doesnt work...
Same issue exista with 1.6.17.


Em sex., 3 de mai. de 2024 11:18, Mariotaku ***@***.***>
escreveu:

**Comment by Matthias102** [comment]
Yeah, I have the same issue on a LG OLED65G39. Unless I start streaming with a fullscreen-app or youtube video active the screen immediatly freezes at startup.

**Comment by mariotaku** [comment]
@Matthias102 what's your setup, is it 5.1 surround or stereo, and which version did you install?

**Comment by mariotaku** [comment]
@githubber321321 I see, thanks for testing both modes! I'll try to improve the workaround so it can work for 5.1 surround too

**Comment by Matthias102** [comment]
I installed the Moonlight WebOS version 1.6.16. I haven't tried 5.1. , yet. The soundchannel is set to stereo.


Stats:
Videodecoder: ndl-webOS 5
Audiodecoder: ndl-webOS 5
LG OLED65G39
System webOS 8.3.0
Sound is passed to a single soundbar over HDMI

Videoencoder: NVENC by a RTX4080
Hostapp: Standardbuild Sunshine 0.23.1

I also run the android moonlight client on my samsung S24 Ultra and on my Firestick 4k Max (2021). Except from the HAGS-bug I don't have any issues with these client devices.

What's curious is that this freeze of the screen at the start of the stream isn't permanent. It will unfreeze as soon as there's an application that renders anything. And even if the applications stops running, the screen won't freeze again.

**Comment by githubber321321** [comment]
@Matthias102 Try the new version (1.6.17) it works fine for stereo mode.

**Comment by Matthias102** [comment]
> @Matthias102 Try the new version (1.6.17) it works fine for stereo mode. At least for me, it does.

Yes, I can confirm that. Unlike 1.6.16 it doesn't freeze with 1.6.17 in stereo mode at the start of the stream, but in 5.1 surround mode it does unless an app is actively rendering something.

**Comment by mariotaku** [comment]
Great stereo works for both of you! For the surround workaround, I was feeding 2.5ms of empty audio and I'll be trying longer sample

**Comment by Matthias102** [comment]
@mariotaku  Thank you for the update

**Comment by mariotaku** [comment]
@githubber321321 @Matthias102 Hello! I have updated to use 5ms of blank audio instead of 2.5ms. Let's see if this snapshot works for you: https://github.com/mariotaku/moonlight-tv/actions/runs/9004094962

I'll increase until it works for both of you!

**Comment by Matthias102** [comment]
@mariotaku 
I installed com.limelight.webos_1.6.17-f8cef72c_arm.ipk web OS Dev Manager. Still freezes when set to surround.

**Comment by mariotaku** [comment]
@Matthias102 Thank you so much! How about this one? 
https://github.com/mariotaku/moonlight-tv/actions/runs/9011506225
It now waits 40ms before playing

**Comment by githubber321321** [comment]
> @Matthias102 Thank you so much! How about this one? https://github.com/mariotaku/moonlight-tv/actions/runs/9011506225 It now waits 40ms before playing

Sorry for the long delay... Couldn't take the time earlier to check it out!
1- https://github.com/mariotaku/moonlight-tv/actions/runs/9004094962 
    This one didn't work for me either...

2- https://github.com/mariotaku/moonlight-tv/actions/runs/9011506225
    This one crashed a couple times, however it seems to be working fine, with no freezing whatsoever.

**Comment by mariotaku** [comment]
@githubber321321 Awesome! I think we're heading to the correct direction.

Could you please test this version again, to see if the sound works and having no crash? https://github.com/mariotaku/moonlight-tv/actions/runs/9041053555

**Comment by Matthias102** [comment]
@mariotaku I hope I am doing it the right way, but I still get a screenfreeze with com.limelight.webos_1.6.17-96b749ed_arm.ipk, when the client is set to surround.

**Comment by githubber321321** [comment]
> > @Matthias102 Thank you so much! How about this one? https://github.com/mariotaku/moonlight-tv/actions/runs/9011506225 It now waits 40ms before playing
> 
> Sorry for the long delay... Couldn't take the time earlier to check it out! 1- https://github.com/mariotaku/moonlight-tv/actions/runs/9004094962 This one didn't work for me either...
> 
> 2- https://github.com/mariotaku/moonlight-tv/actions/runs/9011506225 This one crashed a couple times, however it seems to be working fine, with no freezing whatsoever.

3- https://github.com/mariotaku/moonlight-tv/actions/runs/9041053555
This one froze too.

On a side note the app doesn't seem to crash anymore with build 2... The first couple times I ran it, it did crash on stream start. I can't reproduce it anymore.

I'm using auto for video and audio. Its setting to NDL video and audio, H265 and HDR on.

**Comment by mariotaku** [comment]
@githubber321321 @Matthias102 I'll try more different approaches, and using chat to speed things up. Would you mind finding me on Discord in Moonlight server?

**Comment by githubber321321** [comment]
> @githubber321321 @Matthias102 I'll try more different approaches, and using chat to speed things up. Would you mind finding me on Discord in Moonlight server?
Not at all. What channel should I Join. I appreciate your efforts!

**Comment by mariotaku** [comment]
I got a new snapshot, please let me know if it works for you: https://github.com/mariotaku/moonlight-tv/actions/runs/9044673457

**Comment by Matthias102** [comment]
@mariotaku
UUuhh nice, com.limelight.webos_1.6.17-a4845305_arm.ipk doesn't result in a screenfreeze on startup, when set to surround.

**Comment by francoislg** [comment]
> I got a new snapshot, please let me know if it works for you: https://github.com/mariotaku/moonlight-tv/actions/runs/9044673457

I might be a bit late, but I didn't have the issue described, it was instead frozen on boot after 1 frame was shown, then it automatically disconnected after a little while.

I can confirm that this build seems to have fixed it (no freeze so far). So I'm very glad to see this merged 😄

**Comment by mariotaku** [comment]
@francoislg Now that we have a confirmed working version, I have released v1.16.18 so everyone can get the update. Thanks for your testing :)
