### ISSUE TITLE
Ability to connect to IP with different port

### ISSUE THREAD

**Issue by Dziggify** [mariotaku/moonlight-tv#429]
### Description

I'm using [DuoStream ](https://github.com/DuoStream/Duo?tab=readme-ov-file) right now. Since it's using the same IP but different port, Moonlight WebOS can only detect one. I can manually connect by typing the IP:port, but then it replaces the first one instead of adding a new instance. 

### Motivation

For Duo users like me, I know probably it's an edge case, but it would be awesome to see both of my Sunshine host.

**Comment by Black-Seraph** [comment]
As the creator of Duo, and an LG C9 user myself, I'd love to see this come to fruition.

**Comment by mariotaku** [comment]
Hi, I have finished the investigation. Currently moonlight-tv uses the host address to check uniqueness, which isn't correct. I'll fix this to use UUID instead and include it in the next release.

**Comment by luanolivera** [comment]
> As the creator of Duo, and an LG C9 user myself, I'd love to see this come to fruition.
> 
> At the moment I just make sure my LG TV instance is set to the default port, which works given the fact that I only own a single LG TV, but I'd love to see this implemented regardless.


I'm looking into doing the same but on Tizen, which would be the default port you reffered to ?
