### ISSUE TITLE
Allow higher bitrate selection.

### ISSUE THREAD

**Issue by Artasdmc** [mariotaku/moonlight-tv#433]
### Description

I know all TVs only have shitty 100mbit ethernet ports, but this can be bypassed by using USB to Ethernet adapter to get 300mbit on usb 2.0 and 1gbit on usb 3.0 ports.

Or is the current bitrate limited by the processing?

### Motivation

Quality.

**Comment by mariotaku** [comment]
Hi, 65mbps limit is posed by media pipeline instead of NIC. 

See issue #68 and [FAQs](https://github.com/mariotaku/moonlight-tv/wiki/FAQs#can-i-have-higher-framerate-than-65mbps-on-webos) .
