### ISSUE TITLE
Stream performance overlay doesn't work when pinned

### ISSUE THREAD

**Issue by Marocco2** [mariotaku/moonlight-tv#434]
### Moonlight Version

1.6.18

### Device Type

webOS TV

### Device Model

LG C2

### Device OS

WebOS 7.4

### Host OS

Windows

### Host Software

Sunshine

### Bug Description

Info displayed on Performance stats overlays are frozen when I pin them and hid menu buttons

### Reproduction Steps

1. Start a stream
2. Open stream menu
3. Pin performance stats
4. Close menu

### Expected Behavior

I should see performance stats working when pinned

**Comment by mariotaku** [comment]
Thanks for the report! I was wondering why I saw someone's footage that the overlay has frozen.
