### ISSUE TITLE
Soft keyboard not work, doesn’t appear

### ISSUE THREAD

**Issue by JoseMarcos23** [mariotaku/moonlight-tv#435]
### Moonlight Version

1.6.18

### Device Type

webOS TV

### Device Model

LG B9

### Device OS

5.30.25

### Host OS

Windows

### Host Software

GeForce Experience

### Bug Description

I used to use an older version of moonlight (1.5.8) and when I press on the back button on the remote control, I chose the Soft keyboard option and appears a keyboard immediately that allowed me to write on the computer by click. Now when i press this button pops nothing.

Since I updated moonlight to newest version (today) no longer appears.

### Reproduction Steps

Start moonlight on webos with mstsc.

Press back button on remote control

Select Soft keyboard option

nothing happens

**Comment by Marocco2** [comment]
I can confirm this happens also on WebOS 7.4.
In my experience, it has always been unreliable: if I try to get soft keyboard twice in a row it won't ever appear anymore until I close completely moonlight

**Comment by Marocco2** [comment]
Ok, I found the culprit. Remote shouldn't be in cursor mode: After it's unengaged, you can press back and select soft keyboard using remote arrows. If it doesn't show up and you notice it's still in cursor mode, wait some seconds and press OK

**Comment by mariotaku** [comment]
Hi, there are some issues related to closing the soft keyboard, causing it can't be opened again. It will be fixed in the next release.
