### ISSUE TITLE
Support for Multiple Sunshine Instances from the Same IP Address

### ISSUE THREAD

**Issue by trottdeaje** [mariotaku/moonlight-tv#437]
### Description

Support for displaying multiple Sunshine instances from the same IP address in moonlight. Currently only shows one instance, which is either the first one it detects or the one that comes first alphabetically (I assume). This differs from the PC version of Moonlight, which correctly displays all Sunshine instances.

![moonlight-pc](https://github.com/mariotaku/moonlight-tv/assets/32769513/a6d7776f-3449-40b3-b675-19014b63fe4b)
![moonlight-tv](https://github.com/mariotaku/moonlight-tv/assets/32769513/f497a7c2-6920-4e77-abbd-6f4591e000b7)

Use case: I use a software called [Duo](https://github.com/DuoStream/Duo) that creates multiple virtual desktop instances on one PC, each running a separate instance of Sunshine which do not conflict with each other. These instances are accessible under the same IP but different ports.

### Motivation

Would make it more flexible and user-friendly when streaming games to multiple devices. Currently, when my partner and I play Baldurs Gate 3 using Duo (I'm on steam deck and she's on TV) I have to first quit sunshine from my main non-virtual desktop so that her sunshine instance shows up in moonlight-tv. Since her instance is named Kee, that is the next instance that shows up after AJ-DESKTOP. If I wanted to instead use the TV and she use the steam deck.  I'd have to go shut down her instance or rename my instance so my name comes before hers. I think you can see how this can get tedious after a while :)

### Additional Context

moonlight-tv version: **1.6.17**
TV: **LG C2** 
WebOS TV Version: **8.3.0-2301 (number1-nameri)**

Attached are screenshots of the Moonlight client on PC correctly showing all Sunshine instances (AJ-DESKTOP, Kee, Zaj) and moonlight-tv only showing one. 

Thank you for all the hard work and building this amazing port!

**Comment by trottdeaje** [comment]
Just noticed #429 🤦🏼 apologies, Feel free to close this issue and I can move everything to that thread.

**Comment by mariotaku** [comment]
I'll take a look into how moonlight handles hosts with same IP.
