### ISSUE TITLE
Segmentation fault when trying to run a game on Raspberry Pi 4

### ISSUE THREAD

**Issue by venbo-gt** [mariotaku/moonlight-tv#44]
No problems in the frontend, but when starting a game the program exits with a segmentation fault.

Steps to reproduce:
1. Open Moonlight TV.
2. Click to start or resume a game.
3. The 'Connecting' screen will be displayed briefly.
4. The program exits.

Built and tested on a Raspberry Pi 4 (2GB), in both release and debug modes.

Here's the log, not that it's got anything useful in it.

```
Decoder platform: SDL (SW codec)
INFO: Video Driver: x11
Input manager init, -1 game controller mappings loaded
Controller #0 connected, sdl_id: 0
SDL_CONTROLLERDEVICEADDED
Segmentation fault
```

**Comment by venbo-gt** [comment]
**Update**

This build was probably made with the desktop target set, instead of the pi, which might explain why it builds but doesn't launch any games.

**Comment by mariotaku** [comment]
Crashing issue should be fixed now. Decoder is now pending development. Please stay tuned to #59 .
