### ISSUE TITLE
TV's network-module is crashing

### ISSUE THREAD

**Issue by Matthias102** [mariotaku/moonlight-tv#444]
### Moonlight Version

1.6.18

### Device Type

webOS TV

### Device Model

OLED65G39LA

### Device OS

8.3.1-3607

### Host OS

Windows

### Host Software

Sunshine

### Bug Description

TV disconnects from network. TV shows that there is no cable connection. Not possible to switch wifi on.
Hardreset of router has no effect. Switching of tv has no effect. Only fix is to cut the power to the tv to restart. Network is otherwise stable for every other device.

### Reproduction Steps

This happens at completly random times and can't be reproduced.
It first happened while using moonlight, but now it also happens during streaming of the disney+-app.

### Expected Behavior

A tv with a stable network connection.
Can the network-module crash, because the data-cache is full because of moonlight?
Has anyone else had this problem?

**Comment by mariotaku** [comment]
Hi, it's unlikely that moonlight is the cause of network problem. What kind of wireless network do you have?

**Comment by Matthias102** [comment]
A wifi-6 connection by a Fritz!box 7590 AX.
But as I said the tv is connected with a network cable to that router.

Can the moonlight-app crash the TV's network module so it's not even able to search for other wifi connections and doesn't recognize the cable anymore?

Anyway I called the LG Hotline. I told them that network module is crashing during the use of disney+ and they will send a technician.

**Comment by mariotaku** [comment]
LG's TVs are having the Ethernet controller on their main board, while having the Wi-Fi module in another board. I haven't seen any problems caused by usage of Moonlight yet. But that is being said, without physical access I can't say for sure either. Let's see what does the technician say.

**Comment by Matthias102** [comment]
Hello,

a quick update: I called the technician off because I found the problem myself. It doesn't have to do anything with moonlight. The tv can't reliable deal with a 1000 Mbit connection. No issues at all after setting the network-port of the router to 100 MBit.

Thanks for your good work, mariotaku. I am still happy with your moonlight-build because I can run it without framedrops at 65 Mbit.

**Comment by mariotaku** [comment]
Glad you find out the root cause. Too bad such a powerful modern TV doesn't even have a GbE port!
