### ISSUE TITLE
Allow selection of higher bitrates

### ISSUE THREAD

**Issue by geli09** [mariotaku/moonlight-tv#445]
### Description

I would like to be able to increase the bitrate beyond the 65 mbits. 

### Motivation

Its running more than solid for me and I would love to try out even higher options and test the limits of my tv.

**Comment by mariotaku** [comment]
65mbps is the limit of your TV.

See issue #68 and [FAQs](https://github.com/mariotaku/moonlight-tv/wiki/FAQs#can-i-have-higher-framerate-than-65mbps-on-webos) .
