### ISSUE TITLE
Laggy 1080p

### ISSUE THREAD

**Issue by sher1fff** [mariotaku/moonlight-tv#448]
### Moonlight Version

1.6.18

### Device Type

webOS TV

### Device Model

LG 42LB650V

### Device OS

webOS 1.4.0

### Host OS

Windows

### Host Software

Sunshine

### Host Setup

RTX 3070
Ryzen 5 5500
Windows 11
16gb RAM

### Bug Description

The problem is that 60fps at 1080p resolution feels like 30fps, even at the lowest bitrate. Network framerate shows 60fps. In contrast, on 720p resolution this problem does not occur 60fps feels like 60fps.

**Comment by mariotaku** [comment]
Hi, LB65 is very old. This might be the cause.
