### ISSUE TITLE
Moonlight TV failing to stream on LG TV

### ISSUE THREAD

**Issue by Otakian** [mariotaku/moonlight-tv#452]
### Moonlight Version

1.6.18

### Device Type

webOS TV

### Device Model

LG C3

### Device OS

webOS 8.4.0 (HE_DTV_W230_AFABATAA)

### Host OS

Linux

### Host Software

Sunshine

### Host Setup

OS: Arch Linux x86_64
Kernel: Linux 6.10.7-arch1-1
CPU: AMD Ryzen 9 7950X3D (32) @ 5.76 GHz
GPU: NVIDIA GeForce RTX 4090 [Discrete]
Sunshine version v2024.903.123219

### Bug Description

After pairing the LG TV moonlight client to the sunshine host, when selecting the Desktop app, it proceeds to attempt to connect. After 10 secs it times out with the following error:

`Failed to start streaming
Failed to launch session: cURL error:
Timeout was reached (code -5)`

Sunshine logs detect no attempt of the client attempting to stream data.

Client was tested over ethernet both with built in port and attached usb dongle

![IMG_3269](https://github.com/user-attachments/assets/da54922a-4fb8-4fe2-bca3-e23b14c2b3c8)
![IMG_3268](https://github.com/user-attachments/assets/232a3436-bd0d-40f9-a1b0-31e17de871d3)

### Reproduction Steps

1. Pair Client to PC Host
2. Select any of the apps displayed
3. Connecting screen appears
4. Connection times out with Failed to start streaming error

### Expected Behavior

Seeing a stream of my PCs desktop upon selecting app.

**Comment by mariotaku** [comment]
Hi, is it possible to use tools like Wireshark, to see if there are actually network activity between the computer and the TV?

**Comment by Otakian** [comment]
I'll try and setup a wireshark instance and send you back info once I have it.

**Comment by Otakian** [comment]
Can confirm with the output below that the tv client is attempting to communicate with the pc via the TCP packets below. I filtered out the UDP packets as those just seemed like noise.

[output.txt](https://github.com/user-attachments/files/16873918/output.txt)

**Comment by noctious88** [comment]
I have the same issue, if I downgrade sunshine to v2024.823.131748 on windows, it works. Any version later than this, I get the same error.

**Comment by mariotaku** [comment]
> I have the same issue, if I downgrade sunshine to v2024.823.131748 on windows, it works. Any version later than this, I get the same error. 

Thanks for the report. Are there more specific commit ID in hex format?

**Comment by noctious88** [comment]
> > I have the same issue, if I downgrade sunshine to v2024.823.131748 on windows, it works. Any version later than this, I get the same error.
> 
> Thanks for the report. Are there more specific commit ID in hex format?

No problem, I can't pinpoint the commit ID of version 2024.823.131748, but I downloaded it on the 23rd August. This is the filter of commits from the 22nd: [Sunshine commits filter](https://github.com/LizardByte/Sunshine/commits/master?since=2024-08-22&until=2024-09-11)

**Comment by rayfilm0815** [comment]
I also encountered the same problem. I need to downgrade the version back to 0823 to normalize.

**Comment by mariotaku** [comment]
This might be a host issue, as I reproduced with `cURL` command. I'll discuss with Sunshine devs about this too.

**Comment by conkydong** [comment]
> > > > 저도 같은 문제가 있습니다. 윈도우에서 선샤인을 v2024.823.131748로 다운그레이드하면 작동합니다. 이보다 이후 버전에서는 같은 오류가 발생합니다.
> > > 
> > > 
> > > 보고해 주셔서 감사합니다. 16진수 형식의 더 구체적인 커밋 ID가 있나요?
> > 
> > 
> > 문제없습니다. 2024.823.131748 버전의 커밋 ID를 정확히 알 수 없지만 8월 23일에 다운로드했습니다. 22일 커밋 필터는 다음과 같습니다. [Sunshine 커밋 필터](https://github.com/LizardByte/Sunshine/commits/master?since=2024-08-22&until=2024-09-11)
> 
> Where can I download that version?

I'm also looking for that version.

**Comment by mickabrig7** [comment]
I have the same issue on my LG B3 using **v2024.922.10353**, and from limited testing it seems like it happens only when prep commands are used (global or app-related), removing all of them fixes it for me.

I'm only running `kscreen-doctor` stuff but I could try with a simple `echo` to see if the problem comes from just having prep commands, or having commands that take some time to execute.

**Comment by m33ts4k0z** [comment]
Also having the same issue on my LG C2 using the **v2024.922.10353**.
In my case, prep commands don't matter. I have no issues connecting from my Android phone.

Most likely [this](https://github.com/LizardByte/Sunshine/commit/f048510ef701ca6e693fe3ea433aaf7bf7a058ae#diff-eb6a110416af60a972465b8fe0a2872668110ced01a9ff0403bc973fadf8d0bbL47) commit is the issue.

**Comment by ReenigneArcher** [comment]
> Where can I download that version?

Sorry, we only keep the last 2 pre-releases (to avoid cluttering the releases page).

**Comment by conkydong** [comment]
> > Where can I download that version?
> 
> Sorry, we only keep the last 2 pre-releases (to avoid cluttering the releases page).

Do you still have it stored on your PC or somewhere else?
