### ISSUE TITLE
Core files taking up large amounts of storage space

### ISSUE THREAD

**Issue by choboko** [mariotaku/moonlight-tv#453]
### Moonlight Version

1.6.18

### Device Type

webOS TV

### Device Model

LG C2

### Device OS

webOS 8.3.0

### Host OS

Windows

### Host Software

Sunshine

### Bug Description

I was having storage issues in my LG C2 and decided to look for large files, as instructed in one closed issue here. Having no luck in the prestored files, I looked in the app folders. The Moonlight folder had several files called "Core.XXXX" taking up large amounts of storage space, as the attached image shows. I deleted them, got back my storage space and everything still works fine. Is there any way to avoid these files from piling up and taking up space? Thanks in advance!
<img width="1284" alt="Screenshot 2024-08-31 at 16 23 18" src="https://github.com/user-attachments/assets/6fb709b7-b292-4993-b03b-f59b31094ba7">

**Comment by mariotaku** [comment]
Hi, this issue has been fixed by #382. You can delete all the `core.*` files and it won't come up again if you are having the latest version.
