### ISSUE TITLE
Crash when host is offline

### ISSUE THREAD

**Issue by chocomega** [mariotaku/moonlight-tv#459]
### Moonlight Version

1.6.20 

### Device Type

webOS TV

### Device Model

LG C1

### Device OS

webOS 6.4.0

### Host OS

Windows

### Host Software

Sunshine

### Bug Description

When the host is offline, the loading animation spins indefinitely and pressing the Left button on the remote crashes the app.
This is not happening with 1.6.19.

Crash log:
[_var_palm_jail_com.limelight.webos_media_developer_apps_usr_palm_applications_com.limelight.webos_bin_moonlight (_init+0x691ec) [0x7f0b8].txt](https://github.com/user-attachments/files/17307362/_var_palm_jail_com.limelight.webos_media_developer_apps_usr_palm_applications_com.limelight.webos_bin_moonlight._init%2B0x691ec.0x7f0b8.txt)

### Reproduction Steps

1. Host offline
2. Start Moonlight
3. Press Left button on the remote

### Expected Behavior

The window to wake up the host or retry connection should appear and not crash.

**Comment by Matthias102** [comment]
Yeah, same issue on my LG OLED65G39 since i updated from 1.6.18 to 1.6.20.
