### ISSUE TITLE
[COMPAT] 65SM8600PUA

### ISSUE THREAD

**Issue by ryang3d** [mariotaku/moonlight-tv#46]
- Device Model: 65SM8600PUA
 - System Version: 4.9.0-53804
 - moonlight-tv Version: v0.6.2
 - Is Audio Working: Yes (Stereo)
 - Is Video Working: 1080p60fps (4k works but is a bit choppy)
 - Is Input Working: Magic Remote is working, Wired Xbox 360 is working

Wired in to gigabit LAN, and things seem pretty smooth at 1080p60fps. Not quite as smooth with 4k. Xbox One controller wired & wireless dongles do not work (unknown device). Just ordered 8bitdo adapter to try wireless Xbox One controller again later (will try to follow up once received and tested). Occasional crashing/clunkiness when launching games/Steam, but able to relaunch Moonlight and get smooth streaming from there when this does happen. Consistently crashes when launching a game after changing streaming settings (settings save, and games run on re-launch of moonlight-tv)

Not sure if surround sound is expected to be working at this point (I only heard stereo while testing, but didn't mess with any settings anywhere yet). Would be great to have that working too if not already implemented.

Thanks for all the hard work @mariotaku, this is looking fantastic!

**Comment by mariotaku** [comment]
Thanks for reporting! I'll be closing good compatibility reports, feel free to open if you encounter problems. For surround sound I have created a separate issue #49
