### ISSUE TITLE
Xbox Series S and Series X 

### ISSUE THREAD

**Issue by woiza** [mariotaku/moonlight-tv#464]
### Description

Hi, do you have any plans to build moonlight-tv for Xbox Series S and Series X?

### Motivation

Xbox supports much higher Bitrates and VRR.

### Additional Context

4k120 and YUV 4:4:4 should be possible.

**Comment by mariotaku** [comment]
Hello, platforms other than webOS/embedded Linux are out of scope for this project.

I do want to propose a universal UI design for big screens, though.
