### ISSUE TITLE
LG Remote Mouse Cursor visible when using USB dongle wireless Logitech mouse

### ISSUE THREAD

**Issue by Waxomi** [mariotaku/moonlight-tv#468]
### Moonlight Version

1.6.21

### Device Type

webOS TV

### Device Model

LG SM8500PLA

### Device OS

Web OS 5.4.61

### Host OS

Windows

### Host Software

Sunshine

### Host Setup

Windows 10, 3070, 32gb ram, high end but a bit old now processor and motherboard, I can't remember fully now, streams flawlessly though

### Bug Description

I have plugged an LG wireless mouse via the tiny USB dongle into the back of my TV. Everything works flawlessly except the pink LG cursor appears on top of the mouse cursor while controlling my computer! Can you detect that and hide it when it's there? Or change it to something tiny!

You can go into LG settings and make the cursor smaller, which I've done, but it's still unnecessary while Moonlight is running.

### Reproduction Steps

1. Plug in Logitech wireless mouse USB dongle to back of TV
2. Restart TV
3. Use mouse - mouse should be able to control the pink LG cursor on your TV
4. Start moonlight, go into desktop mode or any mode really of your computer
5. Notice all working flawlessly but the pink LG cursor overlays on top of the normal Windows cursor

### Expected Behavior

I'd love it if I could use the pink cursor with my mouse when I'm using the mouse on my TV, but for it to be hidden or very small when I'm using moonlight.

**Comment by mariotaku** [comment]
Hi, I have made some fixes in v1.6.23 pre-release. Would you like to test that out?

**Comment by mariotaku** [comment]
OK, v1.6.23 fixes this issue and cursor icon should be properly hidden now.

**Comment by Waxomi** [comment]
awesome thank youi! will try it out!!

**Comment by Waxomi** [comment]
It works!! Thank you so much.
