### ISSUE TITLE
[BUG] Release not compatible with 3.22 Geforce Experience

### ISSUE THREAD

**Issue by xatornet** [mariotaku/moonlight-tv#47]
**Describe the bug**
Incoming Geforce Experience 3.22 (Now no beta) is not compatible. Latest Moonlight releases have been updated to support it. 

**To Reproduce**
1. Install latest BETA GFE 3.22.xx on your PC
2. Pair your TV with GFE
3. Select a game
4. See error 500 Handshake

**Additional context**
Moonlight main project has updated PC client to support GFE 3.22.xx (see [here](https://github.com/moonlight-stream/moonlight-qt/releases/tag/v3.1.1) and [here](https://github.com/moonlight-stream/moonlight-android/releases/tag/v9.8.6).)

**Comment by mariotaku** [comment]
Thanks! I didn't notice it has been fixed. Will update to recent core library in next release.

**Comment by xatornet** [comment]
Great, thanks!!
