### ISSUE TITLE
Logitech keyboard and LG TV interactions

### ISSUE THREAD

**Issue by Waxomi** [mariotaku/moonlight-tv#473]
### Description

Thanks for fixing the mouse issue!

There is a secondary one which I don't know if you'll be able to fix where, because Logitech is properly supported by LG I guess, when there is a logitech keyboard connected to the TV, I assume keyboard input triggers a response from the tv.

Right now when using Moonlight with my Logitech keyboard on my LG tv, the cursor snaps to the centre of the screen whenever I press any key on the keyboard and then move the mouse. These buttons do what they correctly need to do on my windows computer, but the cursor snapping makes certain operations difficult.

Is there anything you can do?

### Motivation

Games and programs which use keyboard input and mouse at the same time, eg dragging files while holding down control, or using wasd and mouse to control a game are really hard to control.

### Additional Context

Very latest moonlight with Windows 10, LG webOS TV, Logitech wireless keyboard and mouse.

**Comment by mariotaku** [comment]
Hello! It's indeed very annoying that every keystroke resets the cursor. And there's no way to turn that off.

However, you can use the "Hardware mouse" feature so it will ignore the magic remote's behavior.

**Comment by Waxomi** [comment]
You're right! That's perfect thank you, it works great. I guess then I'll downgrade my suggestion to maybe explaining in more detail how that option can fix this issue!

Thank you very much!! I love this it has completely changed how we interact with our computers in our home.
