### ISSUE TITLE
[COMPAT] OLED55C8PLA

### ISSUE THREAD

**Issue by Jessewb786** [mariotaku/moonlight-tv#48]
Version WebOS: 05.30.10
Video: Doesn't Work [Black screen, also SOPS not supported @4k 60FPS]
Audio: Works
Remote: Works
Controller: Not tested

**Comment by mariotaku** [comment]
Could you provide following info:
1. webOS version and decoder in Moonlight Settings -> About

And try:
1. Lower the bitrate and resolution
2. Update to recent Moonlight versions

**Comment by mariotaku** [comment]
Closing. You may try switching between decoders to find a usable one. If problem still exists, feel free to reopen/open a new issue.
