### ISSUE TITLE
Xbox and other 2.4 GHz Controllers

### ISSUE THREAD

**Issue by woiza** [mariotaku/moonlight-tv#483]
### Description

I can connect my Xbox controllers to my LG C1 via Bluetooth. However, the lag is quite high and noticeable.
I tried using Microsoft's Xbox Wireless Adapter, but the TV didn't recognise it.

### Motivation

Supporting Microsoft's Xbox Wireless adapter and other 2.4 GHz USB sticks and controllers would reduce lag.

### Additional Context

Are you aware of any 2.4 GHz controllers or USB sticks that work with LG TVs? Can you recommend any?

**Comment by mariotaku** [comment]
Hello, using the official Xbox adapter is not possible as it needs drivers. [This wiki page](https://github.com/mariotaku/moonlight-tv/wiki/Gamepad-Setup) has some suggestions of compatible adapters.

**Comment by woiza** [comment]
That's unfortunate. I saw the wiki page, but the adapters listed there are all bluetooth adapters.
Are you aware of any working 2.4 GHz adapters and controllers?
Which adapter / adapter controller combination on the wiki page has the lowest latency?

**Comment by woiza** [comment]
@mariotaku thanks, will do.
