### ISSUE TITLE
NetCast compatibility version

### ISSUE THREAD

**Issue by mariotaku** [mariotaku/moonlight-tv#5]
## What was done
- [x] Main loop
- [x] A/V dec
- [ ] Input Event

## Confirmed to be working on
- [ ] NetCast 4
- [ ] webOS 2
- [x] webOS 3
- [x] webOS 4
- [ ] webOS 5

**Comment by emircanerkul** [comment]
@mariotaku Hi,

I have NetCast TV (lg 40ub800v-za), i can test it but idk how to install it or what to install. Could you give me instructions? I can install and give feedback too.

**Comment by mariotaku** [comment]
Hi, this NetCast thing means a component built-in of webOS 4 and below. Moonlight can't run on NetCast TVs.

**Comment by emircanerkul** [comment]
Oh, okay. Thank you.
