### ISSUE TITLE
[BUG] Release v0.6.3-v0.6.6 crashes on load

### ISSUE THREAD

**Issue by xatornet** [mariotaku/moonlight-tv#50]
**Describe the bug**
I've updated to release v0.6.3 & v0.6.6 and now Moonlight won't even open. Releases v0.6.1 and below work. I've tried to fully erase moonlight and install it again, but i have the same effect.

**To Reproduce**
1. Install v0.6.3/v0.6.6 via webOS Tv Cli
2. Back on the TV, select and open Moonlight
3. The app shows its grey screen for a second, then closes itself again.

**LG webOS TV (please complete the following information):**
 - Model: 55NANO916NA
 - webOS version: 5.2.1

**Comment by mariotaku** [comment]
Could you follow this link to see crash log? https://github.com/mariotaku/moonlight-tv/wiki/Troubleshooting#crashes

**Comment by xatornet** [comment]
I'll try, but seems there's another update to GFE right now. I'll update it and try again...

**Comment by mariotaku** [comment]
Looks like many people got similar issue. Let me update dependencies and try again.

**Comment by xatornet** [comment]
well, eitherway, I'll give it a go again with the updated GFE

**Comment by xatornet** [comment]
Nope, same behaviour even with v0.6.6. Just a grey screen for a second, then the app closes

**Comment by xatornet** [comment]
Also, I don't get a crash log. Seems more like it automatically closes itself. If I try to get a log, here's what I get:

![image](https://user-images.githubusercontent.com/43992639/114556023-924d3f80-9c68-11eb-9ca5-45d30f68c6e6.png)

**Comment by mariotaku** [comment]
@xatornet Now that 0.6.8 should fix crashing issue. Could you try if it can launch? If decoder doesn't work for you, I'll refer to a new issue.

**Comment by xatornet** [comment]
> @xatornet Now that 0.6.8 should fix crashing issue. Could you try if it can launch? If decoder doesn't work for you, I'll refer to a new issue.

I'll give it a go this morning and let you know. Thanks for your huge effort and time @mariotaku

**Comment by mariotaku** [comment]
Nice. I'll close this crash issue and waiting for your further report :)
