### ISSUE TITLE
Black Screen LG Oled 77C8LLA

### ISSUE THREAD

**Issue by circoloco696** [mariotaku/moonlight-tv#51]
# Basic information

 - Device Model: LG OLED77C8LLA
 - System Version: 05.30.10 / Moonlight webOS version 4.3.0 / Decoder webOS SMP / Version 0.6.3
 - Is Audio Working: Yes
 - Is Video Working: No, tryed lower res / Bitrate / PC settings fixed to 60hz / deactivated G-Sync
 - Is Input Working: YES, Remote and Xbox series X controller

Dashboard is working perfect, also everything launchable with the Remote and Controller, Audio is working too. 
The games are starting without image (Blackscreen), i can hear only the Audio. 
PC Monitor getting the settings from Moonlight (lower its res etc. )

I Tested Moonlight Stream also on my Android tablet, works flawless.

**Edit : I saw a new Version released, the problem is still existing on Version 0.6.5**

**Comment by mariotaku** [comment]
Could you try https://github.com/mariotaku/moonlight-tv/releases/tag/v0.6.6 version and switch to another decoder like LGNC/NDL?

**Comment by circoloco696** [comment]
> Could you try https://github.com/mariotaku/moonlight-tv/releases/tag/v0.6.6 version and switch to another decoder like LGNC/NDL?

Its working now ! Thank you ! It runs now with every codec. Im using currently the LGNC. If i can choose, what is the best one ?

Also 4k 60 is working flawless till 35000kbps. Over that the Screen freezes at graphic demanding Pictures /game scenes. 
I think it hit the limitation of the 10/100 mbit ethernet port from the C8 ? Any room to improve here? 

The inputlag from the Xbox controller connected via usb directly on the C8 is phenomenal. Lowest one i´ve tested so far.

**Comment by mariotaku** [comment]
@circoloco696 Great it works! I've done some work to lower input lag to 1ms level on webOS :) Feel free to open new issue when you find something wrong.
