### ISSUE TITLE
[BUG] 1440p has arctifacts - Some considerations

### ISSUE THREAD

**Issue by xatornet** [mariotaku/moonlight-tv#54]
**Describe the bug**
Seems to me that v0.6.8 has a lower quality video decoding than previous versions. On version v0.6.1 for instance, I was using 1440p @60fps with 40Mbps aprox, and the results were right. But now, using the same preset but even with 50Mbps or 60Mbps, I get some weird arctifacts. Mostly color errors like this:

![photo_2021-04-14_11-16-07](https://user-images.githubusercontent.com/43992639/114686200-dac13780-9d12-11eb-88d5-8b7c002ad86c.jpg)

**To Reproduce**
1. Install v0.6.8
2. Pair with pc and  select 1440p 60fps, with 50+Mbps
3. Open a game and play for a couple of min.

**LG webOS TV (please complete the following information):**
 - Model: 55NANO916NA
 - webOS version: 5.2.1

~~**UPDATE**
Testing the issue, It seems it's resolution related, not bitrate. Using 1080p works, but 1440p seems to be causing decoding arctifacts in my case. I'll try with other decoders to see what is the behaviour.~~

**UPDATE 2**
Ok, I've been updating to v0.7.x til v0.7.4 now, and I've tested this properly on my TV. Here are my results:

- 1440p seems to be the culprit. LG's decoders seems that do not like that resolution. I can decode 1080 at 50Mbps or 4k even, without arctifacts, but 1440p, no matter what bitrate I select, has the same arctifacts on the upper side screen.

- Testing both SMP and NDL decoders, I've come across one curious thing: although auto setting defaults to SMP, is NDL what gives far less input delay, and also, **TV enters into gaming reduced input mode by itself whenever using NDL Decoder!!!**

- Also, 120Fps preset does not achieve 120fps. I can't get more than 78-80fps, no matter what bitrate or resolution. It feels like a framerate cap, but it's weird that it caps to about 80fps...

![photo_2021-04-25_19-08-13](https://user-images.githubusercontent.com/43992639/116002357-a9d9e000-a5f9-11eb-82e2-8d430e8a070d.jpg)

**Comment by mariotaku** [comment]
Does it look overexposed? Did you have HDR on your host machine?

**Comment by xatornet** [comment]
I don't have HDR enabled. It looks weird some times. White tends to be on some places yellowish, and dark blue turns into red.

**Comment by mariotaku** [comment]
On larger bitrates I can see drastic raise of submitting time, so I think 40 is a sweet spot for most TVs, crash may even occur when bitrate beyond 60.

**Comment by xatornet** [comment]
> On larger bitrates I can see significant raise of submitting time, so I think 40 is a sweet spot for most TVs, crash may even occur when bitrate beyond 60.

Yeah, but on 40Mbps the arctifacts happen too. That's why I tried raising the bitrate, to see if it would improve picture quality.

**Comment by circoloco696** [comment]
I ordered a usb3 to gigabit Ethernet adapter. All the lg tv's only have 10/100 mbit build in ethernet. 

Cant get over 25-30 mbit with 4k 60 stream without lag/ freezes. I will report back if its possible to crank up the bitrate with this adapter.

**Comment by mariotaku** [comment]
https://github.com/mariotaku/moonlight-tv/releases/tag/v0.6.10 Could you try if this version has sound on webOS?

**Comment by xatornet** [comment]
> https://github.com/mariotaku/moonlight-tv/releases/tag/v0.6.10 Could you try if this version has sound on webOS?

Audio is working back again!! Thanks. I'll update the other thread.

Now on this version I have loads of decoders, but while I select "Auto", i don't actually know which is using. It would be great to put it on the statistics where you can see framerate and other things.

**Comment by xatornet** [comment]
I've been tinkering with latest v0.7.1. It seems that it's not the bitrate the issue. It's the resolution. If I put 1080 at 40Mbps, it works fine. But 1440p at the same bitrate, show those artifacts. Both are using the same decoder, both on h265. I'll futher test with the other decoders included, to see what is the behaviour.

**Comment by xatornet** [comment]
I've updated my findings on the OP post

**Comment by mariotaku** [comment]
There's not much I can do technically for this issue. But the information is very useful, so I'll be converting this into a discussion.
