### ISSUE TITLE
Can't choose NDL with 0.6.9[BUG]

### ISSUE THREAD

**Issue by roykaandorp** [mariotaku/moonlight-tv#55]
**Describe the bug**
Can't choose the NDL video codec, with the 2 codecs I can choose I have a black screen. Version 0.6.6 however does work correctly.

**To Reproduce**
Open moonlight, start a stream.

**Expected behavior**
Possibility to choose the NDL codec.

**LG webOS TV (please complete the following information):**
 - Model: 75uk6200
 - webOS version 4.3.0

**Comment by mariotaku** [comment]
Thanks for your report. I've added back NDL and LGNC in v0.6.10 and it will be available shortly.

**Comment by mariotaku** [comment]
https://github.com/mariotaku/moonlight-tv/releases/tag/v0.6.10 You may need to switch to NDL manually.

**Comment by roykaandorp** [comment]
Yes now it's working, it stayed on NDL as I used that setting on 0.6.6, tried to set it at automatically but that didn't work indeed
