### ISSUE TITLE
[COMPAT] OLED55CX

### ISSUE THREAD

**Issue by matustokar** [mariotaku/moonlight-tv#57]
- Moonlight version: 0.6.10
- Device Model: OLED55CX
- System Version: 5.2.0
- Is Audio Working: Yes
- Is Video Working:  1080@60
- Is Input Working: 

MagicRemote works 
Xbox controller doesn't. After connecting with USB cable to tv it just vibrates, xbox logo is not illuminated. Gamepad indicator in moonlight is showing 1 connected controller but it isn't possible to control the game.

So I wasnt able to do proper testing, but game menu animations seems to be smooth :D

**Comment by mariotaku** [comment]
What is your controller, Is it Xbox One Controller or 360?

**Comment by matustokar** [comment]
xbox one

**Comment by mariotaku** [comment]
@matustokar This is expected. For connecting directly to the TV, Xbox 360 Controller, PS3/PS4 Controller should work. If you want to use Xbox One Controller, you can consider buying an adapter: https://github.com/mariotaku/moonlight-tv/wiki/Gamepad-Setup

**Comment by matustokar** [comment]
Thanks. Will do proper testing in couple days.

**Comment by matustokar** [comment]
Finally had some longer playing sessions. Working good with 1080@60.

**Comment by mariotaku** [comment]
Good to hear that! I think compatibility support could be considered good.
