### ISSUE TITLE
[BUG] Streaming Error on v0.7.0

### ISSUE THREAD

**Issue by xatornet** [mariotaku/moonlight-tv#60]
**Describe the bug**
After the pair, if I try to open any app to stream, I get this error:

Streaming Error
Connection failed at stage 4, errorCode = 552

**To Reproduce**
1. Install v0.7.0
2. Pair with PC
3. Try to open any stream

**LG webOS TV (please complete the following information):**
 - Model: 55NANO916NA
 - webOS version: 5.2.1

**Comment by mariotaku** [comment]
Hi! Could you do a quick check about this issue? https://github.com/mariotaku/moonlight-tv/wiki/Troubleshooting#quick-checklist

**Comment by xatornet** [comment]
Issue resolved on v0.7.1
