### ISSUE TITLE
[COMPAT} 43LH6000

### ISSUE THREAD

**Issue by carlosirume** [mariotaku/moonlight-tv#62]
# Basic information

 - Device Model: 43LH6000
 - System Version: 05.30.80
 - Is Audio Working: 
 - Is Video Working: yes
 - Is Input Working: 

Moonlight is starting and pairing correctly, but does not show the streaming. I have an error message:
Connection failed at 1062492, errorCode  = -1

**Comment by mariotaku** [comment]
Which decoder has been selected? You can find in Settings -> About.

**Comment by carlosirume** [comment]
It´s set to automatic in both, tv and my pc.

**Comment by mariotaku** [comment]
In Settings -> About, you'll find the one that chosen automatically. For your TV, NDL or NetCast Legacy might work.

**Comment by mariotaku** [comment]
Closing this. Feel free to reopen/create a new one if problem occurs.
