### ISSUE TITLE
Automatically extending developer mode with Home Assistant

### ISSUE THREAD

**Issue by Raicuparta** [mariotaku/moonlight-tv#63]
Since I don't like manually extending the dev mode all the time, I wrote an automation for Home Assistant to do this every night: https://gist.github.com/Raicuparta/f9cd299918e7280cc5c90c947b95de0f

If you don't know Home Assistant, check it: https://www.home-assistant.io/

You can have it running off of a raspberry pi or some laptop.

Sorry that this isn't really an issue about this project, but I thought people who use moonlight-tv might find it handy. Feel free to close the issue. Perhaps you can link to the solution in the documentation.

**Comment by mariotaku** [comment]
This is a good one. Before closing/transferring this issue I have some other way to extend this. https://github.com/webosbrew/dev-goodies/blob/main/reset-devmode-timer.sh . Also stay tuned to https://github.com/webosbrew/webos-homebrew-channel :)

**Comment by Raicuparta** [comment]
@mariotaku Interesting! If I understand correctly, it just needs to connect to the TV to get the session token, then the actual resetting doesn't require the TV anymore. I assume you can't SSH into WebOS while the TV is off, even with Wake-On-Lan being on. So using Home Assistant to power on the TV and run your script sounds like the smartest way to accomplish this.

**Comment by mariotaku** [comment]
Indeed. So you can first wake the TV and obtain dev mode token. Then perform all reset requests without TV.

**Comment by Raicuparta** [comment]
@mariotaku I'm trying to run your script, and at the end after calling LG's endpoint, I get this response:
```json
{"result":"success","errorCode":"200","errorMsg":"GNL"}
```
But even with this apparently positive result, the remaining time on my Developer Mode app still didn't reset back to 50 hours. Was I supposed to get a different result, or do you know if there's something that I might be missing?

**Comment by mariotaku** [comment]
Developer Mode only update its UI on boot. So this should be fine. Maybe reboot and you'll see it's been reset?

**Comment by Raicuparta** [comment]
Yeah even after rebooting the TV it doesn't change. Only changes when I press the extend button. Strange 🤔 How did you find that this was the endpoint that needed to be called? Maybe somehow depends on the country or something? I wanna see if I can figure out which endpoint it's calling on my TV, but not sure how to do that.

**Comment by mariotaku** [comment]
Could you try make a GET request to this URL?
`https://developer.lge.com/secure/CheckDevModeSession.dev?sessionToken=[the token you have]`

On mine it says `{"result":"success","errorCode":"200","errorMsg":"49:17:11"}` clearly says it's been updated properly.

**Comment by Raicuparta** [comment]
Yeah that's what I did. I get the success result. The only difference seems to be the "errorMsg" which for you is something that looks like a time counter, and for me it's just "GNL" which I don't know the meaning of.

**Comment by mariotaku** [comment]
Oh, I mean the second URL which is different than first one. `https://developer.lge.com/secure/CheckDevModeSession.dev?sessionToken=[the token you have]` is to check how many hours devmode have.

**Comment by mariotaku** [comment]
Closing. Please looking forward to [homebrew-channel(https://github.com/webosbrew/webos-homebrew-channel) for a better solution.

**Comment by Raicuparta** [comment]
> Oh, I mean the second URL which is different than first one. `https://developer.lge.com/secure/CheckDevModeSession.dev?sessionToken=[the token you have]` is to check how many hours devmode have.

Yeah sorry I didn't notice it was a different URL.

If anyone else needs help with the app not updating: just ignore it and use that API to check the real time. For some reason on my tv the developer mode app doesn't reflect the resets that happen from outside the app. It just keeps counting down. But i can let it go to zero and it still works, as long as the timer on that API call doesn't get to zero too.
