### ISSUE TITLE
[Feature Request] Add some info/description/differences between the different decoder presets

### ISSUE THREAD

**Issue by xatornet** [mariotaku/moonlight-tv#65]
**Is your feature request related to a problem? Please describe.**
Improve Wiki by adding and documenting what characteristics has each decoder ( NDL vs SMP...etc)

**Describe the solution you'd like**
Just adding a description of what advantages/disadvantages each decoder has. Maybe inside wiki or in the main post.

**Comment by mariotaku** [comment]
This is quite confusing. While I'm trying to automate to select the best one, here's a simple doc for comparison: https://github.com/mariotaku/moonlight-tv/wiki/Performance

**Comment by xatornet** [comment]
Great, thanks

**Comment by xatornet** [comment]
Also, and this maybe off-topic but, since the development is pretty good, and fairly stable, is there a possibility to make this into the LG's Store? It's really anoying that your amazing works gets wiped whenever the devmode time runs out.

**Comment by mariotaku** [comment]
I have contacted LG but they ghosted me after few emails :(
But we are also working on a third party homebrew store: https://repo.webosbrew.org/ and will be available in the future (root will be optional)

**Comment by xatornet** [comment]
> I have contacted LG but they ghosted me after a few emails :(
> But we are also working on a third party homebrew store: https://repo.webosbrew.org/ and will be available in the future (root will be optional)

That is great!! I'll give it a go as soon as I find a proper tutorial. Thank you. I won't bother anymore :-)
