### ISSUE TITLE
[COMPAT]SOPS Isn't Supported

### ISSUE THREAD

**Issue by Orof** [mariotaku/moonlight-tv#66]
** Since device support range becomes wider, please submit this issue only when you got problems **

# Basic information

 - Device Model: 55UN7340PVC
 - System Version: 5.2.1
 - Is Audio Working: Yes
 - Is Video Working: 4K60FPS
 - Is Input Working: Remote

Please also provide additional information when possible.
-1080P with enhanced optimization for games present an error - SOPS isn't supported for the resolution
-Using an RX580 GPU with Open Stream for the usage with Moonlight, works great!
d-idn't test gamepad yet

**Comment by mariotaku** [comment]
Hello, I think SOPS could be changed in Settings -> Host Settings. Sometimes the SOPS is not supported under specific resolution/fps. Turning it off will be able to safely ignore that.

**Comment by Orof** [comment]
Disabling optimize game settings solved the problem (but there is no optimization). the resolution is pretty standard - 1080P/60FPS. even in 720P the problem persists. other than that I am very thankful for your creation! now I can use my computer to emulate ps2 & ps3 games, and imagine that my PS5 has backwards compatibility hahaha. much better than 720P/60FPS I got with direct streaming from the computer to the TV over Wi-Fi. I hope that someday moonlight would be able to become a software in the LG official apps, but for me I'm good :)
