### ISSUE TITLE
Static link for releases

### ISSUE THREAD

**Issue by PiRomant** [mariotaku/moonlight-tv#69]
Make static name for `.ipk` for static link https://docs.github.com/en/github/administering-a-repository/linking-to-releases
ex: https://github.com/mariotaku/moonlight-tv/releases/latest/download/com.limelight.webos.manifest.json always leads to the file from latest release.

**Comment by mariotaku** [comment]
Do you have some special consideration for this case? The manifest is for https://github.com/webosbrew/webos-homebrew-channel , which is capable of resolving the IPK file linked to the manifest. Besides, version suffixes to IPK can make people who download Moonlight manually managing those packages with less hassle.

**Comment by PiRomant** [comment]
I wanted to ask to add a static link to the non rooted hack install website. I don't think the author will keep track of the latest versions. https://webosapp.club

**Comment by mariotaku** [comment]
How about to ask them? We have standardized definition, so if they are willing to adopt this, more apps from webosbrew will be available to that app market.

**Comment by PiRomant** [comment]
Unlikely
