### ISSUE TITLE
[COMPAT]

### ISSUE THREAD

**Issue by Jessewb786** [mariotaku/moonlight-tv#71]
Reopening the issue for this TV Model

## Basic information

 - Device model: OLED55C8PLA
 - Firmware version: 05.30.10
 - webOS version: 4.3.0
 - Moonlight version: 0.7.11
 - Is audio working: Yes
 - Is video working: No. Black screen on all video decoder settings, resolutions and refresh rates
 - Is input working: Yes

## Description
Black screen on all video decoder settings, resolutions and refresh rates

**Comment by mariotaku** [comment]
Should be the same to #35, please follow updates in that issue.

**Comment by mariotaku** [comment]
Oh, by the way did it work before?

**Comment by Jessewb786** [comment]
@mariotaku No. I haven't seen it work it in previous versions either.

**Comment by mariotaku** [comment]
@Jessewb786 I see. Let's continue our discussion in #35.
