### ISSUE TITLE
[BUG] Sunshine server doesn't stay paired

### ISSUE THREAD

**Issue by exalented** [mariotaku/moonlight-tv#72]
**Describe the bug**
Exactly as described in #32 the server doesn't stay paired.

**To Reproduce**
1. Paired with Sunshine server streaming an application works great.
2. Close the app.
3. Start the app.
4. Sunshine server is not in the list of servers.

**Expected behavior**
Sunshine server always stays in the list of paired servers.

**LG webOS TV:**
 - Model: 65NANO90UNA
 - webOS version: 5.2.1
 - software version: 03.21.80

**Additional context**
Every single start of the app moonlight needs me to type in the IP again. I believe it stays paired because the server doesn't ask for a pin. Perhaps #74 is related.

**Comment by exalented** [comment]
You can remedy this by adding the same server multiple times. It is then more likely that upon backgrounding/closing the app your server will be there, but it doesn't completely get rid of the issue.

**Comment by mariotaku** [comment]
Time for a revisit. Let's see if it works now.

**Comment by exalented** [comment]
Right! This issue has been resolved as well in conjunction with #91 ! Great job!

**Comment by exalented** [comment]
Sorry for prematurely closing this issue, but after restarting the client more than 3 times it seems this issue is still apparent in v0.9.2 of moonlight-tv

**Comment by exalented** [comment]
The hosts.conf file seems to get corrupted. The file still exists during this entire process, but once cat'd shows:
`LIBXML2_2.6.28 = ???` with no return carriage which makes my tv terminal display: `LIBXML2_2.6.28 = ???~ $ `. Then the only way to get the hosts.conf file saved again without uninstalling the application is to add your server then hit the drop-down menu and click on it. Upon closing the client the hosts.conf is correctly saved.

**Comment by exalented** [comment]
0eb8c67ab4f633fc3eeed0c77e6bf7122e744df6 resolves this issue.
