### ISSUE TITLE
[BUG] Server connection issues

### ISSUE THREAD

**Issue by exalented** [mariotaku/moonlight-tv#73]
**Describe the bug**
Connection loss mid-session causes moonlight to crash and crash upon every subsequent attempt to reconnect.

**To Reproduce**
1. Launch game/app
2. Restart server: `$ systemctl --user restart Sunshine`
3. Moonlight crashes and exibits behaviors described.

**Expected behavior**
Moonlight kicks you back to the main menu.

**LG webOS TV (please complete the following information):**
 - Model: 65NANO90UNA
 - webOS version: 5.2.1
 - software version: 03.21.80

**Additional context**
Related: #72 #32 
Oddly enough this is the only way the sunshine server stays in the list of available servers when moonlight starts up for my particular device.

Reproduced 4 times.
[crashes.log](https://github.com/mariotaku/moonlight-tv/files/6600819/crashes.log)

**Comment by exalented** [comment]
[crashes.log](https://github.com/mariotaku/moonlight-tv/files/6600782/crashes.log)

**Comment by mariotaku** [comment]
Could you try v0.7.12 to see if it's fixed?

**Comment by exalented** [comment]
The v0.7.12 client no longer crashes outright and no longer requires a restart of the client to launch a game/connect to the server. I believe the remaining issues where the sunshine server doesn't fully restart would be an issue for the sunshine team to resolve. Nice work!
