### ISSUE TITLE
What would it take to publish this to the store?

### ISSUE THREAD

**Issue by Raicuparta** [mariotaku/moonlight-tv#75]
Would it be possible at all, or is this type of app just not allowed? If it's even possible, I'd like to know if there's anything I can help with.

**Comment by CremboC** [comment]
Hi @mariotaku , for some reason @Raicuparta closed this issue, but I was going to ask the exact same question. What are the blockers releasing this to the normal LG store, if there are any?

**Comment by mariotaku** [comment]
> Hi @mariotaku , for some reason @Raicuparta closed this issue, but I was going to ask the exact same question. What are the blockers releasing this to the normal LG store, if there are any?

LG people is the blocker. They doesn't seem interested in contact with me. I have sent few inquiries but they ignored.

**Comment by CremboC** [comment]
@mariotaku hmm that's unfortunate. I assume you just tried to follow the normal process https://webostv.developer.lge.com/discover/distribute/app-submission-process/ here? May I ask at which step they ignored you?

**Comment by mariotaku** [comment]
@CremboC moonlight-tv is not ordinary app that's eligible to be submitted directly: https://webostv.developer.lge.com/common-page/faqs/general-what-types-applications-can-run-webos-tv/

> NDK (Native Development Kit) is now provided to some partners and LG is planning to open it in public in the future.

moonlight-tv is not developed by official SDK, instead it's built with unofficial homebrew NDK, which I believe will be rejected upon submittion.
