### ISSUE TITLE
[BUG] Release v0.8.0-0.8.1 garbled audio

### ISSUE THREAD

**Issue by exalented** [mariotaku/moonlight-tv#76]
**Describe the bug**
Garbled audio. Tested with all backends. **This problem does not occur with v0.7.12**

**To Reproduce**
1. Launch Moonlight
2. Launch a game
3. Experience misunderstanding of audio.

**Expected behavior**
Understandable audio

**LG webOS TV:**
 - Model: 65NANO90UNA
 - webOS version: 5.2.3-252105
 - software version: 03.23.05

**Additional context**
Take note that:
- when I select automatic backend selection it picks PulseAudio (This is normal for this TV).
- when I select ndl backend it shows PulseAudio.
- when I select PulseAudio backend it shows PulseAudio.
- when I select sdl backend it shows sdl.

This audio garble sounds familiar to the audio lag I experienced before switching to pipewire on arch a few years ago. The sdl garble sounds different.
[garbledaudio.log](https://github.com/mariotaku/moonlight-tv/files/6689218/garbledaudio.log)

**Comment by mariotaku** [comment]
Is your decoder SMP now? How about NDL?

**Comment by exalented** [comment]
From what I tested only pulse seemed to work.

**Comment by mariotaku** [comment]
> From what I tested only pulse seemed to work. That seems fine because pulse has always been selected in auto mode.

How about to specify decoder to NDL? It should come with a working decoder, unless your host is transmitting wrong audio data. According to the log there's chance.

**Comment by exalented** [comment]
In v7.12 I'll choose NDL as backend, restart, go to settings and it shows the backend as SDL. Launching a game works fine as there's no audio garble and again it says SDL in the stats screen. The same exact situation happens with v8.0 except there's audio garble. And again when I specify to use SDL in v8.0 it shows the backend as PulseAudio both in the menu and in the stats screen when I launch a game.

**Comment by exalented** [comment]
With v0.8.2 comes a new core. This makes the client compatible with Sunshine servers v7.X moving forward; however, for this TV you're going to want to use the NDL backend. *As a side note Sunshine v7.1 isn't able to perform nvenc so you're going to want to force software mode, for example, to get a picture that isn't just rendered black.*
