### ISSUE TITLE
[BUG] audio not working on latest version .8.2

### ISSUE THREAD

**Issue by antargame** [mariotaku/moonlight-tv#79]
No sound but video is available. Tried restarting both host and client. Oh UJ6300 on top  version 06.00.03 . This might be a comparability issue as I am able to get audio working on normal clients like my laptop. Any ideas? It probably just boils down to compatibility right? Any ideas would be appreciated:) thanks in advanced.

**Comment by antargame** [comment]
It also will not allow me to input custom ips for the host or change the audio decode

**Comment by mariotaku** [comment]
Might be related to #67 . What is the current decoder and audio backend?

**Comment by antargame** [comment]
i can not change the current decoder or the audio backend so i couldnt tell you. It is set to automatic and will not let me select a codec or decoder.

**Comment by mariotaku** [comment]
According to your TV, it's running webOS 3.9 isn't it? What did you get if you change audio backend?

**Comment by antargame** [comment]
i am unable to change the audio backend. The menu will not allow me to. I am selecting the button but it wont let me switch it.

**Comment by mariotaku** [comment]
I see, your TV doesn't come with magic remote right? I'll improve that in next release.

**Comment by mariotaku** [comment]
@antargame You're now able to select other audio backends, I think SDL audio will work at least.

**Comment by antargame** [comment]
thanks so much for doing all of this. i will check if this fixed it later and respond back

**Comment by mariotaku** [comment]
Now there are multiple audio backends. Some should work (but with higher latency). Please let me know if sound still not working.
