### ISSUE TITLE
[BUG] LG Model: LJ550T , WebOS 06.00.04 crash when 2nd launches

### ISSUE THREAD

**Issue by tranbaohuu** [mariotaku/moonlight-tv#82]
Dear developers
My TV after first time connected  then CRASH when the second time launches. I think bug from the WebOS version 06.00.04. I remember last time on previous version WebOS everything worked well. I've tried uninstall/ reinstall but it's same.

Regards

**Comment by mariotaku** [comment]
Could you install old versions to see which version breaks on your TV?

**Comment by tranbaohuu** [comment]
> Could you install old versions to see which version breaks on your TV?

Let me try then reply to you !

**Comment by tranbaohuu** [comment]
I've tried 0.8.2, 0.8,1   but they're same issue !

**Comment by mariotaku** [comment]
Sounds like your system is running webOS 6, that's the information listed when you open Moonlight Settings - About?

**Comment by tranbaohuu** [comment]
Let me explain
For the first time connected then played everything were good. After exit then re-open  MoonLight i did not see the IP of my PC that I've added, then I've tried to add PC again and crash when I've clicked on the input  field. Crash back to default TV page. But when I've tried to remove then reinstall again app it's crash like above, 1st  ok, 2nd crash.

**Comment by mariotaku** [comment]
I see. This sounds like something I can fix. What exactly is your system version? You can find them by open Moonlight Settings - About.

**Comment by tranbaohuu** [comment]
I just tried your latest version 9.0 but it's still not working. You can see on 2 videos below for more information.

https://youtu.be/Z7And3VDGjA

https://youtu.be/3gVbCz8X-Kw

**Comment by tranbaohuu** [comment]
> I see. This sounds like something I can fix. What exactly is your system version? You can find them by open Moonlight Settings - About.

I see it but i don't understand on 2 versions 6.x.x and 3.x.x just give you. One inside setting and another on ML![IMG20210719172753.jpg](https://user-images.githubusercontent.com/10123641/126146737-114f2f32-83b4-439b-82d3-eb4b64e8b3a1.jpg)

![IMG20210719172826.jpg](https://user-images.githubusercontent.com/10123641/126146769-dad159f0-ec38-4c6e-b35f-b2752b55b99a.jpg)

**Comment by mariotaku** [comment]
@tranbaohuu Thank you. This information should be enough to fix this issue. I'll work on this.

**Comment by mariotaku** [comment]
@tranbaohuu I have updated 0.9.3 version, maybe it will work on your TV.

**Comment by tranbaohuu** [comment]
> @tranbaohuu I have updated 0.9.3 version, maybe it will work on your TV.

Thank for your contribute ! wish you have a good weekend !

**Comment by mariotaku** [comment]
@tranbaohuu Wish you could also enjoy gaming. Let me know if there are any problem :)

**Comment by tranbaohuu** [comment]
![IMG20210803194002.jpg](https://user-images.githubusercontent.com/10123641/128017159-27fb7738-4917-4f09-91e8-f76b1b7b0ee4.jpg)


Great is back!
