### ISSUE TITLE
[COMPAT] 50UK6520PSA WebOS 4.4.0 1440p and 4K doesn't work

### ISSUE THREAD

**Issue by gricardo93** [mariotaku/moonlight-tv#83]
## Basic information

 - Device model: (50UK6520PSA ) 
 - Firmware version: ( 05.40.06) 
 - webOS version: (4.4.0) 
 - Moonlight version: ( 0.9.0 ) 
 - Is audio working: ( Yes) 
 - Is video working: (1080p60) 
 - Is input working: (Gamepad, Remote) 

## Description

Great app!! It worked on my TV, but unfortunately only 1080p60fps using webOS NDL or Netcast Legacy decoder. On both, when I select 1440p or 4k, only audio works and a blank screen. I hope it can be fixed and thank you so much to bring this app to LG TVs.

**Comment by mariotaku** [comment]
Did you tried to lower the bitrate? As some TV may not have ability to stream 1440p/4K video.
