### ISSUE TITLE
[COMPAT] Can't Discover Host or Input IP Address

### ISSUE THREAD

**Issue by Dutisto** [mariotaku/moonlight-tv#84]
## Basic information
 - Device model: 43UK6300PLB
 - Firmware version: 05.40.06
 - webOS version: 4.3.0
 - Moonlight version: 0.9.0
 - Is audio working: No
 - Is video working: No
 - Is input working: No

## Description

Moonlight doesn't detect my GameStream PC, despite other devices can. If I want to enter the IP manually, I can't enter text into the box.

I said that nothing works because I couldn't (yet) test it

**Comment by mariotaku** [comment]
I have made a major update to the UI. Many reports that soft keyboard is working properly now. Could you try update and give it another shot?

**Comment by mariotaku** [comment]
Closing for now. Please comment if it still doesn't work.
