### ISSUE TITLE
Non-standard input device support

### ISSUE THREAD

**Issue by exalented** [mariotaku/moonlight-tv#86]
**Is your feature request related to a problem? Please describe.**
I am trying to attach a "Harmonix Guitar Controller for Nintendo Wii" adapter to play clonehero through moonlight. moonlight-android *detects* the device using a usb-a to usb-c adapter, but it improperly reconizes it as an Xbox360 controller. This introduces other issues within the game as some buttons on the controller map to the same inputs in-game. https://github.com/moonlight-stream/moonlight-android/blob/823593ddae0b0b2f1a8fcfdf29665b4d834d9c26/app/src/main/java/com/limelight/binding/input/driver/Xbox360Controller.java#L38

**Describe the solution you'd like**
I'd like to be able to have my application (clonehero) properly recognize the adapter as a "Harmonix Guitar Controller for Nintendo Wii" instead of nothing at all.

**Describe alternatives you've considered**
Plugging in my adapter to the physical machine is not an option because I am too far away from it.

**Additional context**
In the log we have the following, but it does not show up as a controller in-game:
```
000000.510 [SDL][ERROR] [MaybeAddDevice] IsJoystick fail 
000001.149 [Input][INFO] Input manager init, 165 game controller mappings loaded
...
000001.374 [Input][INFO] Controller #0 (Generic X-Box pad) connected, sdl_id: 0
```
here is the entire log: 
[cl.log](https://github.com/mariotaku/moonlight-tv/files/6888765/cl.log)

**Comment by mariotaku** [comment]
AFAIK GFE/Moonlight only recognize generic gamepad. (ABXY, DPad, thumbsticks, triggers, etc). What is the button layout of the input device?

**Comment by exalented** [comment]
I do not know what it uses for input (xinput, dinput, etc).
https://miltonwares.com/wp-content/uploads/2019/08/20190712_222737540_iOS.jpg

**Comment by mariotaku** [comment]
After double checking Moonlight's core, I'm pretty sure there's no native way to do that. If you're OK with rooting, you can use https://virtualhere.com/usb_server_software to achieve that.

**Comment by mariotaku** [comment]
Another not so elegant way is to map guitar controller to keyboard. But you will need manual config to do that.

**Comment by exalented** [comment]
So it's best to close this issue as any changes would have to be made upstream correct?

**Comment by mariotaku** [comment]
@exalented I don't think upstream can do anything about that. You need either use another product to handle USB, or I can add joypad-to-key mapping in moonlight-tv, although doing it on a TV would likely to be a pain.

**Comment by exalented** [comment]
IMHO joypad-to-key seems like it would be a pretty hacky sollution so where to go from here?

**Comment by mariotaku** [comment]
It's not a thing yet, but if I'm doing it, I'll create some configuration format, to map buttons to keyboard input for certain joystick. Because GFE lacks raw joystick support.

**Comment by mariotaku** [comment]
Just wanted to give some uncertain good news. GFE may have a way to send raw HID input event. I'll do some research for that.

**Comment by raeldor** [comment]
Have you looked into this for controller support with re-mapping etc...?
https://www.consoletuner.com/products/titan-one/

**Comment by mariotaku** [comment]
It turns out raw HID feature was not available in GFE. I have to close this.
