### ISSUE TITLE
[BUG] Significant audio latency

### ISSUE THREAD

**Issue by Phoenixmatrix** [mariotaku/moonlight-tv#94]
**Describe the bug**
Video works flawlessly, extremely low latency. Unfortunately the audio is delayed about 0.3s.

Using v0.9.6. I've tried a couple of random earlier versions, mainly around other audio bug fixes (eg: the 0.7.1 release) but I couldn't get those to stream at all. I did look at earlier issues and it sounds like when audio got fixed, people testing it did mention the audio latency.

**To Reproduce**
Any game, steam UI or desktop. Using PulseAudio (the others don't work for me), the audio will be significantly out of sync. If I enable the option to play audio on PC too, I can clearly hear the PC sound come much, much earlier.

**Expected behavior**
Audio being closer to being in sync with video.

**LG webOS TV (please complete the following information):**
 - Model: LG OLED55C7P
 - webOS version [e.g. 06.00.05]

> To check version, go to Settings > Quick Settings > General > About this TV > webOS TV Version

**Additional context**
Add any other context about the problem here. For example error message on the screen, and settings in Moonlight

**Comment by mariotaku** [comment]
According to the firmware version ( the version you shared is actually not webOS version), your TV should be running 3.x. Did you tried NetCast legacy decoder and default audio backend?

**Comment by mariotaku** [comment]
Hmm, PulseAudio is indeed a sub-optimal solution when any other doesn't work. I'll see if other audio interfaces works on webOS.

**Comment by aomader** [comment]
I second this. The only working audio decoder is PulseAudio, but the usage of it results in audio with a severe lag.

**Comment by mariotaku** [comment]
Audio latency with NDL/NetCast API should be low enough, there's no audio API with lower latency available. I'll be closing this as outdated.
