### ISSUE TITLE
[COMPAT] Can't pair PC and TV in local network, RTSP handshake failed error 552

### ISSUE THREAD

**Issue by LastOrderSK** [mariotaku/moonlight-tv#96]
## Basic information

 - Device model: 43UH650V-ZB 
 - Firmware version: 05.60.25 
 - webOS version: 3.4.0 
 - Moonlight version: 0.9.6 
 - Is audio working: No 
 - Is video working: No 
 - Is input working: Yes, I can connect my mouse and use my remote in the Moonlight app 

## Description

For the past few days I've tried connecting my PC and LG TV locally to play games, both connected to ethernet.
I have a GTX 980 ti with latest drivers and GFE, with AMD Ryzen CPU.
But I just get errors like "Failed Pairing, RTSP handshake failed (error code 552) and (error code 100). I've tried reinstalling moonlight using dev-manager, homebrew and through CLI.
I've tried also to disable antivirus and firewall but with no avail. I managed get it working one time by using DDU to uninstalling nvidia drivers and then reinstalling GFE and drivers. Sadly it stopped working again a little bit later (probably after a restart of PC or TV). I've tried to do that again but can't get i working again, no matter what.

Any ideas how to fix this and get it working? Is there a problem with the current nvidia driver or GFE?

**Comment by mariotaku** [comment]
This was some issue that I never been able to reproduce. It seems that it also happens quite often on moonlight-embedded based implementations. Maybe logs from your host will provide some information. They are located in `C:\ProgramData\NVIDIA Corporation\NvStream`.

**Comment by LastOrderSK** [comment]
[NvStreamerCurrent.log](https://github.com/mariotaku/moonlight-tv/files/7163806/NvStreamerCurrent.log)
[NvStreamerOld.log](https://github.com/mariotaku/moonlight-tv/files/7163807/NvStreamerOld.log)

Okay, this is interesting. I tried pairing two times in a row and it actually paired the second time. I didn't do anything. So I'll attach both logs.

The "NvStreamerOld" log was created first when it failed pairing, and on the TV I got an error "Paring Failed, no element found". However I can see all the games on the TV but when launching a game, it throws a error "RTSP handshake failed (error code 552)"

The "NvStreamerCurrent" log was created when I successfully paired the second time right now. I tried launching a game and it worked.

One thing to note is that streaming to android, windows and linux works perfectly from this PC.

**Comment by mariotaku** [comment]
Thank you. I'll compare two logs when I'm available.

**Comment by dipar2009** [comment]
Did anyone figure this out? I'm having error 11 which is supposed to be related with 552 (?)

**Comment by mariotaku** [comment]
Closed due to inactivity.
