### ISSUE TITLE
[BUG] Rare Settings UI hard crash

### ISSUE THREAD

**Issue by exalented** [mariotaku/moonlight-tv#97]
**Describe the bug**
When one moves in and out of the settings UI the client sometimes crashes.

**To Reproduce**
Steps to reproduce the behavior. Repeat steps 2 and 3 consecutively.:
1. Launch moonlight
2. Click on settings
3. Exit settings
4. hard crash

**Expected behavior**
No crashing plz

**LG webOS TV:**
 - Model: 65NANO90UNA
 - webOS version 5.2.3-252111

**Additional context**
This is easier to repoduce if the client is paired and able to **access** a gamestream server. Sometimes the client segfaults and other times webos will abort the process.

**Logs**
I've collected 8 crash logs, the first 4 without being connected to a gamestream server.
```
$ ./ares-novacom -r "ls -la /tmp/faultmanager/crash/*.gz" -d lgtv
16:50 /tmp/faultmanager/crash/RDXD_moonlight__Linux Crash: moonlight crashes at location ?var?palm?jail?com.limelight.webos?lib?libc-2.28.so (__libc_do_syscall+0x5) [0x96bde886]____moonlight.2165.wLxjNg.gz
16:51 /tmp/faultmanager/crash/RDXD_moonlight__Linux Crash: moonlight crashes at location ?var?palm?jail?com.limelight.webos?lib?libc-2.28.so (__libc_do_syscall+0x5) [0x96c12886]____moonlight.3281.nIer4f.gz
16:51 /tmp/faultmanager/crash/RDXD_moonlight__Linux Crash: moonlight crashes at location ?var?palm?jail?com.limelight.webos?media?developer?apps?usr?palm?applications?com.limelight.webos?moonlight (apploader_task_execute+0x30) [0xe6a0]____moonlight.4111.PffMjJ.gz
16:51 /tmp/faultmanager/crash/RDXD_moonlight__Linux Crash: moonlight crashes at location ?var?palm?jail?com.limelight.webos?media?developer?apps?usr?palm?applications?com.limelight.webos?moonlight (gs_applist+0x24) [0x304c4]____moonlight.4920.DRrdLa.gz
16:53 /tmp/faultmanager/crash/RDXD_moonlight__Linux Crash: moonlight crashes at location ?var?palm?jail?com.limelight.webos?usr?lib?libcrypto.so.1.0.2 (BN_free+0x5) [0x96a0e79a]____moonlight.5831.rBzau1.gz
16:53 /tmp/faultmanager/crash/RDXD_moonlight__Linux Crash: moonlight crashes at location ?var?palm?jail?com.limelight.webos?usr?lib?libcrypto.so.1.0.2 (X509_STORE_add_cert+0x3d) [0x96ab0faa]____moonlight.7644.PKZNe6.gz
16:53 /tmp/faultmanager/crash/RDXD_moonlight__Linux Crash: moonlight crashes at location ?var?palm?jail?com.limelight.webos?usr?lib?libcrypto.so.1.0.2 (X509_STORE_add_cert+0x3d) [0x96addfaa]____moonlight.6457.9Ye8Oi.gz
16:53 /tmp/faultmanager/crash/RDXD_moonlight__Linux Crash: moonlight crashes at location ?var?palm?jail?com.limelight.webos?usr?lib?libssl.so.1.0.2 (SSLv3_client_method+0x5ac7) [0x96af981c]____moonlight.7003.NwwdC2.gz
..
..
./ares-novacom -r "zcat /tmp/faultmanager/crash/*" -d lgtv >> 8crashLogs_v0.9.92.log
```
[8crashLogs_v0.9.92.log](https://github.com/mariotaku/moonlight-tv/files/7247980/8crashLogs_v0.9.92.log)

[3crashLogs_v0.9.93.log](https://github.com/mariotaku/moonlight-tv/files/7261342/3crashLogs_v0.9.93.log)

[crashLogs_v1.2.0.log](https://github.com/mariotaku/moonlight-tv/files/7541040/crashLogs_v1.2.0.log)

[crashLogs_send_core_v1.2.0.log](https://github.com/mariotaku/moonlight-tv/files/7541200/crashLogs_send_core_v1.2.0.log)

[crashLogs_v1.2.3-v1.2.4.log](https://github.com/mariotaku/moonlight-tv/files/7640904/crashLogs_v1.2.3-v1.2.4.log)

**Comment by mariotaku** [comment]
Might be fixed in v0.9.93. Let's see.

**Comment by exalented** [comment]
Unfortunately not. I've added more logs.

**Comment by mariotaku** [comment]
Does this still happen in recent versions?

**Comment by exalented** [comment]
Yes. This still occurs in 1.2.0, but it's pretty rare and it's harder to repro.

**Comment by mariotaku** [comment]
Somehow the log get truncated again and lost all stack traces. I think it's about LVGL's event system.

**Comment by mariotaku** [comment]
I think this was related to some illegal memory access and might be fixed in later released. Please see if v1.2.3 and later fixed this issue.

**Comment by exalented** [comment]
This issue is still present in v1.2.3.

**Comment by mariotaku** [comment]
I can see 2 different errors. But the second one was truncated. Which way you are using to dump debug log?

**Comment by exalented** [comment]
zcat

**Comment by mariotaku** [comment]
Moonlight-TV has changed a lot since then. I'll close this and please create new issue when you see anything wrong.
